/**
 * @distilled.cloud/freestyle — Freestyle SDK for Effect.
 *
 * `./services` is generated by `scripts/generate.ts` from the Smithy models
 * in `.generated-specs` (written by `scripts/convert.ts` from the OpenAPI
 * spec). Everything else in this folder is hand-written.
 *
 * One module per Freestyle API tag: `vms`, `filesystem`, `snapshots`,
 * `vpcs`, `domains`, `identities`, `firewall`, `hardware`, `tls`,
 * `tunnels`, `backgroundRequests`.
 *
 * File read/write/upload-chunk bodies are `application/octet-stream` — the
 * OpenAPI converter models JSON only, so those operations generate without
 * a binary payload schema. PTY open/attach are WebSocket upgrades (`101`);
 * use {@link connectPty} / {@link reconnectPty} instead of the generated
 * REST stubs.
 *
 * @example
 * ```ts
 * import * as Effect from "effect/Effect";
 * import * as Layer from "effect/Layer";
 * import { FetchHttpClient } from "effect/unstable/http";
 * import * as Freestyle from "@distilled.cloud/freestyle";
 *
 * const Live = Layer.mergeAll(
 *   FetchHttpClient.layer,
 *   Freestyle.CredentialsFromEnv, // FREESTYLE_API_KEY
 *   Freestyle.FreestyleProtocol,
 * );
 *
 * const program = Effect.gen(function* () {
 *   const vm = yield* Freestyle.vms.createVm({
 *     firewall: { rules: [] },
 *   });
 *   const { stdout } = yield* Freestyle.vms.execVm({
 *     vmIdOrSlug: vm.id,
 *     command: "uname -a",
 *   });
 *
 *   const pty = yield* Freestyle.connectPty({
 *     vmIdOrSlug: vm.id,
 *     cols: 120,
 *     rows: 30,
 *   });
 *   pty.write("echo hello\\n");
 *   pty.detach();
 * });
 *
 * program.pipe(Effect.provide(Live), Effect.runPromise);
 * ```
 */
export * from "./credentials.ts";
export * from "./errors.ts";
export * as T from "./traits.ts";
export {
  FreestyleProtocol,
  type FreestyleOpError,
  type FreestyleOpContext,
} from "./protocol.ts";
export { paginateOffset } from "./pagination.ts";
export {
  connectPty,
  reconnectPty,
  PtyError,
  type ConnectPtyOptions,
  type ReconnectPtyOptions,
  type PtySession,
} from "./pty.ts";
export * as Retry from "./retry.ts";
export * from "./services/index.ts";
