/**
 * @distilled.cloud/stackit — STACKIT Cloud API SDK for Effect.
 *
 * `./services` is generated by `scripts/generate.ts` from the Smithy models
 * in `.generated-specs` (written by `scripts/convert.ts` from the OpenAPI
 * documents mirrored at `specs/spec-mirror-stackit/specs/`). Everything else
 * in this folder is hand-written.
 *
 * One module per STACKIT product (IaaS, SKE, DNS, Postgres Flex, …), using
 * that product's latest published OpenAPI version. Auth is a service-account
 * bearer token (`STACKIT_SERVICE_ACCOUNT_TOKEN`); each product's host is
 * rewritten for `STACKIT_REGION` (default `eu01`).
 *
 * @example
 * ```ts
 * import * as Stackit from "@distilled.cloud/stackit";
 *
 * const { zones } = yield* Stackit.dns.listZones({
 *   projectId: "...",
 * });
 * ```
 */
export * from "./credentials.ts";
export * from "./errors.ts";
export * as T from "./traits.ts";
export {
  StackitProtocol,
  applyRegion,
  type StackitOpError,
  type StackitOpContext,
} from "./protocol.ts";
export { paginateByTotalPages } from "./pagination.ts";
export * as Retry from "./retry.ts";
export * from "./services/index.ts";
