import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-openai). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownOpenAIError } from "../errors.ts";
import { paginateAfter } from "../pagination.ts";
import { OpenAIProtocol, type OpenAIOpError, type OpenAIOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { OpenAIOpError, OpenAIOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

export interface ListAuditLogsRequestEffectiveAt {
  /** Return only events whose `effective_at` (Unix seconds) is greater than this value. */
  gt?: number;
  /** Return only events whose `effective_at` (Unix seconds) is greater than or equal to this value. */
  gte?: number;
  /** Return only events whose `effective_at` (Unix seconds) is less than this value. */
  lt?: number;
  /** Return only events whose `effective_at` (Unix seconds) is less than or equal to this value. */
  lte?: number;
}
export const ListAuditLogsRequestEffectiveAt = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    gt: S.optional(S.Number),
    gte: S.optional(S.Number),
    lt: S.optional(S.Number),
    lte: S.optional(S.Number),
  }),
).annotate({
  identifier: "ListAuditLogsRequestEffectiveAt",
}) as any as S.Schema<ListAuditLogsRequestEffectiveAt>;

export type ListAuditLogsRequestProjectIdsList = Array<string>;
export const ListAuditLogsRequestProjectIdsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<ListAuditLogsRequestProjectIdsList>;

/** The event type. */
export type AuditLogEventType =
  | "api_key.created"
  | "api_key.updated"
  | "api_key.deleted"
  | "certificate.created"
  | "certificate.updated"
  | "certificate.deleted"
  | "certificates.activated"
  | "certificates.deactivated"
  | "checkpoint.permission.created"
  | "checkpoint.permission.deleted"
  | "external_key.registered"
  | "external_key.removed"
  | "external_storage.registered"
  | "external_storage.removed"
  | "group.created"
  | "group.updated"
  | "group.deleted"
  | "invite.sent"
  | "invite.accepted"
  | "invite.deleted"
  | "ip_allowlist.created"
  | "ip_allowlist.updated"
  | "ip_allowlist.deleted"
  | "ip_allowlist.config.activated"
  | "ip_allowlist.config.deactivated"
  | "login.succeeded"
  | "login.failed"
  | "logout.succeeded"
  | "logout.failed"
  | "organization.updated"
  | "project.created"
  | "project.updated"
  | "project.archived"
  | "project.deleted"
  | "rate_limit.updated"
  | "rate_limit.deleted"
  | "resource.deleted"
  | "tunnel.created"
  | "tunnel.updated"
  | "tunnel.deleted"
  | "workload_identity_provider.created"
  | "workload_identity_provider.updated"
  | "workload_identity_provider.deleted"
  | "workload_identity_provider_mapping.created"
  | "workload_identity_provider_mapping.updated"
  | "workload_identity_provider_mapping.deleted"
  | "role.created"
  | "role.updated"
  | "role.deleted"
  | "role.assignment.created"
  | "role.assignment.deleted"
  | "role.bound_to_resource"
  | "role.unbound_from_resource"
  | "scim.enabled"
  | "scim.disabled"
  | "service_account.created"
  | "service_account.updated"
  | "service_account.deleted"
  | "user.added"
  | "user.updated"
  | "user.deleted"
  | "tenant.metadata.updated"
  | "tenant.microsoft_entra_mapping.upserted"
  | "tenant.microsoft_entra_mapping.deleted"
  | "tenant.workload_identity.provider.created"
  | "tenant.workload_identity.provider.updated"
  | "tenant.workload_identity.provider.archived"
  | "tenant.workload_identity.mapping.created"
  | "tenant.workload_identity.mapping.updated"
  | "tenant.workload_identity.mapping.archived"
  | "tenant.workload_identity.binding.created"
  | "tenant.workload_identity.principal.provisioned"
  | "tenant.workload_identity.access_token.issued"
  | "tenant.admin_api_key.created"
  | "tenant.admin_api_key.updated"
  | "tenant.admin_api_key.deleted"
  | "tenant.project_api_key.created"
  | "tenant.trusted_access.business_verification.started"
  | "tenant.trusted_access.application.submitted"
  | "tenant.chatgpt_access_token.revoked"
  | "tenant.migration.completed"
  | "tenant.sso.migrated"
  | "tenant.domains.migrated"
  | "tenant.sso_connection.created"
  | "tenant.sso_connection.updated"
  | "tenant.sso_connection.deleted"
  | "tenant.sso_connection.setup.started"
  | "tenant.policy.created"
  | "tenant.policy.updated"
  | "tenant.policy.deleted"
  | "tenant.policy.attached"
  | "tenant.policy.detached"
  | "tenant.principal_authentication_policy.resolved"
  | "tenant.scim.setup.started"
  | "tenant.scim.deletion.requested"
  | "tenant.scim.directory.created"
  | "tenant.product_access_policy.updated"
  | "tenant.resource_share_grant.created"
  | "tenant.resource_share_grant.updated"
  | "tenant.resource_share_grant.accepted"
  | "tenant.resource_share_grant.declined"
  | "tenant.resource_share_grant.revoked"
  | "tenant.resource_share_grant.deleted"
  | "tenant.service_account.updated"
  | "tenant.service_account.deleted"
  | "tenant.service_account.token.revoked"
  | "tenant.billing.overage_limit.updated"
  | "tenant.billing.alerts.updated"
  | "tenant.billing.info.updated"
  | "tenant.usage_limit.workspace.updated"
  | "tenant.usage_limit.group.updated"
  | "tenant.usage_limit.user.updated"
  | "tenant.usage_limit.increase_request.updated"
  | "tenant.usage_limit.increase_request.resolved"
  | "tenant.group.created"
  | "tenant.group.updated"
  | "tenant.group.deleted"
  | "tenant.group.member.added"
  | "tenant.group.member.removed"
  | "tenant.migration_rollout.status.updated"
  | "tenant.migration_rollout.tier.updated"
  | "tenant.role.metadata.updated"
  | "tenant.custom_role.created"
  | "tenant.custom_role.updated"
  | "tenant.custom_role.deleted"
  | "tenant.role_assignment.created"
  | "tenant.role_assignment.deleted"
  | "tenant.resource_role_assignment.created"
  | "tenant.resource_role_assignment.deleted"
  | "tenant.resource_access.updated"
  | "tenant.resource_access.deleted"
  | "tenant.ads_account.onboarding.redemption"
  | "tenant.session_policy.created"
  | "tenant.session_policy.updated"
  | "tenant.session_policy.deleted"
  | "tenant.session_revocation.started"
  | "tenant.third_party_app_policy.updated"
  | "tenant.user.added"
  | "tenant.user.updated"
  | "tenant.user.removed"
  | "tenant.user.looked_up"
  | "tenant.user.invited"
  | "tenant.membership.revoked"
  | "tenant.api_organization_invite.upserted"
  | "tenant.api_organization_invite.deleted"
  | "tenant.chatgpt_workspace_invite.upserted"
  | "tenant.membership.accepted"
  | "tenant.membership.declined"
  | "tenant.workspace_invite_email_settings.updated";
export const AuditLogEventType = S.String;

export type ListAuditLogsRequestEventTypesList = Array<AuditLogEventType | (string & {})>;
export const ListAuditLogsRequestEventTypesList = /*@__PURE__*/ S.Array(
  AuditLogEventType,
) as any as S.Schema<ListAuditLogsRequestEventTypesList>;

export type ListAuditLogsRequestActorIdsList = Array<string>;
export const ListAuditLogsRequestActorIdsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<ListAuditLogsRequestActorIdsList>;

export type ListAuditLogsRequestActorEmailsList = Array<string>;
export const ListAuditLogsRequestActorEmailsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<ListAuditLogsRequestActorEmailsList>;

export type ListAuditLogsRequestResourceIdsList = Array<string>;
export const ListAuditLogsRequestResourceIdsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<ListAuditLogsRequestResourceIdsList>;

export interface ListAuditLogsRequest {
  /** Return only events whose `effective_at` (Unix seconds) is in this range. */
  effective_at?: ListAuditLogsRequestEffectiveAt;
  /** Return only events for these projects. */
  project_ids__?: ListAuditLogsRequestProjectIdsList;
  /** Return only events with a `type` in one of these values. For example, `project.created`. For all options, see the documentation for the [audit log object](https://developers.openai.com/api/reference/resources/admin/subresources/organization/subresources/audit_logs). */
  event_types__?: ListAuditLogsRequestEventTypesList;
  /** Return only events performed by these actors. Can be a user ID, a service account ID, or an api key tracking ID. */
  actor_ids__?: ListAuditLogsRequestActorIdsList;
  /** Return only events performed by users with these emails. */
  actor_emails__?: ListAuditLogsRequestActorEmailsList;
  /** Return only events performed on these targets. For example, a project ID updated. For ChatGPT connector role events, use the workspace connector resource ID shown in `details.id`, such as `<workspace_id>__<connector_id>`. */
  resource_ids__?: ListAuditLogsRequestResourceIdsList;
  /** Return only tenant-scoped events associated with this organization. Required for tenant-scoped events such as `role.bound_to_resource` and `role.unbound_from_resource`. When `true`, all supplied event types must be tenant-scoped. */
  tenant_only?: boolean;
  /** A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 20. */
  limit?: number;
  /** A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with obj_foo, your subsequent call can include after=obj_foo in order to fetch the next page of the list. */
  after?: string;
  /** A cursor for use in pagination. `before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with obj_foo, your subsequent call can include before=obj_foo in order to fetch the previous page of the list. */
  before?: string;
}
export const ListAuditLogsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    effective_at: S.optional(ListAuditLogsRequestEffectiveAt.pipe(T.Query())),
    project_ids__: S.optional(ListAuditLogsRequestProjectIdsList.pipe(T.Query("project_ids[]"))),
    event_types__: S.optional(ListAuditLogsRequestEventTypesList.pipe(T.Query("event_types[]"))),
    actor_ids__: S.optional(ListAuditLogsRequestActorIdsList.pipe(T.Query("actor_ids[]"))),
    actor_emails__: S.optional(ListAuditLogsRequestActorEmailsList.pipe(T.Query("actor_emails[]"))),
    resource_ids__: S.optional(ListAuditLogsRequestResourceIdsList.pipe(T.Query("resource_ids[]"))),
    tenant_only: S.optional(S.Boolean.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    after: S.optional(S.String.pipe(T.Query())),
    before: S.optional(S.String.pipe(T.Query())),
  })
    .pipe(T.Http({ method: "GET", uri: "/organization/audit_logs", code: 200 }))
    .pipe(T.AdminAuth()),
).annotate({ identifier: "ListAuditLogsRequest" }) as any as S.Schema<ListAuditLogsRequest>;

export type ListAuditLogsResponseObject = "list";
export const ListAuditLogsResponseObject = S.String;

/** The project that the action was scoped to. Absent for actions not scoped to projects. Note that any admin actions taken via Admin API keys are associated with the default project. */
export interface AuditLogProject {
  /** The project ID. */
  id?: string;
  /** The project title. */
  name?: string;
}
export const AuditLogProject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
  }),
).annotate({ identifier: "AuditLogProject" }) as any as S.Schema<AuditLogProject>;

/** The type of actor. Is either `session` or `api_key`. */
export type AuditLogActorType = "session" | "api_key";
export const AuditLogActorType = S.String;

/** The user who performed the audit logged action. */
export interface AuditLogActorUser {
  /** The user id. */
  id?: string;
  /** The user email. */
  email?: string;
}
export const AuditLogActorUser = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    email: S.optional(S.String),
  }),
).annotate({ identifier: "AuditLogActorUser" }) as any as S.Schema<AuditLogActorUser>;

/** The session in which the audit logged action was performed. */
export interface AuditLogActorSession {
  user?: AuditLogActorUser;
  /** The IP address from which the action was performed. */
  ip_address?: string;
}
export const AuditLogActorSession = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    user: S.optional(AuditLogActorUser),
    ip_address: S.optional(S.String),
  }),
).annotate({ identifier: "AuditLogActorSession" }) as any as S.Schema<AuditLogActorSession>;

/** The type of API key. Can be either `user` or `service_account`. */
export type AuditLogActorApiKeyType = "user" | "service_account";
export const AuditLogActorApiKeyType = S.String;

/** The service account that performed the audit logged action. */
export interface AuditLogActorServiceAccount {
  /** The service account id. */
  id?: string;
}
export const AuditLogActorServiceAccount = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogActorServiceAccount",
}) as any as S.Schema<AuditLogActorServiceAccount>;

/** The API Key used to perform the audit logged action. */
export interface AuditLogActorApiKey {
  /** The tracking id of the API key. */
  id?: string;
  /** The type of API key. Can be either `user` or `service_account`. */
  type?: AuditLogActorApiKeyType;
  user?: AuditLogActorUser;
  service_account?: AuditLogActorServiceAccount;
}
export const AuditLogActorApiKey = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    type: S.optional(AuditLogActorApiKeyType),
    user: S.optional(AuditLogActorUser),
    service_account: S.optional(AuditLogActorServiceAccount),
  }),
).annotate({ identifier: "AuditLogActorApiKey" }) as any as S.Schema<AuditLogActorApiKey>;

/** The actor who performed the audit logged action. */
export interface AuditLogActor {
  /** The type of actor. Is either `session` or `api_key`. */
  type?: AuditLogActorType;
  session?: AuditLogActorSession;
  api_key?: AuditLogActorApiKey;
}
export const AuditLogActor = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.optional(AuditLogActorType),
    session: S.optional(AuditLogActorSession),
    api_key: S.optional(AuditLogActorApiKey),
  }),
).annotate({ identifier: "AuditLogActor" }) as any as S.Schema<AuditLogActor>;

/** A list of scopes allowed for the API key, e.g. `["api.model.request"]` */
export type AuditLogApiKeyCreatedDataScopesList = Array<string>;
export const AuditLogApiKeyCreatedDataScopesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<AuditLogApiKeyCreatedDataScopesList>;

/** The payload used to create the API key. */
export interface AuditLogApiKeyCreatedData {
  /** A list of scopes allowed for the API key, e.g. `["api.model.request"]` */
  scopes?: AuditLogApiKeyCreatedDataScopesList;
}
export const AuditLogApiKeyCreatedData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    scopes: S.optional(AuditLogApiKeyCreatedDataScopesList),
  }),
).annotate({
  identifier: "AuditLogApiKeyCreatedData",
}) as any as S.Schema<AuditLogApiKeyCreatedData>;

/** The details for events with this `type`. */
export interface AuditLogApiKeyCreated {
  /** The tracking ID of the API key. */
  id?: string;
  /** The payload used to create the API key. */
  data?: AuditLogApiKeyCreatedData;
}
export const AuditLogApiKeyCreated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    data: S.optional(AuditLogApiKeyCreatedData),
  }),
).annotate({ identifier: "AuditLogApiKeyCreated" }) as any as S.Schema<AuditLogApiKeyCreated>;

/** A list of scopes allowed for the API key, e.g. `["api.model.request"]` */
export type AuditLogApiKeyUpdatedChangesRequestedScopesList = Array<string>;
export const AuditLogApiKeyUpdatedChangesRequestedScopesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<AuditLogApiKeyUpdatedChangesRequestedScopesList>;

/** The payload used to update the API key. */
export interface AuditLogApiKeyUpdatedChangesRequested {
  /** A list of scopes allowed for the API key, e.g. `["api.model.request"]` */
  scopes?: AuditLogApiKeyUpdatedChangesRequestedScopesList;
}
export const AuditLogApiKeyUpdatedChangesRequested = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    scopes: S.optional(AuditLogApiKeyUpdatedChangesRequestedScopesList),
  }),
).annotate({
  identifier: "AuditLogApiKeyUpdatedChangesRequested",
}) as any as S.Schema<AuditLogApiKeyUpdatedChangesRequested>;

/** The details for events with this `type`. */
export interface AuditLogApiKeyUpdated {
  /** The tracking ID of the API key. */
  id?: string;
  /** The payload used to update the API key. */
  changes_requested?: AuditLogApiKeyUpdatedChangesRequested;
}
export const AuditLogApiKeyUpdated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    changes_requested: S.optional(AuditLogApiKeyUpdatedChangesRequested),
  }),
).annotate({ identifier: "AuditLogApiKeyUpdated" }) as any as S.Schema<AuditLogApiKeyUpdated>;

/** The details for events with this `type`. */
export interface AuditLogApiKeyDeleted {
  /** The tracking ID of the API key. */
  id?: string;
}
export const AuditLogApiKeyDeleted = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
  }),
).annotate({ identifier: "AuditLogApiKeyDeleted" }) as any as S.Schema<AuditLogApiKeyDeleted>;

/** The payload used to create the checkpoint permission. */
export interface AuditLogCheckpointPermissionCreatedData {
  /** The ID of the project that the checkpoint permission was created for. */
  project_id?: string;
  /** The ID of the fine-tuned model checkpoint. */
  fine_tuned_model_checkpoint?: string;
}
export const AuditLogCheckpointPermissionCreatedData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.optional(S.String),
    fine_tuned_model_checkpoint: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogCheckpointPermissionCreatedData",
}) as any as S.Schema<AuditLogCheckpointPermissionCreatedData>;

/** The project and fine-tuned model checkpoint that the checkpoint permission was created for. */
export interface AuditLogCheckpointPermissionCreated {
  /** The ID of the checkpoint permission. */
  id?: string;
  /** The payload used to create the checkpoint permission. */
  data?: AuditLogCheckpointPermissionCreatedData;
}
export const AuditLogCheckpointPermissionCreated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    data: S.optional(AuditLogCheckpointPermissionCreatedData),
  }),
).annotate({
  identifier: "AuditLogCheckpointPermissionCreated",
}) as any as S.Schema<AuditLogCheckpointPermissionCreated>;

/** The details for events with this `type`. */
export interface AuditLogCheckpointPermissionDeleted {
  /** The ID of the checkpoint permission. */
  id?: string;
}
export const AuditLogCheckpointPermissionDeleted = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogCheckpointPermissionDeleted",
}) as any as S.Schema<AuditLogCheckpointPermissionDeleted>;

/** The details for events with this `type`. */
export interface AuditLogExternalKeyRegistered {
  /** The ID of the external key configuration. */
  id?: string;
  /** The configuration for the external key. */
  data?: unknown;
}
export const AuditLogExternalKeyRegistered = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    data: S.optional(S.Unknown),
  }),
).annotate({
  identifier: "AuditLogExternalKeyRegistered",
}) as any as S.Schema<AuditLogExternalKeyRegistered>;

/** The details for events with this `type`. */
export interface AuditLogExternalKeyRemoved {
  /** The ID of the external key configuration. */
  id?: string;
}
export const AuditLogExternalKeyRemoved = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogExternalKeyRemoved",
}) as any as S.Schema<AuditLogExternalKeyRemoved>;

export type AwsExternalStorageProviderResponseType = "aws";
export const AwsExternalStorageProviderResponseType = S.String;

export interface AwsExternalStorageProviderResponse {
  type: AwsExternalStorageProviderResponseType;
  account_id: string;
  region: string;
  bucket: string;
  role_arn: string;
  external_id: string;
}
export const AwsExternalStorageProviderResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: AwsExternalStorageProviderResponseType,
    account_id: S.String,
    region: S.String,
    bucket: S.String,
    role_arn: S.String,
    external_id: S.String,
  }),
).annotate({
  identifier: "AwsExternalStorageProviderResponse",
}) as any as S.Schema<AwsExternalStorageProviderResponse>;

export type AzureExternalStorageProviderResponseType = "azure";
export const AzureExternalStorageProviderResponseType = S.String;

export interface AzureExternalStorageProviderResponse {
  type: AzureExternalStorageProviderResponseType;
  tenant_id: string;
  subscription_id: string;
  resource_group: string;
  account_name: string;
  container: string;
  region: string;
}
export const AzureExternalStorageProviderResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: AzureExternalStorageProviderResponseType,
    tenant_id: S.String,
    subscription_id: S.String,
    resource_group: S.String,
    account_name: S.String,
    container: S.String,
    region: S.String,
  }),
).annotate({
  identifier: "AzureExternalStorageProviderResponse",
}) as any as S.Schema<AzureExternalStorageProviderResponse>;

export type GcpExternalStorageProviderResponseType = "gcp";
export const GcpExternalStorageProviderResponseType = S.String;

export interface GcpExternalStorageProviderResponse {
  type: GcpExternalStorageProviderResponseType;
  bucket: string;
  workload_identity_project_number: string;
  workload_identity_pool_id: string;
  workload_identity_provider_id: string;
  region: string;
  audience: string;
}
export const GcpExternalStorageProviderResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: GcpExternalStorageProviderResponseType,
    bucket: S.String,
    workload_identity_project_number: S.String,
    workload_identity_pool_id: S.String,
    workload_identity_provider_id: S.String,
    region: S.String,
    audience: S.String,
  }),
).annotate({
  identifier: "GcpExternalStorageProviderResponse",
}) as any as S.Schema<GcpExternalStorageProviderResponse>;

export type Provider =
  | AwsExternalStorageProviderResponse
  | AzureExternalStorageProviderResponse
  | GcpExternalStorageProviderResponse;
export const Provider = S.Unknown as any as S.Schema<Provider>;

/** The configuration for the external storage. */
export interface AuditLogExternalStorageRegisteredData {
  /** The external storage provider configuration. */
  provider?: Provider;
  /** The OpenAI geography derived from the storage region. */
  geography?: string;
}
export const AuditLogExternalStorageRegisteredData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    provider: S.optional(Provider),
    geography: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogExternalStorageRegisteredData",
}) as any as S.Schema<AuditLogExternalStorageRegisteredData>;

/** The details for events with this `type`. */
export interface AuditLogExternalStorageRegistered {
  /** The ID of the external storage configuration. */
  id?: string;
  /** The configuration for the external storage. */
  data?: AuditLogExternalStorageRegisteredData;
}
export const AuditLogExternalStorageRegistered = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    data: S.optional(AuditLogExternalStorageRegisteredData),
  }),
).annotate({
  identifier: "AuditLogExternalStorageRegistered",
}) as any as S.Schema<AuditLogExternalStorageRegistered>;

/** The details for events with this `type`. */
export interface AuditLogExternalStorageRemoved {
  /** The ID of the external storage configuration. */
  id?: string;
}
export const AuditLogExternalStorageRemoved = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogExternalStorageRemoved",
}) as any as S.Schema<AuditLogExternalStorageRemoved>;

/** Information about the created group. */
export interface AuditLogGroupCreatedData {
  /** The group name. */
  group_name?: string;
}
export const AuditLogGroupCreatedData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    group_name: S.optional(S.String),
  }),
).annotate({ identifier: "AuditLogGroupCreatedData" }) as any as S.Schema<AuditLogGroupCreatedData>;

/** The details for events with this `type`. */
export interface AuditLogGroupCreated {
  /** The ID of the group. */
  id?: string;
  /** Information about the created group. */
  data?: AuditLogGroupCreatedData;
}
export const AuditLogGroupCreated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    data: S.optional(AuditLogGroupCreatedData),
  }),
).annotate({ identifier: "AuditLogGroupCreated" }) as any as S.Schema<AuditLogGroupCreated>;

/** The payload used to update the group. */
export interface AuditLogGroupUpdatedChangesRequested {
  /** The updated group name. */
  group_name?: string;
}
export const AuditLogGroupUpdatedChangesRequested = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    group_name: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogGroupUpdatedChangesRequested",
}) as any as S.Schema<AuditLogGroupUpdatedChangesRequested>;

/** The details for events with this `type`. */
export interface AuditLogGroupUpdated {
  /** The ID of the group. */
  id?: string;
  /** The payload used to update the group. */
  changes_requested?: AuditLogGroupUpdatedChangesRequested;
}
export const AuditLogGroupUpdated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    changes_requested: S.optional(AuditLogGroupUpdatedChangesRequested),
  }),
).annotate({ identifier: "AuditLogGroupUpdated" }) as any as S.Schema<AuditLogGroupUpdated>;

/** The details for events with this `type`. */
export interface AuditLogGroupDeleted {
  /** The ID of the group. */
  id?: string;
}
export const AuditLogGroupDeleted = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
  }),
).annotate({ identifier: "AuditLogGroupDeleted" }) as any as S.Schema<AuditLogGroupDeleted>;

/** The details for events with this `type`. */
export interface AuditLogScimEnabled {
  /** The ID of the SCIM was enabled for. */
  id?: string;
}
export const AuditLogScimEnabled = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
  }),
).annotate({ identifier: "AuditLogScimEnabled" }) as any as S.Schema<AuditLogScimEnabled>;

/** The details for events with this `type`. */
export interface AuditLogScimDisabled {
  /** The ID of the SCIM was disabled for. */
  id?: string;
}
export const AuditLogScimDisabled = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
  }),
).annotate({ identifier: "AuditLogScimDisabled" }) as any as S.Schema<AuditLogScimDisabled>;

/** The payload used to create the invite. */
export interface AuditLogInviteSentData {
  /** The email invited to the organization. */
  email?: string;
  /** The role the email was invited to be. Is either `owner` or `member`. */
  role?: string;
}
export const AuditLogInviteSentData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    email: S.optional(S.String),
    role: S.optional(S.String),
  }),
).annotate({ identifier: "AuditLogInviteSentData" }) as any as S.Schema<AuditLogInviteSentData>;

/** The details for events with this `type`. */
export interface AuditLogInviteSent {
  /** The ID of the invite. */
  id?: string;
  /** The payload used to create the invite. */
  data?: AuditLogInviteSentData;
}
export const AuditLogInviteSent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    data: S.optional(AuditLogInviteSentData),
  }),
).annotate({ identifier: "AuditLogInviteSent" }) as any as S.Schema<AuditLogInviteSent>;

/** The details for events with this `type`. */
export interface AuditLogInviteAccepted {
  /** The ID of the invite. */
  id?: string;
}
export const AuditLogInviteAccepted = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
  }),
).annotate({ identifier: "AuditLogInviteAccepted" }) as any as S.Schema<AuditLogInviteAccepted>;

/** The details for events with this `type`. */
export type AuditLogInviteDeleted = AuditLogInviteAccepted;
export const AuditLogInviteDeleted = AuditLogInviteAccepted;

/** The IP addresses or CIDR ranges included in the configuration. */
export type AuditLogIpAllowlistCreatedAllowedIpsList = Array<string>;
export const AuditLogIpAllowlistCreatedAllowedIpsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<AuditLogIpAllowlistCreatedAllowedIpsList>;

/** The details for events with this `type`. */
export interface AuditLogIpAllowlistCreated {
  /** The ID of the IP allowlist configuration. */
  id?: string;
  /** The name of the IP allowlist configuration. */
  name?: string;
  /** The IP addresses or CIDR ranges included in the configuration. */
  allowed_ips?: AuditLogIpAllowlistCreatedAllowedIpsList;
}
export const AuditLogIpAllowlistCreated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    allowed_ips: S.optional(AuditLogIpAllowlistCreatedAllowedIpsList),
  }),
).annotate({
  identifier: "AuditLogIpAllowlistCreated",
}) as any as S.Schema<AuditLogIpAllowlistCreated>;

/** The updated set of IP addresses or CIDR ranges in the configuration. */
export type AuditLogIpAllowlistUpdatedAllowedIpsList = Array<string>;
export const AuditLogIpAllowlistUpdatedAllowedIpsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<AuditLogIpAllowlistUpdatedAllowedIpsList>;

/** The details for events with this `type`. */
export interface AuditLogIpAllowlistUpdated {
  /** The ID of the IP allowlist configuration. */
  id?: string;
  /** The updated set of IP addresses or CIDR ranges in the configuration. */
  allowed_ips?: AuditLogIpAllowlistUpdatedAllowedIpsList;
}
export const AuditLogIpAllowlistUpdated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    allowed_ips: S.optional(AuditLogIpAllowlistUpdatedAllowedIpsList),
  }),
).annotate({
  identifier: "AuditLogIpAllowlistUpdated",
}) as any as S.Schema<AuditLogIpAllowlistUpdated>;

/** The IP addresses or CIDR ranges that were in the configuration. */
export type AuditLogIpAllowlistDeletedAllowedIpsList = Array<string>;
export const AuditLogIpAllowlistDeletedAllowedIpsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<AuditLogIpAllowlistDeletedAllowedIpsList>;

/** The details for events with this `type`. */
export interface AuditLogIpAllowlistDeleted {
  /** The ID of the IP allowlist configuration. */
  id?: string;
  /** The name of the IP allowlist configuration. */
  name?: string;
  /** The IP addresses or CIDR ranges that were in the configuration. */
  allowed_ips?: AuditLogIpAllowlistDeletedAllowedIpsList;
}
export const AuditLogIpAllowlistDeleted = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    allowed_ips: S.optional(AuditLogIpAllowlistDeletedAllowedIpsList),
  }),
).annotate({
  identifier: "AuditLogIpAllowlistDeleted",
}) as any as S.Schema<AuditLogIpAllowlistDeleted>;

export interface AuditLogIpAllowlistConfigActivatedConfigsItem {
  /** The ID of the IP allowlist configuration. */
  id?: string;
  /** The name of the IP allowlist configuration. */
  name?: string;
}
export const AuditLogIpAllowlistConfigActivatedConfigsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogIpAllowlistConfigActivatedConfigsItem",
}) as any as S.Schema<AuditLogIpAllowlistConfigActivatedConfigsItem>;

/** The configurations that were activated. */
export type AuditLogIpAllowlistConfigActivatedConfigsList =
  Array<AuditLogIpAllowlistConfigActivatedConfigsItem>;
export const AuditLogIpAllowlistConfigActivatedConfigsList = /*@__PURE__*/ S.Array(
  AuditLogIpAllowlistConfigActivatedConfigsItem,
) as any as S.Schema<AuditLogIpAllowlistConfigActivatedConfigsList>;

/** The details for events with this `type`. */
export interface AuditLogIpAllowlistConfigActivated {
  /** The configurations that were activated. */
  configs?: AuditLogIpAllowlistConfigActivatedConfigsList;
}
export const AuditLogIpAllowlistConfigActivated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    configs: S.optional(AuditLogIpAllowlistConfigActivatedConfigsList),
  }),
).annotate({
  identifier: "AuditLogIpAllowlistConfigActivated",
}) as any as S.Schema<AuditLogIpAllowlistConfigActivated>;

export type AuditLogIpAllowlistConfigDeactivatedConfigsItem =
  AuditLogIpAllowlistConfigActivatedConfigsItem;
export const AuditLogIpAllowlistConfigDeactivatedConfigsItem =
  AuditLogIpAllowlistConfigActivatedConfigsItem;

/** The configurations that were deactivated. */
export type AuditLogIpAllowlistConfigDeactivatedConfigsList =
  Array<AuditLogIpAllowlistConfigActivatedConfigsItem>;
export const AuditLogIpAllowlistConfigDeactivatedConfigsList = /*@__PURE__*/ S.Array(
  AuditLogIpAllowlistConfigActivatedConfigsItem,
) as any as S.Schema<AuditLogIpAllowlistConfigDeactivatedConfigsList>;

/** The details for events with this `type`. */
export interface AuditLogIpAllowlistConfigDeactivated {
  /** The configurations that were deactivated. */
  configs?: AuditLogIpAllowlistConfigDeactivatedConfigsList;
}
export const AuditLogIpAllowlistConfigDeactivated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    configs: S.optional(AuditLogIpAllowlistConfigDeactivatedConfigsList),
  }),
).annotate({
  identifier: "AuditLogIpAllowlistConfigDeactivated",
}) as any as S.Schema<AuditLogIpAllowlistConfigDeactivated>;

/** The details for events with this `type`. */
export interface AuditLogLoginFailed {
  /** The error code of the failure. */
  error_code?: string;
  /** The error message of the failure. */
  error_message?: string;
}
export const AuditLogLoginFailed = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    error_code: S.optional(S.String),
    error_message: S.optional(S.String),
  }),
).annotate({ identifier: "AuditLogLoginFailed" }) as any as S.Schema<AuditLogLoginFailed>;

/** The details for events with this `type`. */
export type AuditLogLogoutFailed = AuditLogLoginFailed;
export const AuditLogLogoutFailed = AuditLogLoginFailed;

/** The payload used to update the organization settings. */
export interface AuditLogOrganizationUpdatedChangesRequested {
  /** The organization title. */
  title?: string;
  /** The organization description. */
  description?: string;
  /** The organization name. */
  name?: string;
  /** Visibility of the threads page which shows messages created with the Assistants API and Playground. One of `ANY_ROLE`, `OWNERS`, or `NONE`. */
  threads_ui_visibility?: string;
  /** Visibility of the usage dashboard which shows activity and costs for your organization. One of `ANY_ROLE` or `OWNERS`. */
  usage_dashboard_visibility?: string;
  /** How your organization logs data from supported API calls. One of `disabled`, `enabled_per_call`, `enabled_for_all_projects`, or `enabled_for_selected_projects` */
  api_call_logging?: string;
  /** The list of project ids if api_call_logging is set to `enabled_for_selected_projects` */
  api_call_logging_project_ids?: string;
}
export const AuditLogOrganizationUpdatedChangesRequested = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    title: S.optional(S.String),
    description: S.optional(S.String),
    name: S.optional(S.String),
    threads_ui_visibility: S.optional(S.String),
    usage_dashboard_visibility: S.optional(S.String),
    api_call_logging: S.optional(S.String),
    api_call_logging_project_ids: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogOrganizationUpdatedChangesRequested",
}) as any as S.Schema<AuditLogOrganizationUpdatedChangesRequested>;

/** The details for events with this `type`. */
export interface AuditLogOrganizationUpdated {
  /** The organization ID. */
  id?: string;
  /** The payload used to update the organization settings. */
  changes_requested?: AuditLogOrganizationUpdatedChangesRequested;
}
export const AuditLogOrganizationUpdated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    changes_requested: S.optional(AuditLogOrganizationUpdatedChangesRequested),
  }),
).annotate({
  identifier: "AuditLogOrganizationUpdated",
}) as any as S.Schema<AuditLogOrganizationUpdated>;

/** The payload used to create the project. */
export interface AuditLogProjectCreatedData {
  /** The project name. */
  name?: string;
  /** The title of the project as seen on the dashboard. */
  title?: string;
}
export const AuditLogProjectCreatedData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String),
    title: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogProjectCreatedData",
}) as any as S.Schema<AuditLogProjectCreatedData>;

/** The details for events with this `type`. */
export interface AuditLogProjectCreated {
  /** The project ID. */
  id?: string;
  /** The payload used to create the project. */
  data?: AuditLogProjectCreatedData;
}
export const AuditLogProjectCreated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    data: S.optional(AuditLogProjectCreatedData),
  }),
).annotate({ identifier: "AuditLogProjectCreated" }) as any as S.Schema<AuditLogProjectCreated>;

/** The payload used to update the project. */
export interface AuditLogProjectUpdatedChangesRequested {
  /** The title of the project as seen on the dashboard. */
  title?: string;
}
export const AuditLogProjectUpdatedChangesRequested = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    title: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogProjectUpdatedChangesRequested",
}) as any as S.Schema<AuditLogProjectUpdatedChangesRequested>;

/** The details for events with this `type`. */
export interface AuditLogProjectUpdated {
  /** The project ID. */
  id?: string;
  /** The payload used to update the project. */
  changes_requested?: AuditLogProjectUpdatedChangesRequested;
}
export const AuditLogProjectUpdated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    changes_requested: S.optional(AuditLogProjectUpdatedChangesRequested),
  }),
).annotate({ identifier: "AuditLogProjectUpdated" }) as any as S.Schema<AuditLogProjectUpdated>;

/** The details for events with this `type`. */
export interface AuditLogProjectArchived {
  /** The project ID. */
  id?: string;
}
export const AuditLogProjectArchived = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
  }),
).annotate({ identifier: "AuditLogProjectArchived" }) as any as S.Schema<AuditLogProjectArchived>;

/** The details for events with this `type`. */
export type AuditLogProjectDeleted = AuditLogProjectArchived;
export const AuditLogProjectDeleted = AuditLogProjectArchived;

/** The payload used to update the rate limits. */
export interface AuditLogRateLimitUpdatedChangesRequested {
  /** The maximum requests per minute. */
  max_requests_per_1_minute?: number;
  /** The maximum tokens per minute. */
  max_tokens_per_1_minute?: number;
  /** The maximum images per minute. Only relevant for certain models. */
  max_images_per_1_minute?: number;
  /** The maximum audio megabytes per minute. Only relevant for certain models. */
  max_audio_megabytes_per_1_minute?: number;
  /** The maximum requests per day. Only relevant for certain models. */
  max_requests_per_1_day?: number;
  /** The maximum batch input tokens per day. Only relevant for certain models. */
  batch_1_day_max_input_tokens?: number;
}
export const AuditLogRateLimitUpdatedChangesRequested = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    max_requests_per_1_minute: S.optional(S.Number),
    max_tokens_per_1_minute: S.optional(S.Number),
    max_images_per_1_minute: S.optional(S.Number),
    max_audio_megabytes_per_1_minute: S.optional(S.Number),
    max_requests_per_1_day: S.optional(S.Number),
    batch_1_day_max_input_tokens: S.optional(S.Number),
  }),
).annotate({
  identifier: "AuditLogRateLimitUpdatedChangesRequested",
}) as any as S.Schema<AuditLogRateLimitUpdatedChangesRequested>;

/** The details for events with this `type`. */
export interface AuditLogRateLimitUpdated {
  /** The rate limit ID */
  id?: string;
  /** The payload used to update the rate limits. */
  changes_requested?: AuditLogRateLimitUpdatedChangesRequested;
}
export const AuditLogRateLimitUpdated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    changes_requested: S.optional(AuditLogRateLimitUpdatedChangesRequested),
  }),
).annotate({ identifier: "AuditLogRateLimitUpdated" }) as any as S.Schema<AuditLogRateLimitUpdated>;

/** The details for events with this `type`. */
export interface AuditLogRateLimitDeleted {
  /** The rate limit ID */
  id?: string;
}
export const AuditLogRateLimitDeleted = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
  }),
).annotate({ identifier: "AuditLogRateLimitDeleted" }) as any as S.Schema<AuditLogRateLimitDeleted>;

/** The permissions granted by the role. */
export type AuditLogRoleCreatedPermissionsList = Array<string>;
export const AuditLogRoleCreatedPermissionsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<AuditLogRoleCreatedPermissionsList>;

/** The details for events with this `type`. */
export interface AuditLogRoleCreated {
  /** The role ID. */
  id?: string;
  /** The name of the role. */
  role_name?: string;
  /** The permissions granted by the role. */
  permissions?: AuditLogRoleCreatedPermissionsList;
  /** The type of resource the role belongs to. */
  resource_type?: string;
  /** The resource the role is scoped to. */
  resource_id?: string;
}
export const AuditLogRoleCreated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    role_name: S.optional(S.String),
    permissions: S.optional(AuditLogRoleCreatedPermissionsList),
    resource_type: S.optional(S.String),
    resource_id: S.optional(S.String),
  }),
).annotate({ identifier: "AuditLogRoleCreated" }) as any as S.Schema<AuditLogRoleCreated>;

/** The permissions added to the role. */
export type AuditLogRoleUpdatedChangesRequestedPermissionsAddedList = Array<string>;
export const AuditLogRoleUpdatedChangesRequestedPermissionsAddedList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<AuditLogRoleUpdatedChangesRequestedPermissionsAddedList>;

/** The permissions removed from the role. */
export type AuditLogRoleUpdatedChangesRequestedPermissionsRemovedList = Array<string>;
export const AuditLogRoleUpdatedChangesRequestedPermissionsRemovedList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<AuditLogRoleUpdatedChangesRequestedPermissionsRemovedList>;

/** The payload used to update the role. */
export interface AuditLogRoleUpdatedChangesRequested {
  /** The updated role name, when provided. */
  role_name?: string;
  /** The resource the role is scoped to. */
  resource_id?: string;
  /** The type of resource the role belongs to. */
  resource_type?: string;
  /** The permissions added to the role. */
  permissions_added?: AuditLogRoleUpdatedChangesRequestedPermissionsAddedList;
  /** The permissions removed from the role. */
  permissions_removed?: AuditLogRoleUpdatedChangesRequestedPermissionsRemovedList;
  /** The updated role description, when provided. */
  description?: string;
  /** Additional metadata stored on the role. */
  metadata?: unknown;
}
export const AuditLogRoleUpdatedChangesRequested = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    role_name: S.optional(S.String),
    resource_id: S.optional(S.String),
    resource_type: S.optional(S.String),
    permissions_added: S.optional(AuditLogRoleUpdatedChangesRequestedPermissionsAddedList),
    permissions_removed: S.optional(AuditLogRoleUpdatedChangesRequestedPermissionsRemovedList),
    description: S.optional(S.String),
    metadata: S.optional(S.Unknown),
  }),
).annotate({
  identifier: "AuditLogRoleUpdatedChangesRequested",
}) as any as S.Schema<AuditLogRoleUpdatedChangesRequested>;

/** The details for events with this `type`. */
export interface AuditLogRoleUpdated {
  /** The role ID. */
  id?: string;
  /** The payload used to update the role. */
  changes_requested?: AuditLogRoleUpdatedChangesRequested;
}
export const AuditLogRoleUpdated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    changes_requested: S.optional(AuditLogRoleUpdatedChangesRequested),
  }),
).annotate({ identifier: "AuditLogRoleUpdated" }) as any as S.Schema<AuditLogRoleUpdated>;

/** The details for events with this `type`. */
export interface AuditLogRoleDeleted {
  /** The role ID. */
  id?: string;
}
export const AuditLogRoleDeleted = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
  }),
).annotate({ identifier: "AuditLogRoleDeleted" }) as any as S.Schema<AuditLogRoleDeleted>;

/** The details for events with this `type`. */
export interface AuditLogRoleAssignmentCreated {
  /** The identifier of the role assignment. */
  id?: string;
  /** The principal (user or group) that received the role. */
  principal_id?: string;
  /** The type of principal (user or group) that received the role. */
  principal_type?: string;
  /** The resource the role assignment is scoped to. */
  resource_id?: string;
  /** The type of resource the role assignment is scoped to. */
  resource_type?: string;
}
export const AuditLogRoleAssignmentCreated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    principal_id: S.optional(S.String),
    principal_type: S.optional(S.String),
    resource_id: S.optional(S.String),
    resource_type: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogRoleAssignmentCreated",
}) as any as S.Schema<AuditLogRoleAssignmentCreated>;

/** The details for events with this `type`. */
export interface AuditLogRoleAssignmentDeleted {
  /** The identifier of the role assignment. */
  id?: string;
  /** The principal (user or group) that had the role removed. */
  principal_id?: string;
  /** The type of principal (user or group) that had the role removed. */
  principal_type?: string;
  /** The resource the role assignment was scoped to. */
  resource_id?: string;
  /** The type of resource the role assignment was scoped to. */
  resource_type?: string;
}
export const AuditLogRoleAssignmentDeleted = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    principal_id: S.optional(S.String),
    principal_type: S.optional(S.String),
    resource_id: S.optional(S.String),
    resource_type: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogRoleAssignmentDeleted",
}) as any as S.Schema<AuditLogRoleAssignmentDeleted>;

/** The permissions granted to the role for the resource. */
export type AuditLogRoleBoundToResourcePermissionsList = Array<string>;
export const AuditLogRoleBoundToResourcePermissionsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<AuditLogRoleBoundToResourcePermissionsList>;

/** The connector role mutation path that produced the event. */
export type AuditLogRoleBoundToResourceSource =
  | "role_toggle"
  | "role_connector_update"
  | "role_delete"
  | "workspace_permissions"
  | "connector_publish";
export const AuditLogRoleBoundToResourceSource = S.String;

/** The details for events with this `type`. */
export interface AuditLogRoleBoundToResource {
  /** The ID of the resource the role was bound to. ChatGPT workspace connector resources use `<workspace_id>__<connector_id>`. */
  id?: string;
  /** The ID of the role that was bound to the resource. */
  role_id?: string;
  /** The ID of the resource the role was bound to. */
  resource_id?: string;
  /** The type of resource the role was bound to. */
  resource_type?: string;
  /** The permissions granted to the role for the resource. */
  permissions?: AuditLogRoleBoundToResourcePermissionsList;
  /** The workspace ID for a ChatGPT workspace connector resource. */
  workspace_id?: string;
  /** The connector ID for a ChatGPT workspace connector resource. */
  connector_id?: string;
  /** The connector display name for a ChatGPT workspace connector resource, or the connector ID when the display name could not be resolved. */
  connector_name?: string;
  /** Whether the connector is enabled for the role. */
  enabled?: boolean;
  /** The connector role mutation path that produced the event. */
  source?: AuditLogRoleBoundToResourceSource;
}
export const AuditLogRoleBoundToResource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    role_id: S.optional(S.String),
    resource_id: S.optional(S.String),
    resource_type: S.optional(S.String),
    permissions: S.optional(AuditLogRoleBoundToResourcePermissionsList),
    workspace_id: S.optional(S.String),
    connector_id: S.optional(S.String),
    connector_name: S.optional(S.String),
    enabled: S.optional(S.Boolean),
    source: S.optional(AuditLogRoleBoundToResourceSource),
  }),
).annotate({
  identifier: "AuditLogRoleBoundToResource",
}) as any as S.Schema<AuditLogRoleBoundToResource>;

/** The permissions remaining for the role after the change. */
export type AuditLogRoleUnboundFromResourcePermissionsList = Array<string>;
export const AuditLogRoleUnboundFromResourcePermissionsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<AuditLogRoleUnboundFromResourcePermissionsList>;

/** The connector role mutation path that produced the event. */
export type AuditLogRoleUnboundFromResourceSource =
  | "role_toggle"
  | "role_connector_update"
  | "role_delete"
  | "workspace_permissions"
  | "connector_publish";
export const AuditLogRoleUnboundFromResourceSource = S.String;

/** The details for events with this `type`. */
export interface AuditLogRoleUnboundFromResource {
  /** The ID of the resource the role was unbound from. ChatGPT workspace connector resources use `<workspace_id>__<connector_id>`. */
  id?: string;
  /** The ID of the role that was unbound from the resource. */
  role_id?: string;
  /** The ID of the resource the role was unbound from. */
  resource_id?: string;
  /** The type of resource the role was unbound from. */
  resource_type?: string;
  /** The permissions remaining for the role after the change. */
  permissions?: AuditLogRoleUnboundFromResourcePermissionsList;
  /** The workspace ID for a ChatGPT workspace connector resource. */
  workspace_id?: string;
  /** The connector ID for a ChatGPT workspace connector resource. */
  connector_id?: string;
  /** The connector display name for a ChatGPT workspace connector resource, or the connector ID when the display name could not be resolved. */
  connector_name?: string;
  /** Whether the connector is enabled for the role. */
  enabled?: boolean;
  /** The connector role mutation path that produced the event. */
  source?: AuditLogRoleUnboundFromResourceSource;
}
export const AuditLogRoleUnboundFromResource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    role_id: S.optional(S.String),
    resource_id: S.optional(S.String),
    resource_type: S.optional(S.String),
    permissions: S.optional(AuditLogRoleUnboundFromResourcePermissionsList),
    workspace_id: S.optional(S.String),
    connector_id: S.optional(S.String),
    connector_name: S.optional(S.String),
    enabled: S.optional(S.Boolean),
    source: S.optional(AuditLogRoleUnboundFromResourceSource),
  }),
).annotate({
  identifier: "AuditLogRoleUnboundFromResource",
}) as any as S.Schema<AuditLogRoleUnboundFromResource>;

/** The payload used to create the service account. */
export interface AuditLogServiceAccountCreatedData {
  /** The role of the service account. Is either `owner` or `member`. */
  role?: string;
}
export const AuditLogServiceAccountCreatedData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    role: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogServiceAccountCreatedData",
}) as any as S.Schema<AuditLogServiceAccountCreatedData>;

/** The details for events with this `type`. */
export interface AuditLogServiceAccountCreated {
  /** The service account ID. */
  id?: string;
  /** The payload used to create the service account. */
  data?: AuditLogServiceAccountCreatedData;
}
export const AuditLogServiceAccountCreated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    data: S.optional(AuditLogServiceAccountCreatedData),
  }),
).annotate({
  identifier: "AuditLogServiceAccountCreated",
}) as any as S.Schema<AuditLogServiceAccountCreated>;

/** The payload used to updated the service account. */
export type AuditLogServiceAccountUpdatedChangesRequested = AuditLogServiceAccountCreatedData;
export const AuditLogServiceAccountUpdatedChangesRequested = AuditLogServiceAccountCreatedData;

/** The details for events with this `type`. */
export interface AuditLogServiceAccountUpdated {
  /** The service account ID. */
  id?: string;
  /** The payload used to updated the service account. */
  changes_requested?: AuditLogServiceAccountCreatedData;
}
export const AuditLogServiceAccountUpdated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    changes_requested: S.optional(AuditLogServiceAccountCreatedData),
  }),
).annotate({
  identifier: "AuditLogServiceAccountUpdated",
}) as any as S.Schema<AuditLogServiceAccountUpdated>;

/** The details for events with this `type`. */
export interface AuditLogServiceAccountDeleted {
  /** The service account ID. */
  id?: string;
}
export const AuditLogServiceAccountDeleted = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogServiceAccountDeleted",
}) as any as S.Schema<AuditLogServiceAccountDeleted>;

/** The details for events with this `type`. */
export interface AuditLogWorkloadIdentityProviderCreated {
  /** The workload identity provider ID. */
  id?: string;
  /** The payload used to create the workload identity provider. */
  data?: unknown;
}
export const AuditLogWorkloadIdentityProviderCreated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    data: S.optional(S.Unknown),
  }),
).annotate({
  identifier: "AuditLogWorkloadIdentityProviderCreated",
}) as any as S.Schema<AuditLogWorkloadIdentityProviderCreated>;

/** The details for events with this `type`. */
export interface AuditLogWorkloadIdentityProviderUpdated {
  /** The workload identity provider ID. */
  id?: string;
  /** The payload used to update the workload identity provider. */
  changes_requested?: unknown;
}
export const AuditLogWorkloadIdentityProviderUpdated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    changes_requested: S.optional(S.Unknown),
  }),
).annotate({
  identifier: "AuditLogWorkloadIdentityProviderUpdated",
}) as any as S.Schema<AuditLogWorkloadIdentityProviderUpdated>;

/** The details for events with this `type`. */
export interface AuditLogWorkloadIdentityProviderDeleted {
  /** The workload identity provider ID. */
  id?: string;
  /** The workload identity provider name. */
  name?: string;
}
export const AuditLogWorkloadIdentityProviderDeleted = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogWorkloadIdentityProviderDeleted",
}) as any as S.Schema<AuditLogWorkloadIdentityProviderDeleted>;

/** The details for events with this `type`. */
export interface AuditLogWorkloadIdentityProviderMappingCreated {
  /** The workload identity provider mapping ID. */
  id?: string;
  /** The workload identity provider ID. */
  identity_provider_id?: string;
  /** The payload used to create the workload identity provider mapping. */
  data?: unknown;
}
export const AuditLogWorkloadIdentityProviderMappingCreated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    identity_provider_id: S.optional(S.String),
    data: S.optional(S.Unknown),
  }),
).annotate({
  identifier: "AuditLogWorkloadIdentityProviderMappingCreated",
}) as any as S.Schema<AuditLogWorkloadIdentityProviderMappingCreated>;

/** The details for events with this `type`. */
export interface AuditLogWorkloadIdentityProviderMappingUpdated {
  /** The workload identity provider mapping ID. */
  id?: string;
  /** The workload identity provider ID. */
  identity_provider_id?: string;
  /** The payload used to update the workload identity provider mapping. */
  changes_requested?: unknown;
}
export const AuditLogWorkloadIdentityProviderMappingUpdated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    identity_provider_id: S.optional(S.String),
    changes_requested: S.optional(S.Unknown),
  }),
).annotate({
  identifier: "AuditLogWorkloadIdentityProviderMappingUpdated",
}) as any as S.Schema<AuditLogWorkloadIdentityProviderMappingUpdated>;

/** The details for events with this `type`. */
export interface AuditLogWorkloadIdentityProviderMappingDeleted {
  /** The workload identity provider mapping ID. */
  id?: string;
  /** The workload identity provider ID. */
  identity_provider_id?: string;
  /** The project ID. */
  project_id?: string;
  /** The mapped service account ID. */
  service_account_id?: string;
}
export const AuditLogWorkloadIdentityProviderMappingDeleted = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    identity_provider_id: S.optional(S.String),
    project_id: S.optional(S.String),
    service_account_id: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogWorkloadIdentityProviderMappingDeleted",
}) as any as S.Schema<AuditLogWorkloadIdentityProviderMappingDeleted>;

/** The payload used to add the user to the project. */
export interface AuditLogUserAddedData {
  /** The role of the user. Is either `owner` or `member`. */
  role?: string;
}
export const AuditLogUserAddedData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    role: S.optional(S.String),
  }),
).annotate({ identifier: "AuditLogUserAddedData" }) as any as S.Schema<AuditLogUserAddedData>;

/** The details for events with this `type`. */
export interface AuditLogUserAdded {
  /** The user ID. */
  id?: string;
  /** The payload used to add the user to the project. */
  data?: AuditLogUserAddedData;
}
export const AuditLogUserAdded = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    data: S.optional(AuditLogUserAddedData),
  }),
).annotate({ identifier: "AuditLogUserAdded" }) as any as S.Schema<AuditLogUserAdded>;

/** The payload used to update the user. */
export type AuditLogUserUpdatedChangesRequested = AuditLogUserAddedData;
export const AuditLogUserUpdatedChangesRequested = AuditLogUserAddedData;

/** The details for events with this `type`. */
export interface AuditLogUserUpdated {
  /** The project ID. */
  id?: string;
  /** The payload used to update the user. */
  changes_requested?: AuditLogUserAddedData;
}
export const AuditLogUserUpdated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    changes_requested: S.optional(AuditLogUserAddedData),
  }),
).annotate({ identifier: "AuditLogUserUpdated" }) as any as S.Schema<AuditLogUserUpdated>;

/** The details for events with this `type`. */
export interface AuditLogUserDeleted {
  /** The user ID. */
  id?: string;
}
export const AuditLogUserDeleted = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
  }),
).annotate({ identifier: "AuditLogUserDeleted" }) as any as S.Schema<AuditLogUserDeleted>;

/** The details for events with this `type`. */
export interface AuditLogCertificateCreated {
  /** The certificate ID. */
  id?: string;
  /** The name of the certificate. */
  name?: string;
}
export const AuditLogCertificateCreated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogCertificateCreated",
}) as any as S.Schema<AuditLogCertificateCreated>;

/** The details for events with this `type`. */
export type AuditLogCertificateUpdated = AuditLogCertificateCreated;
export const AuditLogCertificateUpdated = AuditLogCertificateCreated;

/** The details for events with this `type`. */
export interface AuditLogCertificateDeleted {
  /** The certificate ID. */
  id?: string;
  /** The name of the certificate. */
  name?: string;
  /** The certificate content in PEM format. */
  certificate?: string;
}
export const AuditLogCertificateDeleted = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    certificate: S.optional(S.String),
  }),
).annotate({
  identifier: "AuditLogCertificateDeleted",
}) as any as S.Schema<AuditLogCertificateDeleted>;

export type AuditLogCertificatesActivatedCertificatesItem = AuditLogCertificateCreated;
export const AuditLogCertificatesActivatedCertificatesItem = AuditLogCertificateCreated;

export type AuditLogCertificatesActivatedCertificatesList = Array<AuditLogCertificateCreated>;
export const AuditLogCertificatesActivatedCertificatesList = /*@__PURE__*/ S.Array(
  AuditLogCertificateCreated,
) as any as S.Schema<AuditLogCertificatesActivatedCertificatesList>;

/** The details for events with this `type`. */
export interface AuditLogCertificatesActivated {
  certificates?: AuditLogCertificatesActivatedCertificatesList;
}
export const AuditLogCertificatesActivated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    certificates: S.optional(AuditLogCertificatesActivatedCertificatesList),
  }),
).annotate({
  identifier: "AuditLogCertificatesActivated",
}) as any as S.Schema<AuditLogCertificatesActivated>;

export type AuditLogCertificatesDeactivatedCertificatesItem = AuditLogCertificateCreated;
export const AuditLogCertificatesDeactivatedCertificatesItem = AuditLogCertificateCreated;

export type AuditLogCertificatesDeactivatedCertificatesList = Array<AuditLogCertificateCreated>;
export const AuditLogCertificatesDeactivatedCertificatesList = /*@__PURE__*/ S.Array(
  AuditLogCertificateCreated,
) as any as S.Schema<AuditLogCertificatesDeactivatedCertificatesList>;

/** The details for events with this `type`. */
export interface AuditLogCertificatesDeactivated {
  certificates?: AuditLogCertificatesDeactivatedCertificatesList;
}
export const AuditLogCertificatesDeactivated = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    certificates: S.optional(AuditLogCertificatesDeactivatedCertificatesList),
  }),
).annotate({
  identifier: "AuditLogCertificatesDeactivated",
}) as any as S.Schema<AuditLogCertificatesDeactivated>;

/** A log of a user action or configuration change within this organization. */
export interface AuditLog {
  /** The ID of this log. */
  id: string;
  type: AuditLogEventType;
  /** The Unix timestamp (in seconds) of the event. */
  effective_at: number;
  /** The project that the action was scoped to. Absent for actions not scoped to projects. Note that any admin actions taken via Admin API keys are associated with the default project. */
  project?: AuditLogProject;
  actor?: AuditLogActor | null;
  /** The details for events with this `type`. */
  api_key_created?: AuditLogApiKeyCreated;
  /** The details for events with this `type`. */
  api_key_updated?: AuditLogApiKeyUpdated;
  /** The details for events with this `type`. */
  api_key_deleted?: AuditLogApiKeyDeleted;
  /** The project and fine-tuned model checkpoint that the checkpoint permission was created for. */
  checkpoint_permission_created?: AuditLogCheckpointPermissionCreated;
  /** The details for events with this `type`. */
  checkpoint_permission_deleted?: AuditLogCheckpointPermissionDeleted;
  /** The details for events with this `type`. */
  external_key_registered?: AuditLogExternalKeyRegistered;
  /** The details for events with this `type`. */
  external_key_removed?: AuditLogExternalKeyRemoved;
  /** The details for events with this `type`. */
  external_storage_registered?: AuditLogExternalStorageRegistered;
  /** The details for events with this `type`. */
  external_storage_removed?: AuditLogExternalStorageRemoved;
  /** The details for events with this `type`. */
  group_created?: AuditLogGroupCreated;
  /** The details for events with this `type`. */
  group_updated?: AuditLogGroupUpdated;
  /** The details for events with this `type`. */
  group_deleted?: AuditLogGroupDeleted;
  /** The details for events with this `type`. */
  scim_enabled?: AuditLogScimEnabled;
  /** The details for events with this `type`. */
  scim_disabled?: AuditLogScimDisabled;
  /** The details for events with this `type`. */
  invite_sent?: AuditLogInviteSent;
  /** The details for events with this `type`. */
  invite_accepted?: AuditLogInviteAccepted;
  /** The details for events with this `type`. */
  invite_deleted?: AuditLogInviteAccepted;
  /** The details for events with this `type`. */
  ip_allowlist_created?: AuditLogIpAllowlistCreated;
  /** The details for events with this `type`. */
  ip_allowlist_updated?: AuditLogIpAllowlistUpdated;
  /** The details for events with this `type`. */
  ip_allowlist_deleted?: AuditLogIpAllowlistDeleted;
  /** The details for events with this `type`. */
  ip_allowlist_config_activated?: AuditLogIpAllowlistConfigActivated;
  /** The details for events with this `type`. */
  ip_allowlist_config_deactivated?: AuditLogIpAllowlistConfigDeactivated;
  /** This event has no additional fields beyond the standard audit log attributes. */
  login_succeeded?: unknown;
  /** The details for events with this `type`. */
  login_failed?: AuditLogLoginFailed;
  /** This event has no additional fields beyond the standard audit log attributes. */
  logout_succeeded?: unknown;
  /** The details for events with this `type`. */
  logout_failed?: AuditLogLoginFailed;
  /** The details for events with this `type`. */
  organization_updated?: AuditLogOrganizationUpdated;
  /** The details for events with this `type`. */
  project_created?: AuditLogProjectCreated;
  /** The details for events with this `type`. */
  project_updated?: AuditLogProjectUpdated;
  /** The details for events with this `type`. */
  project_archived?: AuditLogProjectArchived;
  /** The details for events with this `type`. */
  project_deleted?: AuditLogProjectArchived;
  /** The details for events with this `type`. */
  rate_limit_updated?: AuditLogRateLimitUpdated;
  /** The details for events with this `type`. */
  rate_limit_deleted?: AuditLogRateLimitDeleted;
  /** The details for events with this `type`. */
  role_created?: AuditLogRoleCreated;
  /** The details for events with this `type`. */
  role_updated?: AuditLogRoleUpdated;
  /** The details for events with this `type`. */
  role_deleted?: AuditLogRoleDeleted;
  /** The details for events with this `type`. */
  role_assignment_created?: AuditLogRoleAssignmentCreated;
  /** The details for events with this `type`. */
  role_assignment_deleted?: AuditLogRoleAssignmentDeleted;
  /** The details for events with this `type`. */
  role_bound_to_resource?: AuditLogRoleBoundToResource;
  /** The details for events with this `type`. */
  role_unbound_from_resource?: AuditLogRoleUnboundFromResource;
  /** The details for events with this `type`. */
  service_account_created?: AuditLogServiceAccountCreated;
  /** The details for events with this `type`. */
  service_account_updated?: AuditLogServiceAccountUpdated;
  /** The details for events with this `type`. */
  service_account_deleted?: AuditLogServiceAccountDeleted;
  /** The details for events with this `type`. */
  workload_identity_provider_created?: AuditLogWorkloadIdentityProviderCreated;
  /** The details for events with this `type`. */
  workload_identity_provider_updated?: AuditLogWorkloadIdentityProviderUpdated;
  /** The details for events with this `type`. */
  workload_identity_provider_deleted?: AuditLogWorkloadIdentityProviderDeleted;
  /** The details for events with this `type`. */
  workload_identity_provider_mapping_created?: AuditLogWorkloadIdentityProviderMappingCreated;
  /** The details for events with this `type`. */
  workload_identity_provider_mapping_updated?: AuditLogWorkloadIdentityProviderMappingUpdated;
  /** The details for events with this `type`. */
  workload_identity_provider_mapping_deleted?: AuditLogWorkloadIdentityProviderMappingDeleted;
  /** The details for events with this `type`. */
  user_added?: AuditLogUserAdded;
  /** The details for events with this `type`. */
  user_updated?: AuditLogUserUpdated;
  /** The details for events with this `type`. */
  user_deleted?: AuditLogUserDeleted;
  /** The details for events with this `type`. */
  certificate_created?: AuditLogCertificateCreated;
  /** The details for events with this `type`. */
  certificate_updated?: AuditLogCertificateCreated;
  /** The details for events with this `type`. */
  certificate_deleted?: AuditLogCertificateDeleted;
  /** The details for events with this `type`. */
  certificates_activated?: AuditLogCertificatesActivated;
  /** The details for events with this `type`. */
  certificates_deactivated?: AuditLogCertificatesDeactivated;
}
export const AuditLog = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    type: AuditLogEventType,
    effective_at: S.Number,
    project: S.optional(AuditLogProject),
    actor: S.optional(S.NullOr(AuditLogActor)),
    api_key_created: S.optional(AuditLogApiKeyCreated.pipe(T.Body("api_key.created"))),
    api_key_updated: S.optional(AuditLogApiKeyUpdated.pipe(T.Body("api_key.updated"))),
    api_key_deleted: S.optional(AuditLogApiKeyDeleted.pipe(T.Body("api_key.deleted"))),
    checkpoint_permission_created: S.optional(
      AuditLogCheckpointPermissionCreated.pipe(T.Body("checkpoint.permission.created")),
    ),
    checkpoint_permission_deleted: S.optional(
      AuditLogCheckpointPermissionDeleted.pipe(T.Body("checkpoint.permission.deleted")),
    ),
    external_key_registered: S.optional(
      AuditLogExternalKeyRegistered.pipe(T.Body("external_key.registered")),
    ),
    external_key_removed: S.optional(
      AuditLogExternalKeyRemoved.pipe(T.Body("external_key.removed")),
    ),
    external_storage_registered: S.optional(
      AuditLogExternalStorageRegistered.pipe(T.Body("external_storage.registered")),
    ),
    external_storage_removed: S.optional(
      AuditLogExternalStorageRemoved.pipe(T.Body("external_storage.removed")),
    ),
    group_created: S.optional(AuditLogGroupCreated.pipe(T.Body("group.created"))),
    group_updated: S.optional(AuditLogGroupUpdated.pipe(T.Body("group.updated"))),
    group_deleted: S.optional(AuditLogGroupDeleted.pipe(T.Body("group.deleted"))),
    scim_enabled: S.optional(AuditLogScimEnabled.pipe(T.Body("scim.enabled"))),
    scim_disabled: S.optional(AuditLogScimDisabled.pipe(T.Body("scim.disabled"))),
    invite_sent: S.optional(AuditLogInviteSent.pipe(T.Body("invite.sent"))),
    invite_accepted: S.optional(AuditLogInviteAccepted.pipe(T.Body("invite.accepted"))),
    invite_deleted: S.optional(AuditLogInviteAccepted.pipe(T.Body("invite.deleted"))),
    ip_allowlist_created: S.optional(
      AuditLogIpAllowlistCreated.pipe(T.Body("ip_allowlist.created")),
    ),
    ip_allowlist_updated: S.optional(
      AuditLogIpAllowlistUpdated.pipe(T.Body("ip_allowlist.updated")),
    ),
    ip_allowlist_deleted: S.optional(
      AuditLogIpAllowlistDeleted.pipe(T.Body("ip_allowlist.deleted")),
    ),
    ip_allowlist_config_activated: S.optional(
      AuditLogIpAllowlistConfigActivated.pipe(T.Body("ip_allowlist.config.activated")),
    ),
    ip_allowlist_config_deactivated: S.optional(
      AuditLogIpAllowlistConfigDeactivated.pipe(T.Body("ip_allowlist.config.deactivated")),
    ),
    login_succeeded: S.optional(S.Unknown.pipe(T.Body("login.succeeded"))),
    login_failed: S.optional(AuditLogLoginFailed.pipe(T.Body("login.failed"))),
    logout_succeeded: S.optional(S.Unknown.pipe(T.Body("logout.succeeded"))),
    logout_failed: S.optional(AuditLogLoginFailed.pipe(T.Body("logout.failed"))),
    organization_updated: S.optional(
      AuditLogOrganizationUpdated.pipe(T.Body("organization.updated")),
    ),
    project_created: S.optional(AuditLogProjectCreated.pipe(T.Body("project.created"))),
    project_updated: S.optional(AuditLogProjectUpdated.pipe(T.Body("project.updated"))),
    project_archived: S.optional(AuditLogProjectArchived.pipe(T.Body("project.archived"))),
    project_deleted: S.optional(AuditLogProjectArchived.pipe(T.Body("project.deleted"))),
    rate_limit_updated: S.optional(AuditLogRateLimitUpdated.pipe(T.Body("rate_limit.updated"))),
    rate_limit_deleted: S.optional(AuditLogRateLimitDeleted.pipe(T.Body("rate_limit.deleted"))),
    role_created: S.optional(AuditLogRoleCreated.pipe(T.Body("role.created"))),
    role_updated: S.optional(AuditLogRoleUpdated.pipe(T.Body("role.updated"))),
    role_deleted: S.optional(AuditLogRoleDeleted.pipe(T.Body("role.deleted"))),
    role_assignment_created: S.optional(
      AuditLogRoleAssignmentCreated.pipe(T.Body("role.assignment.created")),
    ),
    role_assignment_deleted: S.optional(
      AuditLogRoleAssignmentDeleted.pipe(T.Body("role.assignment.deleted")),
    ),
    role_bound_to_resource: S.optional(
      AuditLogRoleBoundToResource.pipe(T.Body("role.bound_to_resource")),
    ),
    role_unbound_from_resource: S.optional(
      AuditLogRoleUnboundFromResource.pipe(T.Body("role.unbound_from_resource")),
    ),
    service_account_created: S.optional(
      AuditLogServiceAccountCreated.pipe(T.Body("service_account.created")),
    ),
    service_account_updated: S.optional(
      AuditLogServiceAccountUpdated.pipe(T.Body("service_account.updated")),
    ),
    service_account_deleted: S.optional(
      AuditLogServiceAccountDeleted.pipe(T.Body("service_account.deleted")),
    ),
    workload_identity_provider_created: S.optional(
      AuditLogWorkloadIdentityProviderCreated.pipe(T.Body("workload_identity_provider.created")),
    ),
    workload_identity_provider_updated: S.optional(
      AuditLogWorkloadIdentityProviderUpdated.pipe(T.Body("workload_identity_provider.updated")),
    ),
    workload_identity_provider_deleted: S.optional(
      AuditLogWorkloadIdentityProviderDeleted.pipe(T.Body("workload_identity_provider.deleted")),
    ),
    workload_identity_provider_mapping_created: S.optional(
      AuditLogWorkloadIdentityProviderMappingCreated.pipe(
        T.Body("workload_identity_provider_mapping.created"),
      ),
    ),
    workload_identity_provider_mapping_updated: S.optional(
      AuditLogWorkloadIdentityProviderMappingUpdated.pipe(
        T.Body("workload_identity_provider_mapping.updated"),
      ),
    ),
    workload_identity_provider_mapping_deleted: S.optional(
      AuditLogWorkloadIdentityProviderMappingDeleted.pipe(
        T.Body("workload_identity_provider_mapping.deleted"),
      ),
    ),
    user_added: S.optional(AuditLogUserAdded.pipe(T.Body("user.added"))),
    user_updated: S.optional(AuditLogUserUpdated.pipe(T.Body("user.updated"))),
    user_deleted: S.optional(AuditLogUserDeleted.pipe(T.Body("user.deleted"))),
    certificate_created: S.optional(AuditLogCertificateCreated.pipe(T.Body("certificate.created"))),
    certificate_updated: S.optional(AuditLogCertificateCreated.pipe(T.Body("certificate.updated"))),
    certificate_deleted: S.optional(AuditLogCertificateDeleted.pipe(T.Body("certificate.deleted"))),
    certificates_activated: S.optional(
      AuditLogCertificatesActivated.pipe(T.Body("certificates.activated")),
    ),
    certificates_deactivated: S.optional(
      AuditLogCertificatesDeactivated.pipe(T.Body("certificates.deactivated")),
    ),
  }),
).annotate({ identifier: "AuditLog" }) as any as S.Schema<AuditLog>;

export type ListAuditLogsResponseDataList = Array<AuditLog>;
export const ListAuditLogsResponseDataList = /*@__PURE__*/ S.Array(
  AuditLog,
) as any as S.Schema<ListAuditLogsResponseDataList>;

export interface ListAuditLogsResponse {
  object: ListAuditLogsResponseObject;
  data: ListAuditLogsResponseDataList;
  first_id?: string | null;
  last_id?: string | null;
  has_more: boolean;
}
export const ListAuditLogsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    object: ListAuditLogsResponseObject,
    data: ListAuditLogsResponseDataList,
    first_id: S.optional(S.NullOr(S.String)),
    last_id: S.optional(S.NullOr(S.String)),
    has_more: S.Boolean,
  }),
).annotate({ identifier: "ListAuditLogsResponse" }) as any as S.Schema<ListAuditLogsResponse>;

export type ListAuditLogsError = BadRequest | NotFound | OpenAIOpError;
/** List audit logs List user actions and configuration changes within this organization. */
export const listAuditLogs: API.PaginatedOperationMethod<
  ListAuditLogsRequest,
  ListAuditLogsResponse,
  ListAuditLogsError,
  OpenAIOpContext,
  AuditLog
> = /*@__PURE__*/ API.makePaginated(
  () => ({
    input: ListAuditLogsRequest,
    output: ListAuditLogsResponse,
    errors: [BadRequest, NotFound, UnknownOpenAIError],
    protocol: OpenAIProtocol,
    retry: Retry.Retry,
    pagination: {
      mode: "cursor",
      inputToken: "after",
      outputToken: "last_id",
      items: "data",
      pageSize: "limit",
    } as const,
  }),
  paginateAfter,
) as any;
