import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-openai). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownOpenAIError } from "../errors.ts";
import { OpenAIProtocol, type OpenAIOpError, type OpenAIOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { OpenAIOpError, OpenAIOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class ContextLengthExceeded
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<ContextLengthExceeded>()("ContextLengthExceeded", {
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400, body: { "/error/code": "context_length_exceeded" } }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

/** The array of strings that will be turned into an embedding. */
export type CreateEmbeddingRequestInputArrayList = Array<string>;
export const CreateEmbeddingRequestInputArrayList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreateEmbeddingRequestInputArrayList>;

/** The array of integers that will be turned into an embedding. */
export type CreateEmbeddingRequestInputArrayList2 = Array<number>;
export const CreateEmbeddingRequestInputArrayList2 = /*@__PURE__*/ S.Array(
  S.Number,
) as any as S.Schema<CreateEmbeddingRequestInputArrayList2>;

export type CreateEmbeddingRequestInputArrayItemList = Array<number>;
export const CreateEmbeddingRequestInputArrayItemList = /*@__PURE__*/ S.Array(
  S.Number,
) as any as S.Schema<CreateEmbeddingRequestInputArrayItemList>;

/** The array of arrays containing integers that will be turned into an embedding. */
export type CreateEmbeddingRequestInputArrayList3 = Array<CreateEmbeddingRequestInputArrayItemList>;
export const CreateEmbeddingRequestInputArrayList3 = /*@__PURE__*/ S.Array(
  CreateEmbeddingRequestInputArrayItemList,
) as any as S.Schema<CreateEmbeddingRequestInputArrayList3>;

/** Input text to embed, encoded as a string or array of tokens. To embed multiple inputs in a single request, pass an array of strings or array of token arrays. The input must not exceed the max input tokens for the model (8192 tokens for all embedding models), cannot be an empty string, and any array must be 2048 dimensions or less. [Example Python code](https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken) for counting tokens. In addition to the per-input token limit, all embedding models enforce a maximum of 300,000 tokens summed across all inputs in a single request. */
export type CreateEmbeddingRequestInput =
  | string
  | CreateEmbeddingRequestInputArrayList
  | CreateEmbeddingRequestInputArrayList2
  | CreateEmbeddingRequestInputArrayList3;
export const CreateEmbeddingRequestInput =
  S.Unknown as any as S.Schema<CreateEmbeddingRequestInput>;

export type CreateEmbeddingRequestModelCase1 =
  | "text-embedding-ada-002"
  | "text-embedding-3-small"
  | "text-embedding-3-large";
export const CreateEmbeddingRequestModelCase1 = S.String;

/** ID of the model to use. You can use the [List models](https://developers.openai.com/api/reference/resources/models/methods/list) API to see all of your available models, or see our [Model overview](https://developers.openai.com/api/docs/models) for descriptions of them. */
export type CreateEmbeddingRequestModel = string | CreateEmbeddingRequestModelCase1;
export const CreateEmbeddingRequestModel =
  S.Unknown as any as S.Schema<CreateEmbeddingRequestModel>;

/** The format to return the embeddings in. Can be either `float` or [`base64`](https://pypi.org/project/pybase64/). */
export type CreateEmbeddingRequestEncodingFormat = "float" | "base64";
export const CreateEmbeddingRequestEncodingFormat = S.String;

export interface CreateEmbeddingRequest {
  /** Input text to embed, encoded as a string or array of tokens. To embed multiple inputs in a single request, pass an array of strings or array of token arrays. The input must not exceed the max input tokens for the model (8192 tokens for all embedding models), cannot be an empty string, and any array must be 2048 dimensions or less. [Example Python code](https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken) for counting tokens. In addition to the per-input token limit, all embedding models enforce a maximum of 300,000 tokens summed across all inputs in a single request. */
  input: CreateEmbeddingRequestInput;
  /** ID of the model to use. You can use the [List models](https://developers.openai.com/api/reference/resources/models/methods/list) API to see all of your available models, or see our [Model overview](https://developers.openai.com/api/docs/models) for descriptions of them. */
  model: CreateEmbeddingRequestModel;
  /** The format to return the embeddings in. Can be either `float` or [`base64`](https://pypi.org/project/pybase64/). */
  encoding_format?: CreateEmbeddingRequestEncodingFormat | (string & {});
  /** The number of dimensions the resulting output embeddings should have. Only supported in `text-embedding-3` and later models. */
  dimensions?: number;
  /** A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](https://developers.openai.com/api/docs/guides/safety-best-practices#implement-safety-identifiers). */
  user?: string;
}
export const CreateEmbeddingRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    input: CreateEmbeddingRequestInput,
    model: CreateEmbeddingRequestModel,
    encoding_format: S.optional(CreateEmbeddingRequestEncodingFormat),
    dimensions: S.optional(S.Number),
    user: S.optional(S.String),
  }).pipe(T.Http({ method: "POST", uri: "/embeddings", code: 200 })),
).annotate({ identifier: "CreateEmbeddingRequest" }) as any as S.Schema<CreateEmbeddingRequest>;

export type EmbeddingEmbeddingCase0List = Array<number>;
export const EmbeddingEmbeddingCase0List = /*@__PURE__*/ S.Array(
  S.Number,
) as any as S.Schema<EmbeddingEmbeddingCase0List>;

/** The embedding vector, returned as a list of floats when `encoding_format` is `float` (the default), or as a base64-encoded string when `encoding_format` is `base64`. The length of the vector depends on the model as listed in the [embedding guide](https://developers.openai.com/api/docs/guides/embeddings). */
export type EmbeddingEmbedding = EmbeddingEmbeddingCase0List | string;
export const EmbeddingEmbedding = S.Unknown as any as S.Schema<EmbeddingEmbedding>;

/** The object type, which is always "embedding". */
export type EmbeddingObject = "embedding";
export const EmbeddingObject = S.String;

/** Represents an embedding vector returned by embedding endpoint. */
export interface Embedding {
  /** The index of the embedding in the list of embeddings. */
  index: number;
  /** The embedding vector, returned as a list of floats when `encoding_format` is `float` (the default), or as a base64-encoded string when `encoding_format` is `base64`. The length of the vector depends on the model as listed in the [embedding guide](https://developers.openai.com/api/docs/guides/embeddings). */
  embedding: EmbeddingEmbedding;
  /** The object type, which is always "embedding". */
  object: EmbeddingObject;
}
export const Embedding = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    index: S.Number,
    embedding: EmbeddingEmbedding,
    object: EmbeddingObject,
  }),
).annotate({ identifier: "Embedding" }) as any as S.Schema<Embedding>;

/** The list of embeddings generated by the model. */
export type CreateEmbeddingResponseDataList = Array<Embedding>;
export const CreateEmbeddingResponseDataList = /*@__PURE__*/ S.Array(
  Embedding,
) as any as S.Schema<CreateEmbeddingResponseDataList>;

/** The object type, which is always "list". */
export type CreateEmbeddingResponseObject = "list";
export const CreateEmbeddingResponseObject = S.String;

/** The usage information for the request. */
export interface CreateEmbeddingResponseUsage {
  /** The number of tokens used by the prompt. */
  prompt_tokens: number;
  /** The total number of tokens used by the request. */
  total_tokens: number;
}
export const CreateEmbeddingResponseUsage = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    prompt_tokens: S.Number,
    total_tokens: S.Number,
  }),
).annotate({
  identifier: "CreateEmbeddingResponseUsage",
}) as any as S.Schema<CreateEmbeddingResponseUsage>;

export interface CreateEmbeddingResponse {
  /** The list of embeddings generated by the model. */
  data: CreateEmbeddingResponseDataList;
  /** The name of the model used to generate the embedding. */
  model: string;
  /** The object type, which is always "list". */
  object: CreateEmbeddingResponseObject;
  /** The usage information for the request. */
  usage: CreateEmbeddingResponseUsage;
}
export const CreateEmbeddingResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: CreateEmbeddingResponseDataList,
    model: S.String,
    object: CreateEmbeddingResponseObject,
    usage: CreateEmbeddingResponseUsage,
  }),
).annotate({ identifier: "CreateEmbeddingResponse" }) as any as S.Schema<CreateEmbeddingResponse>;

export type CreateEmbeddingError = BadRequest | Forbidden | ContextLengthExceeded | OpenAIOpError;
/** Create embeddings Creates an embedding vector representing the input text. */
export const createEmbedding: API.OperationMethod<
  CreateEmbeddingRequest,
  CreateEmbeddingResponse,
  CreateEmbeddingError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateEmbeddingRequest,
  output: CreateEmbeddingResponse,
  errors: [BadRequest, Forbidden, ContextLengthExceeded, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));
