import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-openai). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownOpenAIError } from "../errors.ts";
import { paginateAfter } from "../pagination.ts";
import { OpenAIProtocol, type OpenAIOpError, type OpenAIOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { OpenAIOpError, OpenAIOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

export class UnprocessableEntity
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<UnprocessableEntity>()("UnprocessableEntity", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 422 }],
  ) {}

export interface CreateGroupRequest {
  /** Human readable name for the group. */
  name: string;
}
export const CreateGroupRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String,
  })
    .pipe(T.Http({ method: "POST", uri: "/organization/groups", code: 200 }))
    .pipe(T.AdminAuth()),
).annotate({ identifier: "CreateGroupRequest" }) as any as S.Schema<CreateGroupRequest>;

/** The type of the group. */
export type GroupResponseGroupType = "group" | "tenant_group";
export const GroupResponseGroupType = S.String;

/** Details about an organization group. */
export interface GroupResponse {
  /** Identifier for the group. */
  id: string;
  /** Display name of the group. */
  name: string;
  /** Unix timestamp (in seconds) when the group was created. */
  created_at: number;
  /** Whether the group is managed through SCIM and controlled by your identity provider. */
  is_scim_managed: boolean;
  /** The type of the group. */
  group_type: GroupResponseGroupType;
}
export const GroupResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    name: S.String,
    created_at: S.Number,
    is_scim_managed: S.Boolean,
    group_type: GroupResponseGroupType,
  }),
).annotate({ identifier: "GroupResponse" }) as any as S.Schema<GroupResponse>;

export interface DeleteGroupRequest {
  /** The ID of the group to delete. */
  group_id: string;
}
export const DeleteGroupRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    group_id: S.String.pipe(T.Label()),
  })
    .pipe(T.Http({ method: "DELETE", uri: "/organization/groups/{group_id}", code: 200 }))
    .pipe(T.AdminAuth()),
).annotate({ identifier: "DeleteGroupRequest" }) as any as S.Schema<DeleteGroupRequest>;

/** Always `group.deleted`. */
export type GroupDeletedResourceObject = "group.deleted";
export const GroupDeletedResourceObject = S.String;

/** Confirmation payload returned after deleting a group. */
export interface GroupDeletedResource {
  /** Always `group.deleted`. */
  object: GroupDeletedResourceObject;
  /** Identifier of the deleted group. */
  id: string;
  /** Whether the group was deleted. */
  deleted: boolean;
}
export const GroupDeletedResource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    object: GroupDeletedResourceObject,
    id: S.String,
    deleted: S.Boolean,
  }),
).annotate({ identifier: "GroupDeletedResource" }) as any as S.Schema<GroupDeletedResource>;

export interface GetGroupRequest {
  /** The ID of the group to retrieve. */
  group_id: string;
}
export const GetGroupRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    group_id: S.String.pipe(T.Label()),
  })
    .pipe(T.Http({ method: "GET", uri: "/organization/groups/{group_id}", code: 200 }))
    .pipe(T.AdminAuth()),
).annotate({ identifier: "GetGroupRequest" }) as any as S.Schema<GetGroupRequest>;

export type ListGroupsRequestOrder = "asc" | "desc";
export const ListGroupsRequestOrder = S.String;

export interface ListGroupsRequest {
  /** A limit on the number of groups to be returned. Limit can range between 0 and 1000, and the default is 100. */
  limit?: number;
  /** A cursor for use in pagination. `after` is a group ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with group_abc, your subsequent call can include `after=group_abc` in order to fetch the next page of the list. */
  after?: string;
  /** Specifies the sort order of the returned groups. */
  order?: ListGroupsRequestOrder | (string & {});
}
export const ListGroupsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    limit: S.optional(S.Number.pipe(T.Query())),
    after: S.optional(S.String.pipe(T.Query())),
    order: S.optional(ListGroupsRequestOrder.pipe(T.Query())),
  })
    .pipe(T.Http({ method: "GET", uri: "/organization/groups", code: 200 }))
    .pipe(T.AdminAuth()),
).annotate({ identifier: "ListGroupsRequest" }) as any as S.Schema<ListGroupsRequest>;

/** Always `list`. */
export type GroupListResourceObject = "list";
export const GroupListResourceObject = S.String;

/** Groups returned in the current page. */
export type GroupListResourceDataList = Array<GroupResponse>;
export const GroupListResourceDataList = /*@__PURE__*/ S.Array(
  GroupResponse,
) as any as S.Schema<GroupListResourceDataList>;

/** Paginated list of organization groups. */
export interface GroupListResource {
  /** Always `list`. */
  object: GroupListResourceObject;
  /** Groups returned in the current page. */
  data: GroupListResourceDataList;
  /** Whether additional groups are available when paginating. */
  has_more: boolean;
  /** Cursor to fetch the next page of results, or `null` if there are no more results. */
  next: string | null;
}
export const GroupListResource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    object: GroupListResourceObject,
    data: GroupListResourceDataList,
    has_more: S.Boolean,
    next: S.NullOr(S.String),
  }),
).annotate({ identifier: "GroupListResource" }) as any as S.Schema<GroupListResource>;

export interface UpdateGroupRequest {
  /** The ID of the group to update. */
  group_id: string;
  /** New display name for the group. */
  name: string;
}
export const UpdateGroupRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    group_id: S.String.pipe(T.Label()),
    name: S.String,
  })
    .pipe(T.Http({ method: "POST", uri: "/organization/groups/{group_id}", code: 200 }))
    .pipe(T.AdminAuth()),
).annotate({ identifier: "UpdateGroupRequest" }) as any as S.Schema<UpdateGroupRequest>;

/** Response returned after updating a group. */
export interface GroupResourceWithSuccess {
  /** Identifier for the group. */
  id: string;
  /** Updated display name for the group. */
  name: string;
  /** Unix timestamp (in seconds) when the group was created. */
  created_at: number;
  /** Whether the group is managed through SCIM and controlled by your identity provider. */
  is_scim_managed: boolean;
}
export const GroupResourceWithSuccess = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    name: S.String,
    created_at: S.Number,
    is_scim_managed: S.Boolean,
  }),
).annotate({ identifier: "GroupResourceWithSuccess" }) as any as S.Schema<GroupResourceWithSuccess>;

export type CreateGroupError =
  | BadRequest
  | Forbidden
  | NotFound
  | UnprocessableEntity
  | OpenAIOpError;
/** Create group Creates a new group in the organization. */
export const createGroup: API.OperationMethod<
  CreateGroupRequest,
  GroupResponse,
  CreateGroupError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateGroupRequest,
  output: GroupResponse,
  errors: [BadRequest, Forbidden, NotFound, UnprocessableEntity, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));

export type DeleteGroupError = BadRequest | Forbidden | NotFound | OpenAIOpError;
/** Delete group Deletes a group from the organization. */
export const deleteGroup: API.OperationMethod<
  DeleteGroupRequest,
  GroupDeletedResource,
  DeleteGroupError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteGroupRequest,
  output: GroupDeletedResource,
  errors: [BadRequest, Forbidden, NotFound, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));

export type GetGroupError = BadRequest | Forbidden | NotFound | OpenAIOpError;
/** Retrieve group Retrieves a group. */
export const getGroup: API.OperationMethod<
  GetGroupRequest,
  GroupResponse,
  GetGroupError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetGroupRequest,
  output: GroupResponse,
  errors: [BadRequest, Forbidden, NotFound, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));

export type ListGroupsError = BadRequest | Forbidden | NotFound | OpenAIOpError;
/** List groups Lists all groups in the organization. */
export const listGroups: API.PaginatedOperationMethod<
  ListGroupsRequest,
  GroupListResource,
  ListGroupsError,
  OpenAIOpContext,
  GroupResponse
> = /*@__PURE__*/ API.makePaginated(
  () => ({
    input: ListGroupsRequest,
    output: GroupListResource,
    errors: [BadRequest, Forbidden, NotFound, UnknownOpenAIError],
    protocol: OpenAIProtocol,
    retry: Retry.Retry,
    pagination: {
      mode: "cursor",
      inputToken: "after",
      outputToken: "next",
      items: "data",
      pageSize: "limit",
    } as const,
  }),
  paginateAfter,
) as any;

export type UpdateGroupError = BadRequest | Forbidden | NotFound | OpenAIOpError;
/** Update group Updates a group's information. */
export const updateGroup: API.OperationMethod<
  UpdateGroupRequest,
  GroupResourceWithSuccess,
  UpdateGroupError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateGroupRequest,
  output: GroupResourceWithSuccess,
  errors: [BadRequest, Forbidden, NotFound, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));
