import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-openai). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownOpenAIError } from "../errors.ts";
import { OpenAIProtocol, type OpenAIOpError, type OpenAIOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { OpenAIOpError, OpenAIOpContext };

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

export interface DeleteModelRequest {
  /** The model to delete */
  model: string;
}
export const DeleteModelRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    model: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "DELETE", uri: "/models/{model}", code: 200 })),
).annotate({ identifier: "DeleteModelRequest" }) as any as S.Schema<DeleteModelRequest>;

export interface DeleteModelResponse {
  id: string;
  deleted: boolean;
  object: string;
}
export const DeleteModelResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    deleted: S.Boolean,
    object: S.String,
  }),
).annotate({ identifier: "DeleteModelResponse" }) as any as S.Schema<DeleteModelResponse>;

export interface GetModelRequest {
  /** The ID of the model to use for this request */
  model: string;
}
export const GetModelRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    model: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/models/{model}", code: 200 })),
).annotate({ identifier: "GetModelRequest" }) as any as S.Schema<GetModelRequest>;

/** The object type, which is always "model". */
export type ModelObject = "model";
export const ModelObject = S.String;

/** Describes an OpenAI model offering that can be used with the API. */
export interface Model {
  /** The model identifier, which can be referenced in the API endpoints. */
  id: string;
  /** The Unix timestamp (in seconds) when the model was created. */
  created: number;
  /** The object type, which is always "model". */
  object: ModelObject;
  /** The organization that owns the model. */
  owned_by: string;
  /** The date when the model will shut down, or null if not announced. */
  shutdown_date?: string | null;
}
export const Model = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    created: S.Number,
    object: ModelObject,
    owned_by: S.String,
    shutdown_date: S.optional(S.NullOr(S.String)),
  }),
).annotate({ identifier: "Model" }) as any as S.Schema<Model>;

export interface ListModelsRequest {}
export const ListModelsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/models", code: 200 })),
).annotate({ identifier: "ListModelsRequest" }) as any as S.Schema<ListModelsRequest>;

export type ListModelsResponseObject = "list";
export const ListModelsResponseObject = S.String;

export type ListModelsResponseDataList = Array<Model>;
export const ListModelsResponseDataList = /*@__PURE__*/ S.Array(
  Model,
) as any as S.Schema<ListModelsResponseDataList>;

export interface ListModelsResponse {
  object: ListModelsResponseObject;
  data: ListModelsResponseDataList;
}
export const ListModelsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    object: ListModelsResponseObject,
    data: ListModelsResponseDataList,
  }),
).annotate({ identifier: "ListModelsResponse" }) as any as S.Schema<ListModelsResponse>;

export type DeleteModelError = Forbidden | NotFound | OpenAIOpError;
/** Delete a fine-tuned model Delete a fine-tuned model. You must have the Owner role in your organization to delete a model. */
export const deleteModel: API.OperationMethod<
  DeleteModelRequest,
  DeleteModelResponse,
  DeleteModelError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteModelRequest,
  output: DeleteModelResponse,
  errors: [Forbidden, NotFound, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));

export type GetModelError = Forbidden | NotFound | OpenAIOpError;
/** Retrieve model Retrieves a model instance, providing basic information about the model such as the owner and permissioning. */
export const getModel: API.OperationMethod<GetModelRequest, Model, GetModelError, OpenAIOpContext> =
  /*@__PURE__*/ API.make(() => ({
    input: GetModelRequest,
    output: Model,
    errors: [Forbidden, NotFound, UnknownOpenAIError],
    protocol: OpenAIProtocol,
    retry: Retry.Retry,
  }));

export type ListModelsError = Forbidden | OpenAIOpError;
/** List models Lists the currently available models, and provides basic information about each one such as the owner and availability. */
export const listModels: API.OperationMethod<
  ListModelsRequest,
  ListModelsResponse,
  ListModelsError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListModelsRequest,
  output: ListModelsResponse,
  errors: [Forbidden, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));
