import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-openai). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownOpenAIError } from "../errors.ts";
import { OpenAIProtocol, type OpenAIOpError, type OpenAIOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { OpenAIOpError, OpenAIOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

/** An array of strings to classify for moderation. */
export type CreateModerationRequestInputCase1List = Array<string>;
export const CreateModerationRequestInputCase1List = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreateModerationRequestInputCase1List>;

/** Always `image_url`. */
export type CreateModerationRequestInputCase2ItemCase0Type = "image_url";
export const CreateModerationRequestInputCase2ItemCase0Type = S.String;

/** Contains either an image URL or a data URL for a base64 encoded image. */
export interface CreateModerationRequestInputCase2ItemCase0ImageUrl {
  /** Either a URL of the image or the base64 encoded image data. */
  url: string;
}
export const CreateModerationRequestInputCase2ItemCase0ImageUrl = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.String,
  }),
).annotate({
  identifier: "CreateModerationRequestInputCase2ItemCase0ImageUrl",
}) as any as S.Schema<CreateModerationRequestInputCase2ItemCase0ImageUrl>;

/** An object describing an image to classify. */
export interface CreateModerationRequestInputCase2ItemCase0 {
  /** Always `image_url`. */
  type: CreateModerationRequestInputCase2ItemCase0Type;
  /** Contains either an image URL or a data URL for a base64 encoded image. */
  image_url: CreateModerationRequestInputCase2ItemCase0ImageUrl;
}
export const CreateModerationRequestInputCase2ItemCase0 = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: CreateModerationRequestInputCase2ItemCase0Type,
    image_url: CreateModerationRequestInputCase2ItemCase0ImageUrl,
  }),
).annotate({
  identifier: "CreateModerationRequestInputCase2ItemCase0",
}) as any as S.Schema<CreateModerationRequestInputCase2ItemCase0>;

/** Always `text`. */
export type CreateModerationRequestInputCase2ItemCase1Type = "text";
export const CreateModerationRequestInputCase2ItemCase1Type = S.String;

/** An object describing text to classify. */
export interface CreateModerationRequestInputCase2ItemCase1 {
  /** Always `text`. */
  type: CreateModerationRequestInputCase2ItemCase1Type;
  /** A string of text to classify. */
  text: string;
}
export const CreateModerationRequestInputCase2ItemCase1 = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: CreateModerationRequestInputCase2ItemCase1Type,
    text: S.String,
  }),
).annotate({
  identifier: "CreateModerationRequestInputCase2ItemCase1",
}) as any as S.Schema<CreateModerationRequestInputCase2ItemCase1>;

export type CreateModerationRequestInputCase2Item =
  | CreateModerationRequestInputCase2ItemCase0
  | CreateModerationRequestInputCase2ItemCase1;
export const CreateModerationRequestInputCase2Item =
  S.Unknown as any as S.Schema<CreateModerationRequestInputCase2Item>;

/** An array of multi-modal inputs to the moderation model. */
export type CreateModerationRequestInputCase2List = Array<CreateModerationRequestInputCase2Item>;
export const CreateModerationRequestInputCase2List = /*@__PURE__*/ S.Array(
  CreateModerationRequestInputCase2Item,
) as any as S.Schema<CreateModerationRequestInputCase2List>;

/** Input (or inputs) to classify. Can be a single string, an array of strings, or an array of multi-modal input objects similar to other models. */
export type CreateModerationRequestInput =
  | string
  | CreateModerationRequestInputCase1List
  | CreateModerationRequestInputCase2List;
export const CreateModerationRequestInput =
  S.Unknown as any as S.Schema<CreateModerationRequestInput>;

export type CreateModerationRequestModelCase1 =
  | "omni-moderation-latest"
  | "omni-moderation-2024-09-26"
  | "text-moderation-latest"
  | "text-moderation-stable";
export const CreateModerationRequestModelCase1 = S.String;

/** The content moderation model you would like to use. Learn more in [the moderation guide](https://developers.openai.com/api/docs/guides/moderation), and learn about available models [here](https://developers.openai.com/api/docs/guides/moderation). */
export type CreateModerationRequestModel = string | CreateModerationRequestModelCase1;
export const CreateModerationRequestModel =
  S.Unknown as any as S.Schema<CreateModerationRequestModel>;

export interface CreateModerationRequest {
  /** Input (or inputs) to classify. Can be a single string, an array of strings, or an array of multi-modal input objects similar to other models. */
  input: CreateModerationRequestInput;
  /** The content moderation model you would like to use. Learn more in [the moderation guide](https://developers.openai.com/api/docs/guides/moderation), and learn about available models [here](https://developers.openai.com/api/docs/guides/moderation). */
  model?: CreateModerationRequestModel;
}
export const CreateModerationRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    input: CreateModerationRequestInput,
    model: S.optional(CreateModerationRequestModel),
  }).pipe(T.Http({ method: "POST", uri: "/moderations", code: 200 })),
).annotate({ identifier: "CreateModerationRequest" }) as any as S.Schema<CreateModerationRequest>;

/** A list of the categories, and whether they are flagged or not. */
export interface CreateModerationResponseResultsItemCategories {
  /** Content that expresses, incites, or promotes hate based on race, gender, ethnicity, religion, nationality, sexual orientation, disability status, or caste. Hateful content aimed at non-protected groups (e.g., chess players) is harassment. */
  hate: boolean;
  /** Hateful content that also includes violence or serious harm towards the targeted group based on race, gender, ethnicity, religion, nationality, sexual orientation, disability status, or caste. */
  hate_threatening: boolean;
  /** Content that expresses, incites, or promotes harassing language towards any target. */
  harassment: boolean;
  /** Harassment content that also includes violence or serious harm towards any target. */
  harassment_threatening: boolean;
  illicit: boolean | null;
  illicit_violent: boolean | null;
  /** Content that promotes, encourages, or depicts acts of self-harm, such as suicide, cutting, and eating disorders. */
  self_harm: boolean;
  /** Content where the speaker expresses that they are engaging or intend to engage in acts of self-harm, such as suicide, cutting, and eating disorders. */
  self_harm_intent: boolean;
  /** Content that encourages performing acts of self-harm, such as suicide, cutting, and eating disorders, or that gives instructions or advice on how to commit such acts. */
  self_harm_instructions: boolean;
  /** Content meant to arouse sexual excitement, such as the description of sexual activity, or that promotes sexual services (excluding sex education and wellness). */
  sexual: boolean;
  /** Sexual content that includes an individual who is under 18 years old. */
  sexual_minors: boolean;
  /** Content that depicts death, violence, or physical injury. */
  violence: boolean;
  /** Content that depicts death, violence, or physical injury in graphic detail. */
  violence_graphic: boolean;
}
export const CreateModerationResponseResultsItemCategories = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    hate: S.Boolean,
    hate_threatening: S.Boolean.pipe(T.Body("hate/threatening")),
    harassment: S.Boolean,
    harassment_threatening: S.Boolean.pipe(T.Body("harassment/threatening")),
    illicit: S.NullOr(S.Boolean),
    illicit_violent: S.NullOr(S.Boolean).pipe(T.Body("illicit/violent")),
    self_harm: S.Boolean.pipe(T.Body("self-harm")),
    self_harm_intent: S.Boolean.pipe(T.Body("self-harm/intent")),
    self_harm_instructions: S.Boolean.pipe(T.Body("self-harm/instructions")),
    sexual: S.Boolean,
    sexual_minors: S.Boolean.pipe(T.Body("sexual/minors")),
    violence: S.Boolean,
    violence_graphic: S.Boolean.pipe(T.Body("violence/graphic")),
  }),
).annotate({
  identifier: "CreateModerationResponseResultsItemCategories",
}) as any as S.Schema<CreateModerationResponseResultsItemCategories>;

/** A list of the categories along with their scores as predicted by model. */
export interface CreateModerationResponseResultsItemCategoryScores {
  /** The score for the category 'hate'. */
  hate: number;
  /** The score for the category 'hate/threatening'. */
  hate_threatening: number;
  /** The score for the category 'harassment'. */
  harassment: number;
  /** The score for the category 'harassment/threatening'. */
  harassment_threatening: number;
  /** The score for the category 'illicit'. */
  illicit: number;
  /** The score for the category 'illicit/violent'. */
  illicit_violent: number;
  /** The score for the category 'self-harm'. */
  self_harm: number;
  /** The score for the category 'self-harm/intent'. */
  self_harm_intent: number;
  /** The score for the category 'self-harm/instructions'. */
  self_harm_instructions: number;
  /** The score for the category 'sexual'. */
  sexual: number;
  /** The score for the category 'sexual/minors'. */
  sexual_minors: number;
  /** The score for the category 'violence'. */
  violence: number;
  /** The score for the category 'violence/graphic'. */
  violence_graphic: number;
}
export const CreateModerationResponseResultsItemCategoryScores = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    hate: S.Number,
    hate_threatening: S.Number.pipe(T.Body("hate/threatening")),
    harassment: S.Number,
    harassment_threatening: S.Number.pipe(T.Body("harassment/threatening")),
    illicit: S.Number,
    illicit_violent: S.Number.pipe(T.Body("illicit/violent")),
    self_harm: S.Number.pipe(T.Body("self-harm")),
    self_harm_intent: S.Number.pipe(T.Body("self-harm/intent")),
    self_harm_instructions: S.Number.pipe(T.Body("self-harm/instructions")),
    sexual: S.Number,
    sexual_minors: S.Number.pipe(T.Body("sexual/minors")),
    violence: S.Number,
    violence_graphic: S.Number.pipe(T.Body("violence/graphic")),
  }),
).annotate({
  identifier: "CreateModerationResponseResultsItemCategoryScores",
}) as any as S.Schema<CreateModerationResponseResultsItemCategoryScores>;

export type CreateModerationResponseResultsItemCategoryAppliedInputTypesHateItem = "text";
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesHateItem = S.String;

/** The applied input type(s) for the category 'hate'. */
export type CreateModerationResponseResultsItemCategoryAppliedInputTypesHateList =
  Array<CreateModerationResponseResultsItemCategoryAppliedInputTypesHateItem>;
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesHateList =
  /*@__PURE__*/ S.Array(
    CreateModerationResponseResultsItemCategoryAppliedInputTypesHateItem,
  ) as any as S.Schema<CreateModerationResponseResultsItemCategoryAppliedInputTypesHateList>;

export type CreateModerationResponseResultsItemCategoryAppliedInputTypesHateThreateningItem =
  "text";
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesHateThreateningItem =
  S.String;

/** The applied input type(s) for the category 'hate/threatening'. */
export type CreateModerationResponseResultsItemCategoryAppliedInputTypesHateThreateningList =
  Array<CreateModerationResponseResultsItemCategoryAppliedInputTypesHateThreateningItem>;
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesHateThreateningList =
  /*@__PURE__*/ S.Array(
    CreateModerationResponseResultsItemCategoryAppliedInputTypesHateThreateningItem,
  ) as any as S.Schema<CreateModerationResponseResultsItemCategoryAppliedInputTypesHateThreateningList>;

export type CreateModerationResponseResultsItemCategoryAppliedInputTypesHarassmentItem = "text";
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesHarassmentItem = S.String;

/** The applied input type(s) for the category 'harassment'. */
export type CreateModerationResponseResultsItemCategoryAppliedInputTypesHarassmentList =
  Array<CreateModerationResponseResultsItemCategoryAppliedInputTypesHarassmentItem>;
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesHarassmentList =
  /*@__PURE__*/ S.Array(
    CreateModerationResponseResultsItemCategoryAppliedInputTypesHarassmentItem,
  ) as any as S.Schema<CreateModerationResponseResultsItemCategoryAppliedInputTypesHarassmentList>;

export type CreateModerationResponseResultsItemCategoryAppliedInputTypesHarassmentThreateningItem =
  "text";
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesHarassmentThreateningItem =
  S.String;

/** The applied input type(s) for the category 'harassment/threatening'. */
export type CreateModerationResponseResultsItemCategoryAppliedInputTypesHarassmentThreateningList =
  Array<CreateModerationResponseResultsItemCategoryAppliedInputTypesHarassmentThreateningItem>;
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesHarassmentThreateningList =
  /*@__PURE__*/ S.Array(
    CreateModerationResponseResultsItemCategoryAppliedInputTypesHarassmentThreateningItem,
  ) as any as S.Schema<CreateModerationResponseResultsItemCategoryAppliedInputTypesHarassmentThreateningList>;

export type CreateModerationResponseResultsItemCategoryAppliedInputTypesIllicitItem = "text";
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesIllicitItem = S.String;

/** The applied input type(s) for the category 'illicit'. */
export type CreateModerationResponseResultsItemCategoryAppliedInputTypesIllicitList =
  Array<CreateModerationResponseResultsItemCategoryAppliedInputTypesIllicitItem>;
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesIllicitList =
  /*@__PURE__*/ S.Array(
    CreateModerationResponseResultsItemCategoryAppliedInputTypesIllicitItem,
  ) as any as S.Schema<CreateModerationResponseResultsItemCategoryAppliedInputTypesIllicitList>;

export type CreateModerationResponseResultsItemCategoryAppliedInputTypesIllicitViolentItem = "text";
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesIllicitViolentItem =
  S.String;

/** The applied input type(s) for the category 'illicit/violent'. */
export type CreateModerationResponseResultsItemCategoryAppliedInputTypesIllicitViolentList =
  Array<CreateModerationResponseResultsItemCategoryAppliedInputTypesIllicitViolentItem>;
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesIllicitViolentList =
  /*@__PURE__*/ S.Array(
    CreateModerationResponseResultsItemCategoryAppliedInputTypesIllicitViolentItem,
  ) as any as S.Schema<CreateModerationResponseResultsItemCategoryAppliedInputTypesIllicitViolentList>;

export type CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmItem =
  | "text"
  | "image";
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmItem = S.String;

/** The applied input type(s) for the category 'self-harm'. */
export type CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmList =
  Array<CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmItem>;
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmList =
  /*@__PURE__*/ S.Array(
    CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmItem,
  ) as any as S.Schema<CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmList>;

export type CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmIntentItem =
  | "text"
  | "image";
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmIntentItem =
  S.String;

/** The applied input type(s) for the category 'self-harm/intent'. */
export type CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmIntentList =
  Array<CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmIntentItem>;
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmIntentList =
  /*@__PURE__*/ S.Array(
    CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmIntentItem,
  ) as any as S.Schema<CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmIntentList>;

export type CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmInstructionsItem =
  | "text"
  | "image";
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmInstructionsItem =
  S.String;

/** The applied input type(s) for the category 'self-harm/instructions'. */
export type CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmInstructionsList =
  Array<CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmInstructionsItem>;
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmInstructionsList =
  /*@__PURE__*/ S.Array(
    CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmInstructionsItem,
  ) as any as S.Schema<CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmInstructionsList>;

export type CreateModerationResponseResultsItemCategoryAppliedInputTypesSexualItem =
  | "text"
  | "image";
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesSexualItem = S.String;

/** The applied input type(s) for the category 'sexual'. */
export type CreateModerationResponseResultsItemCategoryAppliedInputTypesSexualList =
  Array<CreateModerationResponseResultsItemCategoryAppliedInputTypesSexualItem>;
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesSexualList =
  /*@__PURE__*/ S.Array(
    CreateModerationResponseResultsItemCategoryAppliedInputTypesSexualItem,
  ) as any as S.Schema<CreateModerationResponseResultsItemCategoryAppliedInputTypesSexualList>;

export type CreateModerationResponseResultsItemCategoryAppliedInputTypesSexualMinorsItem = "text";
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesSexualMinorsItem =
  S.String;

/** The applied input type(s) for the category 'sexual/minors'. */
export type CreateModerationResponseResultsItemCategoryAppliedInputTypesSexualMinorsList =
  Array<CreateModerationResponseResultsItemCategoryAppliedInputTypesSexualMinorsItem>;
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesSexualMinorsList =
  /*@__PURE__*/ S.Array(
    CreateModerationResponseResultsItemCategoryAppliedInputTypesSexualMinorsItem,
  ) as any as S.Schema<CreateModerationResponseResultsItemCategoryAppliedInputTypesSexualMinorsList>;

export type CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceItem =
  | "text"
  | "image";
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceItem = S.String;

/** The applied input type(s) for the category 'violence'. */
export type CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceList =
  Array<CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceItem>;
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceList =
  /*@__PURE__*/ S.Array(
    CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceItem,
  ) as any as S.Schema<CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceList>;

export type CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceGraphicItem =
  | "text"
  | "image";
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceGraphicItem =
  S.String;

/** The applied input type(s) for the category 'violence/graphic'. */
export type CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceGraphicList =
  Array<CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceGraphicItem>;
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceGraphicList =
  /*@__PURE__*/ S.Array(
    CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceGraphicItem,
  ) as any as S.Schema<CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceGraphicList>;

/** A list of the categories along with the input type(s) that the score applies to. */
export interface CreateModerationResponseResultsItemCategoryAppliedInputTypes {
  /** The applied input type(s) for the category 'hate'. */
  hate: CreateModerationResponseResultsItemCategoryAppliedInputTypesHateList;
  /** The applied input type(s) for the category 'hate/threatening'. */
  hate_threatening: CreateModerationResponseResultsItemCategoryAppliedInputTypesHateThreateningList;
  /** The applied input type(s) for the category 'harassment'. */
  harassment: CreateModerationResponseResultsItemCategoryAppliedInputTypesHarassmentList;
  /** The applied input type(s) for the category 'harassment/threatening'. */
  harassment_threatening: CreateModerationResponseResultsItemCategoryAppliedInputTypesHarassmentThreateningList;
  /** The applied input type(s) for the category 'illicit'. */
  illicit: CreateModerationResponseResultsItemCategoryAppliedInputTypesIllicitList;
  /** The applied input type(s) for the category 'illicit/violent'. */
  illicit_violent: CreateModerationResponseResultsItemCategoryAppliedInputTypesIllicitViolentList;
  /** The applied input type(s) for the category 'self-harm'. */
  self_harm: CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmList;
  /** The applied input type(s) for the category 'self-harm/intent'. */
  self_harm_intent: CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmIntentList;
  /** The applied input type(s) for the category 'self-harm/instructions'. */
  self_harm_instructions: CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmInstructionsList;
  /** The applied input type(s) for the category 'sexual'. */
  sexual: CreateModerationResponseResultsItemCategoryAppliedInputTypesSexualList;
  /** The applied input type(s) for the category 'sexual/minors'. */
  sexual_minors: CreateModerationResponseResultsItemCategoryAppliedInputTypesSexualMinorsList;
  /** The applied input type(s) for the category 'violence'. */
  violence: CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceList;
  /** The applied input type(s) for the category 'violence/graphic'. */
  violence_graphic: CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceGraphicList;
}
export const CreateModerationResponseResultsItemCategoryAppliedInputTypes = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      hate: CreateModerationResponseResultsItemCategoryAppliedInputTypesHateList,
      hate_threatening:
        CreateModerationResponseResultsItemCategoryAppliedInputTypesHateThreateningList.pipe(
          T.Body("hate/threatening"),
        ),
      harassment: CreateModerationResponseResultsItemCategoryAppliedInputTypesHarassmentList,
      harassment_threatening:
        CreateModerationResponseResultsItemCategoryAppliedInputTypesHarassmentThreateningList.pipe(
          T.Body("harassment/threatening"),
        ),
      illicit: CreateModerationResponseResultsItemCategoryAppliedInputTypesIllicitList,
      illicit_violent:
        CreateModerationResponseResultsItemCategoryAppliedInputTypesIllicitViolentList.pipe(
          T.Body("illicit/violent"),
        ),
      self_harm: CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmList.pipe(
        T.Body("self-harm"),
      ),
      self_harm_intent:
        CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmIntentList.pipe(
          T.Body("self-harm/intent"),
        ),
      self_harm_instructions:
        CreateModerationResponseResultsItemCategoryAppliedInputTypesSelfHarmInstructionsList.pipe(
          T.Body("self-harm/instructions"),
        ),
      sexual: CreateModerationResponseResultsItemCategoryAppliedInputTypesSexualList,
      sexual_minors:
        CreateModerationResponseResultsItemCategoryAppliedInputTypesSexualMinorsList.pipe(
          T.Body("sexual/minors"),
        ),
      violence: CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceList,
      violence_graphic:
        CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceGraphicList.pipe(
          T.Body("violence/graphic"),
        ),
    }),
).annotate({
  identifier: "CreateModerationResponseResultsItemCategoryAppliedInputTypes",
}) as any as S.Schema<CreateModerationResponseResultsItemCategoryAppliedInputTypes>;

export interface CreateModerationResponseResultsItem {
  /** Whether any of the below categories are flagged. */
  flagged: boolean;
  /** A list of the categories, and whether they are flagged or not. */
  categories: CreateModerationResponseResultsItemCategories;
  /** A list of the categories along with their scores as predicted by model. */
  category_scores: CreateModerationResponseResultsItemCategoryScores;
  /** A list of the categories along with the input type(s) that the score applies to. */
  category_applied_input_types: CreateModerationResponseResultsItemCategoryAppliedInputTypes;
}
export const CreateModerationResponseResultsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    flagged: S.Boolean,
    categories: CreateModerationResponseResultsItemCategories,
    category_scores: CreateModerationResponseResultsItemCategoryScores,
    category_applied_input_types: CreateModerationResponseResultsItemCategoryAppliedInputTypes,
  }),
).annotate({
  identifier: "CreateModerationResponseResultsItem",
}) as any as S.Schema<CreateModerationResponseResultsItem>;

/** A list of moderation objects. */
export type CreateModerationResponseResultsList = Array<CreateModerationResponseResultsItem>;
export const CreateModerationResponseResultsList = /*@__PURE__*/ S.Array(
  CreateModerationResponseResultsItem,
) as any as S.Schema<CreateModerationResponseResultsList>;

/** Represents if a given text input is potentially harmful. */
export interface CreateModerationResponse {
  /** The unique identifier for the moderation request. */
  id: string;
  /** The model used to generate the moderation results. */
  model: string;
  /** A list of moderation objects. */
  results: CreateModerationResponseResultsList;
}
export const CreateModerationResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    model: S.String,
    results: CreateModerationResponseResultsList,
  }),
).annotate({ identifier: "CreateModerationResponse" }) as any as S.Schema<CreateModerationResponse>;

export type CreateModerationError = BadRequest | Forbidden | OpenAIOpError;
/** Create moderation Classifies if text and/or image inputs are potentially harmful. Learn more in the [moderation guide](https://developers.openai.com/api/docs/guides/moderation). */
export const createModeration: API.OperationMethod<
  CreateModerationRequest,
  CreateModerationResponse,
  CreateModerationError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateModerationRequest,
  output: CreateModerationResponse,
  errors: [BadRequest, Forbidden, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));
