import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-openai). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownOpenAIError } from "../errors.ts";
import { paginateAfter } from "../pagination.ts";
import { OpenAIProtocol, type OpenAIOpError, type OpenAIOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { OpenAIOpError, OpenAIOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

/** Skill files to upload (directory upload) or a single zip file. */
export type CreateSkillRequestFilesCase0List = Array<Blob | Uint8Array | ArrayBuffer>;
export const CreateSkillRequestFilesCase0List = /*@__PURE__*/ S.Array(
  S.Union([S.instanceOf(Blob), S.instanceOf(Uint8Array), S.instanceOf(ArrayBuffer)]),
) as any as S.Schema<CreateSkillRequestFilesCase0List>;

export type CreateSkillRequestFiles =
  | CreateSkillRequestFilesCase0List
  | Blob
  | Uint8Array
  | ArrayBuffer;
export const CreateSkillRequestFiles = S.Unknown as any as S.Schema<CreateSkillRequestFiles>;

export interface CreateSkillRequest {
  files: CreateSkillRequestFiles;
}
export const CreateSkillRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    files: CreateSkillRequestFiles,
  }).pipe(T.Http({ method: "POST", uri: "/skills", code: 200 })),
).annotate({ identifier: "CreateSkillRequest" }) as any as S.Schema<CreateSkillRequest>;

/** The object type, which is `skill`. */
export type SkillResourceObject = "skill";
export const SkillResourceObject = S.String;

export interface SkillResource {
  /** Unique identifier for the skill. */
  id: string;
  /** The object type, which is `skill`. */
  object: SkillResourceObject;
  /** Name of the skill. */
  name: string;
  /** Description of the skill. */
  description: string;
  /** Unix timestamp (seconds) for when the skill was created. */
  created_at: number;
  /** Default version for the skill. */
  default_version: string;
  /** Latest version for the skill. */
  latest_version: string;
}
export const SkillResource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    object: SkillResourceObject,
    name: S.String,
    description: S.String,
    created_at: S.Number,
    default_version: S.String,
    latest_version: S.String,
  }),
).annotate({ identifier: "SkillResource" }) as any as S.Schema<SkillResource>;

/** Skill files to upload (directory upload) or a single zip file. */
export type CreateSkillVersionRequestFilesCase0List = Array<Blob | Uint8Array | ArrayBuffer>;
export const CreateSkillVersionRequestFilesCase0List = /*@__PURE__*/ S.Array(
  S.Union([S.instanceOf(Blob), S.instanceOf(Uint8Array), S.instanceOf(ArrayBuffer)]),
) as any as S.Schema<CreateSkillVersionRequestFilesCase0List>;

export type CreateSkillVersionRequestFiles =
  | CreateSkillVersionRequestFilesCase0List
  | Blob
  | Uint8Array
  | ArrayBuffer;
export const CreateSkillVersionRequestFiles =
  S.Unknown as any as S.Schema<CreateSkillVersionRequestFiles>;

export interface CreateSkillVersionRequest {
  /** The identifier of the skill to version. */
  skill_id: string;
  files: CreateSkillVersionRequestFiles;
  /** Whether to set this version as the default. */
  default?: boolean;
}
export const CreateSkillVersionRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    skill_id: S.String.pipe(T.Label()),
    files: CreateSkillVersionRequestFiles,
    default: S.optional(S.Boolean),
  }).pipe(T.Http({ method: "POST", uri: "/skills/{skill_id}/versions", code: 200 })),
).annotate({
  identifier: "CreateSkillVersionRequest",
}) as any as S.Schema<CreateSkillVersionRequest>;

/** The object type, which is `skill.version`. */
export type SkillVersionResourceObject = "skill.version";
export const SkillVersionResourceObject = S.String;

export interface SkillVersionResource {
  /** The object type, which is `skill.version`. */
  object: SkillVersionResourceObject;
  /** Unique identifier for the skill version. */
  id: string;
  /** Identifier of the skill for this version. */
  skill_id: string;
  /** Version number for this skill. */
  version: string;
  /** Unix timestamp (seconds) for when the version was created. */
  created_at: number;
  /** Name of the skill version. */
  name: string;
  /** Description of the skill version. */
  description: string;
}
export const SkillVersionResource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    object: SkillVersionResourceObject,
    id: S.String,
    skill_id: S.String,
    version: S.String,
    created_at: S.Number,
    name: S.String,
    description: S.String,
  }),
).annotate({ identifier: "SkillVersionResource" }) as any as S.Schema<SkillVersionResource>;

export interface DeleteSkillRequest {
  /** The identifier of the skill to delete. */
  skill_id: string;
}
export const DeleteSkillRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    skill_id: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "DELETE", uri: "/skills/{skill_id}", code: 200 })),
).annotate({ identifier: "DeleteSkillRequest" }) as any as S.Schema<DeleteSkillRequest>;

export type DeletedSkillResourceObject = "skill.deleted";
export const DeletedSkillResourceObject = S.String;

export interface DeletedSkillResource {
  object: DeletedSkillResourceObject;
  deleted: boolean;
  id: string;
}
export const DeletedSkillResource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    object: DeletedSkillResourceObject,
    deleted: S.Boolean,
    id: S.String,
  }),
).annotate({ identifier: "DeletedSkillResource" }) as any as S.Schema<DeletedSkillResource>;

export interface DeleteSkillVersionRequest {
  /** The identifier of the skill. */
  skill_id: string;
  /** The skill version number. */
  version: string;
}
export const DeleteSkillVersionRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    skill_id: S.String.pipe(T.Label()),
    version: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "DELETE", uri: "/skills/{skill_id}/versions/{version}", code: 200 })),
).annotate({
  identifier: "DeleteSkillVersionRequest",
}) as any as S.Schema<DeleteSkillVersionRequest>;

export type DeletedSkillVersionResourceObject = "skill.version.deleted";
export const DeletedSkillVersionResourceObject = S.String;

export interface DeletedSkillVersionResource {
  object: DeletedSkillVersionResourceObject;
  deleted: boolean;
  id: string;
  /** The deleted skill version. */
  version: string;
}
export const DeletedSkillVersionResource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    object: DeletedSkillVersionResourceObject,
    deleted: S.Boolean,
    id: S.String,
    version: S.String,
  }),
).annotate({
  identifier: "DeletedSkillVersionResource",
}) as any as S.Schema<DeletedSkillVersionResource>;

export interface GetSkillRequest {
  /** The identifier of the skill to retrieve. */
  skill_id: string;
}
export const GetSkillRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    skill_id: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/skills/{skill_id}", code: 200 })),
).annotate({ identifier: "GetSkillRequest" }) as any as S.Schema<GetSkillRequest>;

export interface GetSkillContentRequest {
  /** The identifier of the skill to download. */
  skill_id: string;
}
export const GetSkillContentRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    skill_id: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/skills/{skill_id}/content", code: 200 })),
).annotate({ identifier: "GetSkillContentRequest" }) as any as S.Schema<GetSkillContentRequest>;

export type GetSkillContentResponse = string;
export const GetSkillContentResponse = /*@__PURE__*/ S.suspend(() =>
  S.String.pipe(T.RawResponseRoot()),
).annotate({ identifier: "GetSkillContentResponse" }) as any as S.Schema<GetSkillContentResponse>;

export interface GetSkillVersionRequest {
  /** The identifier of the skill. */
  skill_id: string;
  /** The version number to retrieve. */
  version: string;
}
export const GetSkillVersionRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    skill_id: S.String.pipe(T.Label()),
    version: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/skills/{skill_id}/versions/{version}", code: 200 })),
).annotate({ identifier: "GetSkillVersionRequest" }) as any as S.Schema<GetSkillVersionRequest>;

export interface GetSkillVersionContentRequest {
  /** The identifier of the skill. */
  skill_id: string;
  /** The skill version number. */
  version: string;
}
export const GetSkillVersionContentRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    skill_id: S.String.pipe(T.Label()),
    version: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({ method: "GET", uri: "/skills/{skill_id}/versions/{version}/content", code: 200 }),
  ),
).annotate({
  identifier: "GetSkillVersionContentRequest",
}) as any as S.Schema<GetSkillVersionContentRequest>;

export type GetSkillVersionContentResponse = string;
export const GetSkillVersionContentResponse = /*@__PURE__*/ S.suspend(() =>
  S.String.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "GetSkillVersionContentResponse",
}) as any as S.Schema<GetSkillVersionContentResponse>;

export type OrderEnum = "asc" | "desc";
export const OrderEnum = S.String;

export interface ListSkillsRequest {
  /** Number of items to retrieve */
  limit?: number;
  /** Sort order of results by timestamp. Use `asc` for ascending order or `desc` for descending order. */
  order?: OrderEnum | (string & {});
  /** Identifier for the last item from the previous pagination request */
  after?: string;
}
export const ListSkillsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    limit: S.optional(S.Number.pipe(T.Query())),
    order: S.optional(OrderEnum.pipe(T.Query())),
    after: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/skills", code: 200 })),
).annotate({ identifier: "ListSkillsRequest" }) as any as S.Schema<ListSkillsRequest>;

/** The type of object returned, must be `list`. */
export type SkillListResourceObject = "list";
export const SkillListResourceObject = S.String;

/** A list of items */
export type SkillListResourceDataList = Array<SkillResource>;
export const SkillListResourceDataList = /*@__PURE__*/ S.Array(
  SkillResource,
) as any as S.Schema<SkillListResourceDataList>;

export interface SkillListResource {
  /** The type of object returned, must be `list`. */
  object: SkillListResourceObject;
  /** A list of items */
  data: SkillListResourceDataList;
  first_id: string | null;
  last_id: string | null;
  /** Whether there are more items available. */
  has_more: boolean;
}
export const SkillListResource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    object: SkillListResourceObject,
    data: SkillListResourceDataList,
    first_id: S.NullOr(S.String),
    last_id: S.NullOr(S.String),
    has_more: S.Boolean,
  }),
).annotate({ identifier: "SkillListResource" }) as any as S.Schema<SkillListResource>;

export interface ListSkillVersionsRequest {
  /** The identifier of the skill. */
  skill_id: string;
  /** Number of versions to retrieve. */
  limit?: number;
  /** Sort order of results by version number. */
  order?: OrderEnum | (string & {});
  /** The skill version ID to start after. */
  after?: string;
}
export const ListSkillVersionsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    skill_id: S.String.pipe(T.Label()),
    limit: S.optional(S.Number.pipe(T.Query())),
    order: S.optional(OrderEnum.pipe(T.Query())),
    after: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/skills/{skill_id}/versions", code: 200 })),
).annotate({ identifier: "ListSkillVersionsRequest" }) as any as S.Schema<ListSkillVersionsRequest>;

/** The type of object returned, must be `list`. */
export type SkillVersionListResourceObject = "list";
export const SkillVersionListResourceObject = S.String;

/** A list of items */
export type SkillVersionListResourceDataList = Array<SkillVersionResource>;
export const SkillVersionListResourceDataList = /*@__PURE__*/ S.Array(
  SkillVersionResource,
) as any as S.Schema<SkillVersionListResourceDataList>;

export interface SkillVersionListResource {
  /** The type of object returned, must be `list`. */
  object: SkillVersionListResourceObject;
  /** A list of items */
  data: SkillVersionListResourceDataList;
  first_id: string | null;
  last_id: string | null;
  /** Whether there are more items available. */
  has_more: boolean;
}
export const SkillVersionListResource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    object: SkillVersionListResourceObject,
    data: SkillVersionListResourceDataList,
    first_id: S.NullOr(S.String),
    last_id: S.NullOr(S.String),
    has_more: S.Boolean,
  }),
).annotate({ identifier: "SkillVersionListResource" }) as any as S.Schema<SkillVersionListResource>;

export interface UpdateSkillDefaultVersionRequest {
  /** The identifier of the skill. */
  skill_id: string;
  /** The skill version number to set as default. */
  default_version: string;
}
export const UpdateSkillDefaultVersionRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    skill_id: S.String.pipe(T.Label()),
    default_version: S.String,
  }).pipe(T.Http({ method: "POST", uri: "/skills/{skill_id}", code: 200 })),
).annotate({
  identifier: "UpdateSkillDefaultVersionRequest",
}) as any as S.Schema<UpdateSkillDefaultVersionRequest>;

export type CreateSkillError = BadRequest | OpenAIOpError;
/** Create Skill Create a new skill. */
export const createSkill: API.OperationMethod<
  CreateSkillRequest,
  SkillResource,
  CreateSkillError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateSkillRequest,
  output: SkillResource,
  errors: [BadRequest, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));

export type CreateSkillVersionError = BadRequest | NotFound | OpenAIOpError;
/** Create Skill Version Create a new immutable skill version. */
export const createSkillVersion: API.OperationMethod<
  CreateSkillVersionRequest,
  SkillVersionResource,
  CreateSkillVersionError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateSkillVersionRequest,
  output: SkillVersionResource,
  errors: [BadRequest, NotFound, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));

export type DeleteSkillError = NotFound | OpenAIOpError;
/** Delete Skill Delete a skill by its ID. */
export const deleteSkill: API.OperationMethod<
  DeleteSkillRequest,
  DeletedSkillResource,
  DeleteSkillError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteSkillRequest,
  output: DeletedSkillResource,
  errors: [NotFound, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));

export type DeleteSkillVersionError = BadRequest | NotFound | OpenAIOpError;
/** Delete Skill Version Delete a skill version. */
export const deleteSkillVersion: API.OperationMethod<
  DeleteSkillVersionRequest,
  DeletedSkillVersionResource,
  DeleteSkillVersionError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteSkillVersionRequest,
  output: DeletedSkillVersionResource,
  errors: [BadRequest, NotFound, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));

export type GetSkillError = NotFound | OpenAIOpError;
/** Get Skill Get a skill by its ID. */
export const getSkill: API.OperationMethod<
  GetSkillRequest,
  SkillResource,
  GetSkillError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetSkillRequest,
  output: SkillResource,
  errors: [NotFound, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));

export type GetSkillContentError = NotFound | OpenAIOpError;
/** Get Skill Content Download a skill zip bundle by its ID. */
export const getSkillContent: API.OperationMethod<
  GetSkillContentRequest,
  GetSkillContentResponse,
  GetSkillContentError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetSkillContentRequest,
  output: GetSkillContentResponse,
  errors: [NotFound, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));

export type GetSkillVersionError = BadRequest | NotFound | OpenAIOpError;
/** Get Skill Version Get a specific skill version. */
export const getSkillVersion: API.OperationMethod<
  GetSkillVersionRequest,
  SkillVersionResource,
  GetSkillVersionError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetSkillVersionRequest,
  output: SkillVersionResource,
  errors: [BadRequest, NotFound, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));

export type GetSkillVersionContentError = BadRequest | NotFound | OpenAIOpError;
/** Get Skill Version Content Download a skill version zip bundle. */
export const getSkillVersionContent: API.OperationMethod<
  GetSkillVersionContentRequest,
  GetSkillVersionContentResponse,
  GetSkillVersionContentError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetSkillVersionContentRequest,
  output: GetSkillVersionContentResponse,
  errors: [BadRequest, NotFound, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));

export type ListSkillsError = NotFound | OpenAIOpError;
/** List Skills List all skills for the current project. */
export const listSkills: API.PaginatedOperationMethod<
  ListSkillsRequest,
  SkillListResource,
  ListSkillsError,
  OpenAIOpContext,
  SkillResource
> = /*@__PURE__*/ API.makePaginated(
  () => ({
    input: ListSkillsRequest,
    output: SkillListResource,
    errors: [NotFound, UnknownOpenAIError],
    protocol: OpenAIProtocol,
    retry: Retry.Retry,
    pagination: {
      mode: "cursor",
      inputToken: "after",
      outputToken: "last_id",
      items: "data",
      pageSize: "limit",
    } as const,
  }),
  paginateAfter,
) as any;

export type ListSkillVersionsError = BadRequest | NotFound | OpenAIOpError;
/** List Skill Versions List skill versions for a skill. */
export const listSkillVersions: API.PaginatedOperationMethod<
  ListSkillVersionsRequest,
  SkillVersionListResource,
  ListSkillVersionsError,
  OpenAIOpContext,
  SkillVersionResource
> = /*@__PURE__*/ API.makePaginated(
  () => ({
    input: ListSkillVersionsRequest,
    output: SkillVersionListResource,
    errors: [BadRequest, NotFound, UnknownOpenAIError],
    protocol: OpenAIProtocol,
    retry: Retry.Retry,
    pagination: {
      mode: "cursor",
      inputToken: "after",
      outputToken: "last_id",
      items: "data",
      pageSize: "limit",
    } as const,
  }),
  paginateAfter,
) as any;

export type UpdateSkillDefaultVersionError = BadRequest | NotFound | OpenAIOpError;
/** Update Skill Default Version Update the default version pointer for a skill. */
export const updateSkillDefaultVersion: API.OperationMethod<
  UpdateSkillDefaultVersionRequest,
  SkillResource,
  UpdateSkillDefaultVersionError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateSkillDefaultVersionRequest,
  output: SkillResource,
  errors: [BadRequest, NotFound, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));
