import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-openai). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownOpenAIError } from "../errors.ts";
import { paginateAfter } from "../pagination.ts";
import { OpenAIProtocol, type OpenAIOpError, type OpenAIOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { OpenAIOpError, OpenAIOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

export interface AssignUserRoleRequest {
  /** The ID of the user that should receive the organization role. */
  user_id: string;
  /** Identifier of the role to assign. */
  role_id: string;
}
export const AssignUserRoleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    user_id: S.String.pipe(T.Label()),
    role_id: S.String,
  })
    .pipe(T.Http({ method: "POST", uri: "/organization/users/{user_id}/roles", code: 200 }))
    .pipe(T.AdminAuth()),
).annotate({ identifier: "AssignUserRoleRequest" }) as any as S.Schema<AssignUserRoleRequest>;

/** Always `user.role`. */
export type UserRoleAssignmentObject = "user.role";
export const UserRoleAssignmentObject = S.String;

/** The object type, which is always `organization.user` */
export type UserObject = "organization.user";
export const UserObject = S.String;

export type UserUserObject = "user";
export const UserUserObject = S.String;

/** Nested user details. */
export interface UserUser {
  object: UserUserObject;
  id: string;
  email?: string | null;
  name?: string | null;
  picture?: string | null;
  enabled?: boolean | null;
  banned?: boolean | null;
  banned_at?: number | null;
}
export const UserUser = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    object: UserUserObject,
    id: S.String,
    email: S.optional(S.NullOr(S.String)),
    name: S.optional(S.NullOr(S.String)),
    picture: S.optional(S.NullOr(S.String)),
    enabled: S.optional(S.NullOr(S.Boolean)),
    banned: S.optional(S.NullOr(S.Boolean)),
    banned_at: S.optional(S.NullOr(S.Number)),
  }),
).annotate({ identifier: "UserUser" }) as any as S.Schema<UserUser>;

export type UserProjectsObject = "list";
export const UserProjectsObject = S.String;

export interface UserProjectsDataItem {
  id?: string | null;
  name?: string | null;
  role?: string | null;
}
export const UserProjectsDataItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.NullOr(S.String)),
    name: S.optional(S.NullOr(S.String)),
    role: S.optional(S.NullOr(S.String)),
  }),
).annotate({ identifier: "UserProjectsDataItem" }) as any as S.Schema<UserProjectsDataItem>;

export type UserProjectsDataList = Array<UserProjectsDataItem>;
export const UserProjectsDataList = /*@__PURE__*/ S.Array(
  UserProjectsDataItem,
) as any as S.Schema<UserProjectsDataList>;

export interface UserProjects {
  object: UserProjectsObject;
  data: UserProjectsDataList;
}
export const UserProjects = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    object: UserProjectsObject,
    data: UserProjectsDataList,
  }),
).annotate({ identifier: "UserProjects" }) as any as S.Schema<UserProjects>;

/** Represents an individual `user` within an organization. */
export interface User {
  /** The object type, which is always `organization.user` */
  object: UserObject;
  /** The identifier, which can be referenced in API endpoints */
  id: string;
  /** The name of the user */
  name?: string | null;
  /** The email address of the user */
  email?: string | null;
  /** `owner` or `reader` */
  role?: string | null;
  /** The Unix timestamp (in seconds) of when the user was added. */
  added_at: number;
  /** Whether this is the organization's default user. */
  is_default?: boolean;
  /** The Unix timestamp (in seconds) of when the user was created. */
  created?: number;
  /** Nested user details. */
  user?: UserUser;
  /** Whether the user is a service account. */
  is_service_account?: boolean;
  /** Whether the user is an authorized purchaser for Scale Tier. */
  is_scale_tier_authorized_purchaser?: boolean | null;
  /** Whether the user is managed through SCIM. */
  is_scim_managed?: boolean;
  /** The Unix timestamp (in seconds) of the user's last API key usage. */
  api_key_last_used_at?: number | null;
  /** The technical level metadata for the user. */
  technical_level?: string | null;
  /** The developer persona metadata for the user. */
  developer_persona?: string | null;
  /** Projects associated with the user, if included. */
  projects?: UserProjects | null;
}
export const User = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    object: UserObject,
    id: S.String,
    name: S.optional(S.NullOr(S.String)),
    email: S.optional(S.NullOr(S.String)),
    role: S.optional(S.NullOr(S.String)),
    added_at: S.Number,
    is_default: S.optional(S.Boolean),
    created: S.optional(S.Number),
    user: S.optional(UserUser),
    is_service_account: S.optional(S.Boolean),
    is_scale_tier_authorized_purchaser: S.optional(S.NullOr(S.Boolean)),
    is_scim_managed: S.optional(S.Boolean),
    api_key_last_used_at: S.optional(S.NullOr(S.Number)),
    technical_level: S.optional(S.NullOr(S.String)),
    developer_persona: S.optional(S.NullOr(S.String)),
    projects: S.optional(S.NullOr(UserProjects)),
  }),
).annotate({ identifier: "User" }) as any as S.Schema<User>;

/** Always `role`. */
export type RoleObject = "role";
export const RoleObject = S.String;

/** Permissions granted by the role. */
export type RolePermissionsList = Array<string>;
export const RolePermissionsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<RolePermissionsList>;

/** Details about a role that can be assigned through the public Roles API. */
export interface Role {
  /** Always `role`. */
  object: RoleObject;
  /** Identifier for the role. */
  id: string;
  /** Unique name for the role. */
  name: string;
  /** Optional description of the role. */
  description: string | null;
  /** Permissions granted by the role. */
  permissions: RolePermissionsList;
  /** Resource type the role is bound to (for example `api.organization` or `api.project`). */
  resource_type: string;
  /** Whether the role is predefined and managed by OpenAI. */
  predefined_role: boolean;
}
export const Role = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    object: RoleObject,
    id: S.String,
    name: S.String,
    description: S.NullOr(S.String),
    permissions: RolePermissionsList,
    resource_type: S.String,
    predefined_role: S.Boolean,
  }),
).annotate({ identifier: "Role" }) as any as S.Schema<Role>;

/** Role assignment linking a user to a role. */
export interface UserRoleAssignment {
  /** Always `user.role`. */
  object: UserRoleAssignmentObject;
  user: User;
  role: Role;
}
export const UserRoleAssignment = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    object: UserRoleAssignmentObject,
    user: User,
    role: Role,
  }),
).annotate({ identifier: "UserRoleAssignment" }) as any as S.Schema<UserRoleAssignment>;

export interface GetUserRoleRequest {
  /** The ID of the user to inspect. */
  user_id: string;
  /** The ID of the organization role to retrieve for the user. */
  role_id: string;
}
export const GetUserRoleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    user_id: S.String.pipe(T.Label()),
    role_id: S.String.pipe(T.Label()),
  })
    .pipe(
      T.Http({ method: "GET", uri: "/organization/users/{user_id}/roles/{role_id}", code: 200 }),
    )
    .pipe(T.AdminAuth()),
).annotate({ identifier: "GetUserRoleRequest" }) as any as S.Schema<GetUserRoleRequest>;

/** Permissions associated with the role. */
export type AssignedRoleDetailsPermissionsList = Array<string>;
export const AssignedRoleDetailsPermissionsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<AssignedRoleDetailsPermissionsList>;

export type AssignedRoleDetailsCreatedByUserObjMap = { [key: string]: unknown | undefined };
export const AssignedRoleDetailsCreatedByUserObjMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<AssignedRoleDetailsCreatedByUserObjMap>;

export type AssignedRoleDetailsMetadataMap = { [key: string]: unknown | undefined };
export const AssignedRoleDetailsMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<AssignedRoleDetailsMetadataMap>;

export interface AssignedRoleDetailsAssignmentSourcesItem {
  principal_id: string;
  principal_type: string;
}
export const AssignedRoleDetailsAssignmentSourcesItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    principal_id: S.String,
    principal_type: S.String,
  }),
).annotate({
  identifier: "AssignedRoleDetailsAssignmentSourcesItem",
}) as any as S.Schema<AssignedRoleDetailsAssignmentSourcesItem>;

export type AssignedRoleDetailsAssignmentSourcesList =
  Array<AssignedRoleDetailsAssignmentSourcesItem>;
export const AssignedRoleDetailsAssignmentSourcesList = /*@__PURE__*/ S.Array(
  AssignedRoleDetailsAssignmentSourcesItem,
) as any as S.Schema<AssignedRoleDetailsAssignmentSourcesList>;

/** Detailed information about a role assignment entry returned when listing assignments. */
export interface AssignedRoleDetails {
  /** Identifier for the role. */
  id: string;
  /** Name of the role. */
  name: string;
  /** Permissions associated with the role. */
  permissions: AssignedRoleDetailsPermissionsList;
  /** Resource type the role applies to. */
  resource_type: string;
  /** Whether the role is predefined by OpenAI. */
  predefined_role: boolean;
  /** Description of the role. */
  description: string | null;
  /** When the role was created. */
  created_at: number | null;
  /** When the role was last updated. */
  updated_at: number | null;
  /** Identifier of the actor who created the role. */
  created_by: string | null;
  /** User details for the actor that created the role, when available. */
  created_by_user_obj: AssignedRoleDetailsCreatedByUserObjMap | null;
  /** Arbitrary metadata stored on the role. */
  metadata: AssignedRoleDetailsMetadataMap | null;
  /** Principals from which the role assignment is inherited, when available. */
  assignment_sources: AssignedRoleDetailsAssignmentSourcesList | null;
}
export const AssignedRoleDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    name: S.String,
    permissions: AssignedRoleDetailsPermissionsList,
    resource_type: S.String,
    predefined_role: S.Boolean,
    description: S.NullOr(S.String),
    created_at: S.NullOr(S.Number),
    updated_at: S.NullOr(S.Number),
    created_by: S.NullOr(S.String),
    created_by_user_obj: S.NullOr(AssignedRoleDetailsCreatedByUserObjMap),
    metadata: S.NullOr(AssignedRoleDetailsMetadataMap),
    assignment_sources: S.NullOr(AssignedRoleDetailsAssignmentSourcesList),
  }),
).annotate({ identifier: "AssignedRoleDetails" }) as any as S.Schema<AssignedRoleDetails>;

export type ListUserRoleAssignmentsRequestOrder = "asc" | "desc";
export const ListUserRoleAssignmentsRequestOrder = S.String;

export interface ListUserRoleAssignmentsRequest {
  /** The ID of the user to inspect. */
  user_id: string;
  /** A limit on the number of organization role assignments to return. */
  limit?: number;
  /** Cursor for pagination. Provide the value from the previous response's `next` field to continue listing organization roles. */
  after?: string;
  /** Sort order for the returned organization roles. */
  order?: ListUserRoleAssignmentsRequestOrder | (string & {});
}
export const ListUserRoleAssignmentsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    user_id: S.String.pipe(T.Label()),
    limit: S.optional(S.Number.pipe(T.Query())),
    after: S.optional(S.String.pipe(T.Query())),
    order: S.optional(ListUserRoleAssignmentsRequestOrder.pipe(T.Query())),
  })
    .pipe(T.Http({ method: "GET", uri: "/organization/users/{user_id}/roles", code: 200 }))
    .pipe(T.AdminAuth()),
).annotate({
  identifier: "ListUserRoleAssignmentsRequest",
}) as any as S.Schema<ListUserRoleAssignmentsRequest>;

/** Always `list`. */
export type RoleListResourceObject = "list";
export const RoleListResourceObject = S.String;

/** Role assignments returned in the current page. */
export type RoleListResourceDataList = Array<AssignedRoleDetails>;
export const RoleListResourceDataList = /*@__PURE__*/ S.Array(
  AssignedRoleDetails,
) as any as S.Schema<RoleListResourceDataList>;

/** Paginated list of roles assigned to a principal. */
export interface RoleListResource {
  /** Always `list`. */
  object: RoleListResourceObject;
  /** Role assignments returned in the current page. */
  data: RoleListResourceDataList;
  /** Whether additional assignments are available when paginating. */
  has_more: boolean;
  /** Cursor to fetch the next page of results, or `null` when there are no more assignments. */
  next: string | null;
}
export const RoleListResource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    object: RoleListResourceObject,
    data: RoleListResourceDataList,
    has_more: S.Boolean,
    next: S.NullOr(S.String),
  }),
).annotate({ identifier: "RoleListResource" }) as any as S.Schema<RoleListResource>;

export interface UnassignUserRoleRequest {
  /** The ID of the user to modify. */
  user_id: string;
  /** The ID of the organization role to remove from the user. */
  role_id: string;
}
export const UnassignUserRoleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    user_id: S.String.pipe(T.Label()),
    role_id: S.String.pipe(T.Label()),
  })
    .pipe(
      T.Http({ method: "DELETE", uri: "/organization/users/{user_id}/roles/{role_id}", code: 200 }),
    )
    .pipe(T.AdminAuth()),
).annotate({ identifier: "UnassignUserRoleRequest" }) as any as S.Schema<UnassignUserRoleRequest>;

/** Confirmation payload returned after unassigning a role. */
export interface DeletedRoleAssignmentResource {
  /** Identifier for the deleted assignment, such as `group.role.deleted` or `user.role.deleted`. */
  object: string;
  /** Whether the assignment was removed. */
  deleted: boolean;
}
export const DeletedRoleAssignmentResource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    object: S.String,
    deleted: S.Boolean,
  }),
).annotate({
  identifier: "DeletedRoleAssignmentResource",
}) as any as S.Schema<DeletedRoleAssignmentResource>;

export type AssignUserRoleError = BadRequest | Forbidden | NotFound | OpenAIOpError;
/** Assign organization role to user Assigns an organization role to a user within the organization. */
export const assignUserRole: API.OperationMethod<
  AssignUserRoleRequest,
  UserRoleAssignment,
  AssignUserRoleError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AssignUserRoleRequest,
  output: UserRoleAssignment,
  errors: [BadRequest, Forbidden, NotFound, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));

export type GetUserRoleError = BadRequest | Forbidden | NotFound | OpenAIOpError;
/** Retrieve user organization role Retrieves an organization role assigned to a user. */
export const getUserRole: API.OperationMethod<
  GetUserRoleRequest,
  AssignedRoleDetails,
  GetUserRoleError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetUserRoleRequest,
  output: AssignedRoleDetails,
  errors: [BadRequest, Forbidden, NotFound, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));

export type ListUserRoleAssignmentsError = BadRequest | Forbidden | NotFound | OpenAIOpError;
/** List user organization role assignments Lists the organization roles assigned to a user within the organization. */
export const listUserRoleAssignments: API.PaginatedOperationMethod<
  ListUserRoleAssignmentsRequest,
  RoleListResource,
  ListUserRoleAssignmentsError,
  OpenAIOpContext,
  AssignedRoleDetails
> = /*@__PURE__*/ API.makePaginated(
  () => ({
    input: ListUserRoleAssignmentsRequest,
    output: RoleListResource,
    errors: [BadRequest, Forbidden, NotFound, UnknownOpenAIError],
    protocol: OpenAIProtocol,
    retry: Retry.Retry,
    pagination: {
      mode: "cursor",
      inputToken: "after",
      outputToken: "next",
      items: "data",
      pageSize: "limit",
    } as const,
  }),
  paginateAfter,
) as any;

export type UnassignUserRoleError = BadRequest | Forbidden | NotFound | OpenAIOpError;
/** Unassign organization role from user Unassigns an organization role from a user within the organization. */
export const unassignUserRole: API.OperationMethod<
  UnassignUserRoleRequest,
  DeletedRoleAssignmentResource,
  UnassignUserRoleError,
  OpenAIOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UnassignUserRoleRequest,
  output: DeletedRoleAssignmentResource,
  errors: [BadRequest, Forbidden, NotFound, UnknownOpenAIError],
  protocol: OpenAIProtocol,
  retry: Retry.Retry,
}));
