// Re-export everything from distilled-core
export {
  // Core category constants
  AuthError,
  BadRequestError,
  ConflictError,
  NotFoundError,
  QuotaError,
  ServerError,
  ThrottlingError,
  NetworkError,
  ParseError,
  ConfigurationError,
  TimeoutError,
  RetryableError,
  // Category storage keys
  categoriesKey,
  retryableKey,
  // Category decorators
  withCategory,
  withRetryable,
  withAuthError,
  withBadRequestError,
  withConflictError,
  withNotFoundError,
  withQuotaError,
  withServerError,
  withThrottlingError,
  withNetworkError,
  withParseError,
  withConfigurationError,
  withTimeoutError,
  withRetryableError,
  // Category predicates
  hasCategory,
  isAuthError,
  isBadRequestError,
  isConflictError,
  isNotFoundError,
  isQuotaError,
  isServerError,
  isThrottlingError,
  isNetworkError,
  isParseError,
  isConfigurationError,
  isTimeoutError,
  isRetryableError,
  // Transient error detection
  isRetryable,
  getRetryableInfo,
  isThrottling,
  isTransientError,
  isHttpClientTransportError,
  // Category catchers
  makeCatcher,
  catchErrors,
  catchErrors as catch,
  catchAuthError,
  catchBadRequestError,
  catchConflictError,
  catchNotFoundError,
  catchQuotaError,
  catchServerError,
  catchThrottlingError,
  catchNetworkError,
  catchParseError,
  catchConfigurationError,
  catchTimeoutError,
  catchRetryableError,
  catchCategory,
} from "distilled-core/Category";

export type {
  CoreCategory as Category,
  RetryableInfo,
  AllKeys,
  ExtractAll,
} from "distilled-core/Category";
