import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs/acme.json (from RFC 8555). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { AcmeProtocol, type AcmeOpError, type AcmeOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { AcmeOpError, AcmeOpContext };

/** The request specified an account that does not exist. */
export class AcmeAccountDoesNotExist
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeAccountDoesNotExist>()("AcmeAccountDoesNotExist", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:accountDoesNotExist$" } }],
  ) {}

/** The request specified a certificate to be revoked that has already been revoked. */
export class AcmeAlreadyRevoked
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeAlreadyRevoked>()("AcmeAlreadyRevoked", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:alreadyRevoked$" } }],
  ) {}

/** The CSR is unacceptable (e.g., due to a short key). */
export class AcmeBadCsr
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeBadCsr>()("AcmeBadCsr", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:badCSR$" } }],
  ) {}

/** The client sent an unacceptable anti-replay nonce. */
export class AcmeBadNonce
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeBadNonce>()("AcmeBadNonce", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:badNonce$" } }],
  ) {}

/** The JWS was signed by a public key the server does not support. */
export class AcmeBadPublicKey
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeBadPublicKey>()("AcmeBadPublicKey", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:badPublicKey$" } }],
  ) {}

/** The revocation reason provided is not allowed by the server. */
export class AcmeBadRevocationReason
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeBadRevocationReason>()("AcmeBadRevocationReason", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:badRevocationReason$" } }],
  ) {}

/** The JWS was signed with an algorithm the server does not support. */
export class AcmeBadSignatureAlgorithm
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeBadSignatureAlgorithm>()("AcmeBadSignatureAlgorithm", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:badSignatureAlgorithm$" } }],
  ) {}

/** Certification Authority Authorization (CAA) records forbid the CA from issuing a certificate. */
export class AcmeCaa
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeCaa>()("AcmeCaa", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:caa$" } }],
  ) {}

/** The server could not connect to validation target. */
export class AcmeConnection
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeConnection>()("AcmeConnection", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:connection$" } }],
  ) {}

/** There was a problem with a DNS query during identifier validation. */
export class AcmeDns
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeDns>()("AcmeDns", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:dns$" } }],
  ) {}

/** The request must include a value for the "externalAccountBinding" field. */
export class AcmeExternalAccountRequired
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeExternalAccountRequired>()("AcmeExternalAccountRequired", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:externalAccountRequired$" } }],
  ) {}

/** Response received didn't match the challenge's requirements. */
export class AcmeIncorrectResponse
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeIncorrectResponse>()("AcmeIncorrectResponse", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:incorrectResponse$" } }],
  ) {}

/** A contact URL for an account was invalid. */
export class AcmeInvalidContact
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeInvalidContact>()("AcmeInvalidContact", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:invalidContact$" } }],
  ) {}

/** The request message was malformed. */
export class AcmeMalformed
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeMalformed>()("AcmeMalformed", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:malformed$" } }],
  ) {}

/** The request attempted to finalize an order that is not ready to be finalized. */
export class AcmeOrderNotReady
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeOrderNotReady>()("AcmeOrderNotReady", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:orderNotReady$" } }],
  ) {}

/** The request exceeds a rate limit. */
export class AcmeRateLimited
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeRateLimited>()("AcmeRateLimited", {
      retryAfter: S.optional(S.Duration),
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }).pipe(C.withThrottlingError, C.withRetryableError),
    [{ message: { matches: "^urn:ietf:params:acme:error:rateLimited$" } }],
  ) {}

/** The server will not issue certificates for the identifier. */
export class AcmeRejectedIdentifier
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeRejectedIdentifier>()("AcmeRejectedIdentifier", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:rejectedIdentifier$" } }],
  ) {}

/** The server experienced an internal error. */
export class AcmeServerInternal
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeServerInternal>()("AcmeServerInternal", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }).pipe(C.withRetryableError),
    [{ message: { matches: "^urn:ietf:params:acme:error:serverInternal$" } }],
  ) {}

/** The server received a TLS error during validation. */
export class AcmeTls
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeTls>()("AcmeTls", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:tls$" } }],
  ) {}

/** The client lacks sufficient authorization. */
export class AcmeUnauthorized
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeUnauthorized>()("AcmeUnauthorized", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:unauthorized$" } }],
  ) {}

/** A contact URL for an account used an unsupported protocol scheme. */
export class AcmeUnsupportedContact
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeUnsupportedContact>()("AcmeUnsupportedContact", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:unsupportedContact$" } }],
  ) {}

/** An identifier is of an unsupported type. */
export class AcmeUnsupportedIdentifier
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeUnsupportedIdentifier>()("AcmeUnsupportedIdentifier", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:unsupportedIdentifier$" } }],
  ) {}

/** Visit the "instance" URL and take actions specified there. */
export class AcmeUserActionRequired
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<AcmeUserActionRequired>()("AcmeUserActionRequired", {
      code: S.Number,
      message: S.String,
      type: S.String,
      detail: S.optional(S.String),
    }),
    [{ message: { matches: "^urn:ietf:params:acme:error:userActionRequired$" } }],
  ) {}

export interface DeactivateAuthorizationRequest {
  /** Absolute URL of the resource, as returned by the CA. */
  url: string;
  /** Always `deactivated`. */
  status: string;
}
export const DeactivateAuthorizationRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.String.pipe(T.Label()),
    status: S.String,
  }).pipe(T.Http({ method: "POST", uri: "/authz/{url}/deactivate", code: 200 })),
).annotate({
  identifier: "DeactivateAuthorizationRequest",
}) as any as S.Schema<DeactivateAuthorizationRequest>;

export interface Identifier {
  /** The type of identifier. This document defines the "dns" identifier type. See the registry defined in Section 9.7.7 for any others. */
  type: string;
  /** The identifier itself. */
  value: string;
}
export const Identifier = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.String,
    value: S.String,
  }),
).annotate({ identifier: "Identifier" }) as any as S.Schema<Identifier>;

export interface Subproblem {
  /** The error type URI. */
  type?: string;
  /** A human-readable explanation. */
  detail?: string;
  /** The identifier this subproblem is about. */
  identifier?: Identifier;
}
export const Subproblem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.optional(S.String),
    detail: S.optional(S.String),
    identifier: S.optional(Identifier),
  }),
).annotate({ identifier: "Subproblem" }) as any as S.Schema<Subproblem>;

export type ProblemSubproblemsList = Array<Subproblem>;
export const ProblemSubproblemsList = /*@__PURE__*/ S.Array(
  Subproblem,
) as any as S.Schema<ProblemSubproblemsList>;

/** RFC 7807 problem document (RFC 8555 §6.7). */
export interface Problem {
  /** The error type URI, e.g. `urn:ietf:params:acme:error:malformed`. */
  type?: string;
  /** A human-readable explanation. */
  detail?: string;
  /** The HTTP status code. */
  status?: number;
  /** A URI reference identifying this occurrence. */
  instance?: string;
  /** The identifier the error relates to. */
  identifier?: Identifier;
  /** Errors for individual identifiers (RFC 8555 §6.7.1). */
  subproblems?: ProblemSubproblemsList;
}
export const Problem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.optional(S.String),
    detail: S.optional(S.String),
    status: S.optional(S.Number),
    instance: S.optional(S.String),
    identifier: S.optional(Identifier),
    subproblems: S.optional(ProblemSubproblemsList),
  }),
).annotate({ identifier: "Problem" }) as any as S.Schema<Problem>;

/** RFC 8555 §8 */
export interface Challenge {
  /** The type of challenge encoded in the object. */
  type: string;
  /** The URL to which a response can be posted. */
  url: string;
  /** The status of this challenge. Possible values are "pending", "processing", "valid", and "invalid" (see Section 7.1.6). */
  status: string;
  /** The time at which the server validated this challenge, encoded in the format specified in [RFC3339]. This field is REQUIRED if the "status" field is "valid". */
  validated?: string;
  /** A random value that uniquely identifies the challenge. This value MUST have at least 128 bits of entropy. It MUST NOT contain any characters outside the base64url alphabet and MUST NOT include base64 padding characters ("="). See [RFC4086] for additional information on randomness requirements. */
  token?: string;
  /** Error that occurred while the server was validating the challenge, if any, structured as a problem document [RFC7807]. Multiple errors can be indicated by using subproblems Section 6.7.1. A challenge object with an error MUST have status equal to "invalid". */
  error?: Problem;
}
export const Challenge = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.String,
    url: S.String,
    status: S.String,
    validated: S.optional(S.String),
    token: S.optional(S.String),
    error: S.optional(Problem),
  }),
).annotate({ identifier: "Challenge" }) as any as S.Schema<Challenge>;

export type AuthorizationChallengesList = Array<Challenge>;
export const AuthorizationChallengesList = /*@__PURE__*/ S.Array(
  Challenge,
) as any as S.Schema<AuthorizationChallengesList>;

/** RFC 8555 §7.1.4 */
export interface Authorization {
  /** The identifier that the account is authorized to represent. */
  identifier: Identifier;
  /** The status of this authorization. Possible values are "pending", "valid", "invalid", "deactivated", "expired", and "revoked". See Section 7.1.6. */
  status: string;
  /** The timestamp after which the server will consider this authorization invalid, encoded in the format specified in [RFC3339]. This field is REQUIRED for objects with "valid" in the "status" field. */
  expires?: string;
  /** For pending authorizations, the challenges that the client can fulfill in order to prove possession of the identifier. For valid authorizations, the challenge that was validated. For invalid authorizations, the challenge that was attempted and failed. Each array entry is an object with parameters required to validate the challenge. A client should attempt to fulfill one of these challenges, and a server should consider any one of the challenges sufficient to make the authorization valid. */
  challenges: AuthorizationChallengesList;
  /** This field MUST be present and true for authorizations created as a result of a newOrder request containing a DNS identifier with a value that was a wildcard domain name. For other authorizations, it MUST be absent. Wildcard domain names are described in Section 7.1.3. */
  wildcard?: boolean;
}
export const Authorization = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    identifier: Identifier,
    status: S.String,
    expires: S.optional(S.String),
    challenges: AuthorizationChallengesList,
    wildcard: S.optional(S.Boolean),
  }),
).annotate({ identifier: "Authorization" }) as any as S.Schema<Authorization>;

export interface DownloadCertificateRequest {
  /** Absolute URL of the resource, as returned by the CA. */
  url: string;
}
export const DownloadCertificateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "POST", uri: "/cert/{url}", code: 200 })),
).annotate({
  identifier: "DownloadCertificateRequest",
}) as any as S.Schema<DownloadCertificateRequest>;

/** Alternate chain URLs from `Link: <url>;rel="alternate"` headers. */
export type CertificateChainAlternatesList = Array<string>;
export const CertificateChainAlternatesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CertificateChainAlternatesList>;

export interface CertificateChain {
  /** PEM certificate chain (`application/pem-certificate-chain`), leaf first. */
  chain: string;
  /** Alternate chain URLs from `Link: <url>;rel="alternate"` headers. */
  alternates?: CertificateChainAlternatesList;
}
export const CertificateChain = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    chain: S.String,
    alternates: S.optional(CertificateChainAlternatesList),
  }),
).annotate({ identifier: "CertificateChain" }) as any as S.Schema<CertificateChain>;

export interface FinalizeOrderRequest {
  /** Absolute URL of the resource, as returned by the CA. */
  url: string;
  /** A CSR encoding the parameters for the certificate being requested [RFC2986]. The CSR is sent in the base64url-encoded version of the DER format. (Note: Because this field uses base64url, and does not include headers, it is different from PEM.) */
  csr: string;
}
export const FinalizeOrderRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.String.pipe(T.Label()),
    csr: S.String,
  }).pipe(T.Http({ method: "POST", uri: "/finalize/{url}", code: 200 })),
).annotate({ identifier: "FinalizeOrderRequest" }) as any as S.Schema<FinalizeOrderRequest>;

export type OrderResponseIdentifiersList = Array<Identifier>;
export const OrderResponseIdentifiersList = /*@__PURE__*/ S.Array(
  Identifier,
) as any as S.Schema<OrderResponseIdentifiersList>;

export type OrderResponseAuthorizationsList = Array<string>;
export const OrderResponseAuthorizationsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<OrderResponseAuthorizationsList>;

/** RFC 8555 §7.1.3, plus the `Location` header as `location`. */
export interface OrderResponse {
  /** The status of this order. Possible values are "pending", "ready", "processing", "valid", and "invalid". See Section 7.1.6. */
  status: string;
  /** The timestamp after which the server will consider this order invalid, encoded in the format specified in [RFC3339]. This field is REQUIRED for objects with "pending" or "valid" in the status field. */
  expires?: string;
  /** An array of identifier objects that the order pertains to. */
  identifiers: OrderResponseIdentifiersList;
  /** The requested value of the notBefore field in the certificate, in the date format defined in [RFC3339]. */
  notBefore?: string;
  /** The requested value of the notAfter field in the certificate, in the date format defined in [RFC3339]. */
  notAfter?: string;
  /** The error that occurred while processing the order, if any. This field is structured as a problem document [RFC7807]. */
  error?: Problem;
  /** For pending orders, the authorizations that the client needs to complete before the requested certificate can be issued (see Section 7.5), including unexpired authorizations that the client has completed in the past for identifiers specified in the order. The authorizations required are dictated by server policy; there may not be a 1:1 relationship between the order identifiers and the authorizations required. For final orders (in the "valid" or "invalid" state), the authorizations that were completed. Each entry is a URL from which an authorization can be fetched with a POST-as-GET request. */
  authorizations: OrderResponseAuthorizationsList;
  /** A URL that a CSR must be POSTed to once all of the order's authorizations are satisfied to finalize the order. The result of a successful finalization will be the population of the certificate URL for the order. */
  finalize: string;
  /** A URL for the certificate that has been issued in response to this order. */
  certificate?: string;
  /** The order URL (`Location` header). */
  location?: string;
}
export const OrderResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status: S.String,
    expires: S.optional(S.String),
    identifiers: OrderResponseIdentifiersList,
    notBefore: S.optional(S.String),
    notAfter: S.optional(S.String),
    error: S.optional(Problem),
    authorizations: OrderResponseAuthorizationsList,
    finalize: S.String,
    certificate: S.optional(S.String),
    location: S.optional(S.String),
  }),
).annotate({ identifier: "OrderResponse" }) as any as S.Schema<OrderResponse>;

export interface GetAuthorizationRequest {
  /** Absolute URL of the resource, as returned by the CA. */
  url: string;
}
export const GetAuthorizationRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "POST", uri: "/authz/{url}", code: 200 })),
).annotate({ identifier: "GetAuthorizationRequest" }) as any as S.Schema<GetAuthorizationRequest>;

export interface GetDirectoryRequest {}
export const GetDirectoryRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/directory", code: 200 })),
).annotate({ identifier: "GetDirectoryRequest" }) as any as S.Schema<GetDirectoryRequest>;

export type DirectoryMetaCaaIdentitiesList = Array<string>;
export const DirectoryMetaCaaIdentitiesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<DirectoryMetaCaaIdentitiesList>;

export interface DirectoryMeta {
  /** A URL identifying the current terms of service. */
  termsOfService?: string;
  /** An HTTP or HTTPS URL locating a website providing more information about the ACME server. */
  website?: string;
  /** The hostnames that the ACME server recognizes as referring to itself for the purposes of CAA record validation as defined in [RFC6844]. Each string MUST represent the same sequence of ASCII code points that the server will expect to see as the "Issuer Domain Name" in a CAA issue or issuewild property tag. This allows clients to determine the correct issuer domain name to use when configuring CAA records. */
  caaIdentities?: DirectoryMetaCaaIdentitiesList;
  /** If this field is present and set to "true", then the CA requires that all newAccount requests include an "externalAccountBinding" field associating the new account with an external account. */
  externalAccountRequired?: boolean;
}
export const DirectoryMeta = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    termsOfService: S.optional(S.String),
    website: S.optional(S.String),
    caaIdentities: S.optional(DirectoryMetaCaaIdentitiesList),
    externalAccountRequired: S.optional(S.Boolean),
  }),
).annotate({ identifier: "DirectoryMeta" }) as any as S.Schema<DirectoryMeta>;

/** RFC 8555 §7.1.1 */
export interface Directory {
  /** URL of the new nonce resource. */
  newNonce: string;
  /** URL of the new account resource. */
  newAccount: string;
  /** URL of the new order resource. */
  newOrder: string;
  /** URL of the new authorization resource. */
  newAuthz?: string;
  /** URL of the revoke certificate resource. */
  revokeCert: string;
  /** URL of the key change resource. */
  keyChange?: string;
  /** Metadata relating to the service provided by the ACME server. */
  meta?: DirectoryMeta;
}
export const Directory = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    newNonce: S.String,
    newAccount: S.String,
    newOrder: S.String,
    newAuthz: S.optional(S.String),
    revokeCert: S.String,
    keyChange: S.optional(S.String),
    meta: S.optional(DirectoryMeta),
  }),
).annotate({ identifier: "Directory" }) as any as S.Schema<Directory>;

export interface GetOrderRequest {
  /** Absolute URL of the resource, as returned by the CA. */
  url: string;
}
export const GetOrderRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "POST", uri: "/order/{url}", code: 200 })),
).annotate({ identifier: "GetOrderRequest" }) as any as S.Schema<GetOrderRequest>;

export type NewAccountRequestContactList = Array<string>;
export const NewAccountRequestContactList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<NewAccountRequestContactList>;

/** A JWS binding this account to an existing CA account (RFC 8555 §7.3.4). The protocol builds it from the credentials' EAB key id and HMAC key. */
export interface ExternalAccountBinding {
  protected: string;
  payload: string;
  signature: string;
}
export const ExternalAccountBinding = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    protected: S.String,
    payload: S.String,
    signature: S.String,
  }),
).annotate({ identifier: "ExternalAccountBinding" }) as any as S.Schema<ExternalAccountBinding>;

export interface NewAccountRequest {
  /** Same meaning as the corresponding server field defined in Section 7.1.2. */
  contact?: NewAccountRequestContactList;
  /** Same meaning as the corresponding server field defined in Section 7.1.2. */
  termsOfServiceAgreed?: boolean;
  /** If this field is present with the value "true", then the server MUST NOT create a new account if one does not already exist. This allows a client to look up an account URL based on an account key (see Section 7.3.1). */
  onlyReturnExisting?: boolean;
  /** Same meaning as the corresponding server field defined in Section 7.1.2 */
  externalAccountBinding?: ExternalAccountBinding;
}
export const NewAccountRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    contact: S.optional(NewAccountRequestContactList),
    termsOfServiceAgreed: S.optional(S.Boolean),
    onlyReturnExisting: S.optional(S.Boolean),
    externalAccountBinding: S.optional(ExternalAccountBinding),
  }).pipe(T.Http({ method: "POST", uri: "/newAccount", code: 200 })),
).annotate({ identifier: "NewAccountRequest" }) as any as S.Schema<NewAccountRequest>;

export type AccountResponseContactList = Array<string>;
export const AccountResponseContactList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<AccountResponseContactList>;

/** RFC 8555 §7.1.2, plus the `Location` header as `location`. */
export interface AccountResponse {
  /** The status of this account. Possible values are "valid", "deactivated", and "revoked". The value "deactivated" should be used to indicate client-initiated deactivation whereas "revoked" should be used to indicate server- initiated deactivation. See Section 7.1.6. */
  status: string;
  /** An array of URLs that the server can use to contact the client for issues related to this account. For example, the server may wish to notify the client about server-initiated revocation or certificate expiration. For information on supported URL schemes, see Section 7.3. */
  contact?: AccountResponseContactList;
  /** Including this field in a newAccount request, with a value of true, indicates the client's agreement with the terms of service. This field cannot be updated by the client. */
  termsOfServiceAgreed?: boolean;
  /** A URL from which a list of orders submitted by this account can be fetched via a POST-as-GET request, as described in Section 7.1.2.1. */
  orders?: string;
  /** The account URL (`Location` header); the `kid` for every later request. */
  location?: string;
}
export const AccountResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status: S.String,
    contact: S.optional(AccountResponseContactList),
    termsOfServiceAgreed: S.optional(S.Boolean),
    orders: S.optional(S.String),
    location: S.optional(S.String),
  }),
).annotate({ identifier: "AccountResponse" }) as any as S.Schema<AccountResponse>;

export interface NewNonceRequest {}
export const NewNonceRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/newNonce", code: 200 })),
).annotate({ identifier: "NewNonceRequest" }) as any as S.Schema<NewNonceRequest>;

export interface NonceResponse {
  /** The `Replay-Nonce` header. */
  replayNonce: string;
}
export const NonceResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    replayNonce: S.String,
  }),
).annotate({ identifier: "NonceResponse" }) as any as S.Schema<NonceResponse>;

export type NewOrderRequestIdentifiersList = Array<Identifier>;
export const NewOrderRequestIdentifiersList = /*@__PURE__*/ S.Array(
  Identifier,
) as any as S.Schema<NewOrderRequestIdentifiersList>;

export interface NewOrderRequest {
  /** An array of identifier objects that the client wishes to submit an order for. */
  identifiers: NewOrderRequestIdentifiersList;
  /** The requested value of the notBefore field in the certificate, in the date format defined in [RFC3339]. */
  notBefore?: string;
  /** The requested value of the notAfter field in the certificate, in the date format defined in [RFC3339]. */
  notAfter?: string;
}
export const NewOrderRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    identifiers: NewOrderRequestIdentifiersList,
    notBefore: S.optional(S.String),
    notAfter: S.optional(S.String),
  }).pipe(T.Http({ method: "POST", uri: "/newOrder", code: 200 })),
).annotate({ identifier: "NewOrderRequest" }) as any as S.Schema<NewOrderRequest>;

export interface RespondChallengeRequest {
  /** Absolute URL of the resource, as returned by the CA. */
  url: string;
}
export const RespondChallengeRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "POST", uri: "/challenge/{url}", code: 200 })),
).annotate({ identifier: "RespondChallengeRequest" }) as any as S.Schema<RespondChallengeRequest>;

export interface RevokeCertificateRequest {
  /** The certificate to be revoked, in the base64url-encoded version of the DER format. (Note: Because this field uses base64url, and does not include headers, it is different from PEM.) */
  certificate: string;
  /** One of the revocation reasonCodes defined in Section 5.3.1 of [RFC5280] to be used when generating OCSP responses and CRLs. If this field is not set, the server SHOULD omit the reasonCode CRL entry extension when generating OCSP responses and CRLs. The server MAY disallow a subset of reasonCodes from being used by the user. If a request contains a disallowed reasonCode, then the server MUST reject it with the error type "urn:ietf:params:acme:error:badRevocationReason". The problem document detail SHOULD indicate which reasonCodes are allowed. */
  reason?: number;
}
export const RevokeCertificateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    certificate: S.String,
    reason: S.optional(S.Number),
  }).pipe(T.Http({ method: "POST", uri: "/revokeCert", code: 200 })),
).annotate({ identifier: "RevokeCertificateRequest" }) as any as S.Schema<RevokeCertificateRequest>;

export interface RevokeCertificateResponse {}
export const RevokeCertificateResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "RevokeCertificateResponse",
}) as any as S.Schema<RevokeCertificateResponse>;

export type UpdateAccountRequestContactList = Array<string>;
export const UpdateAccountRequestContactList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<UpdateAccountRequestContactList>;

export interface UpdateAccountRequest {
  /** Absolute URL of the resource, as returned by the CA. */
  url: string;
  /** An array of URLs that the server can use to contact the client for issues related to this account. For example, the server may wish to notify the client about server-initiated revocation or certificate expiration. For information on supported URL schemes, see Section 7.3. */
  contact?: UpdateAccountRequestContactList;
  /** `deactivated` to deactivate the account (RFC 8555 §7.3.6). */
  status?: string;
}
export const UpdateAccountRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.String.pipe(T.Label()),
    contact: S.optional(UpdateAccountRequestContactList),
    status: S.optional(S.String),
  }).pipe(T.Http({ method: "POST", uri: "/account/{url}", code: 200 })),
).annotate({ identifier: "UpdateAccountRequest" }) as any as S.Schema<UpdateAccountRequest>;

export type DeactivateAuthorizationError =
  | AcmeAccountDoesNotExist
  | AcmeBadNonce
  | AcmeMalformed
  | AcmeRateLimited
  | AcmeServerInternal
  | AcmeUnauthorized
  | AcmeOpError;
/** Deactivate the authorization at `url` */
export const deactivateAuthorization: API.OperationMethod<
  DeactivateAuthorizationRequest,
  Authorization,
  DeactivateAuthorizationError,
  AcmeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeactivateAuthorizationRequest,
  output: Authorization,
  errors: [
    AcmeAccountDoesNotExist,
    AcmeBadNonce,
    AcmeMalformed,
    AcmeRateLimited,
    AcmeServerInternal,
    AcmeUnauthorized,
  ],
  protocol: AcmeProtocol,
  retry: Retry.Retry,
}));

export type DownloadCertificateError =
  | AcmeAccountDoesNotExist
  | AcmeBadNonce
  | AcmeMalformed
  | AcmeRateLimited
  | AcmeServerInternal
  | AcmeUnauthorized
  | AcmeOpError;
/** Download the PEM certificate chain at `url` (POST-as-GET) */
export const downloadCertificate: API.OperationMethod<
  DownloadCertificateRequest,
  CertificateChain,
  DownloadCertificateError,
  AcmeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DownloadCertificateRequest,
  output: CertificateChain,
  errors: [
    AcmeAccountDoesNotExist,
    AcmeBadNonce,
    AcmeMalformed,
    AcmeRateLimited,
    AcmeServerInternal,
    AcmeUnauthorized,
  ],
  protocol: AcmeProtocol,
  retry: Retry.Retry,
}));

export type FinalizeOrderError =
  | AcmeAccountDoesNotExist
  | AcmeBadCsr
  | AcmeBadNonce
  | AcmeMalformed
  | AcmeOrderNotReady
  | AcmeRateLimited
  | AcmeServerInternal
  | AcmeUnauthorized
  | AcmeOpError;
/** Submit the CSR to the order's finalize URL */
export const finalizeOrder: API.OperationMethod<
  FinalizeOrderRequest,
  OrderResponse,
  FinalizeOrderError,
  AcmeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: FinalizeOrderRequest,
  output: OrderResponse,
  errors: [
    AcmeAccountDoesNotExist,
    AcmeBadCsr,
    AcmeBadNonce,
    AcmeMalformed,
    AcmeOrderNotReady,
    AcmeRateLimited,
    AcmeServerInternal,
    AcmeUnauthorized,
  ],
  protocol: AcmeProtocol,
  retry: Retry.Retry,
}));

export type GetAuthorizationError =
  | AcmeAccountDoesNotExist
  | AcmeBadNonce
  | AcmeMalformed
  | AcmeRateLimited
  | AcmeServerInternal
  | AcmeUnauthorized
  | AcmeOpError;
/** Fetch the authorization at `url` (POST-as-GET) */
export const getAuthorization: API.OperationMethod<
  GetAuthorizationRequest,
  Authorization,
  GetAuthorizationError,
  AcmeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetAuthorizationRequest,
  output: Authorization,
  errors: [
    AcmeAccountDoesNotExist,
    AcmeBadNonce,
    AcmeMalformed,
    AcmeRateLimited,
    AcmeServerInternal,
    AcmeUnauthorized,
  ],
  protocol: AcmeProtocol,
  retry: Retry.Retry,
}));

export type GetDirectoryError = AcmeOpError;
/** Fetch the CA's directory of resource URLs */
export const getDirectory: API.OperationMethod<
  GetDirectoryRequest,
  Directory,
  GetDirectoryError,
  AcmeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetDirectoryRequest,
  output: Directory,
  errors: [],
  protocol: AcmeProtocol,
  retry: Retry.Retry,
}));

export type GetOrderError =
  | AcmeAccountDoesNotExist
  | AcmeBadNonce
  | AcmeMalformed
  | AcmeRateLimited
  | AcmeServerInternal
  | AcmeUnauthorized
  | AcmeOpError;
/** Fetch the order at `url` (POST-as-GET) */
export const getOrder: API.OperationMethod<
  GetOrderRequest,
  OrderResponse,
  GetOrderError,
  AcmeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetOrderRequest,
  output: OrderResponse,
  errors: [
    AcmeAccountDoesNotExist,
    AcmeBadNonce,
    AcmeMalformed,
    AcmeRateLimited,
    AcmeServerInternal,
    AcmeUnauthorized,
  ],
  protocol: AcmeProtocol,
  retry: Retry.Retry,
}));

export type NewAccountError =
  | AcmeAccountDoesNotExist
  | AcmeBadNonce
  | AcmeBadPublicKey
  | AcmeBadSignatureAlgorithm
  | AcmeExternalAccountRequired
  | AcmeInvalidContact
  | AcmeMalformed
  | AcmeRateLimited
  | AcmeServerInternal
  | AcmeUnauthorized
  | AcmeUnsupportedContact
  | AcmeUserActionRequired
  | AcmeOpError;
/** Create an account, or find the existing account for this key */
export const newAccount: API.OperationMethod<
  NewAccountRequest,
  AccountResponse,
  NewAccountError,
  AcmeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: NewAccountRequest,
  output: AccountResponse,
  errors: [
    AcmeAccountDoesNotExist,
    AcmeBadNonce,
    AcmeBadPublicKey,
    AcmeBadSignatureAlgorithm,
    AcmeExternalAccountRequired,
    AcmeInvalidContact,
    AcmeMalformed,
    AcmeRateLimited,
    AcmeServerInternal,
    AcmeUnauthorized,
    AcmeUnsupportedContact,
    AcmeUserActionRequired,
  ],
  protocol: AcmeProtocol,
  retry: Retry.Retry,
}));

export type NewNonceError = AcmeOpError;
/** Get a fresh anti-replay nonce (the `Replay-Nonce` header) */
export const newNonce: API.OperationMethod<
  NewNonceRequest,
  NonceResponse,
  NewNonceError,
  AcmeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: NewNonceRequest,
  output: NonceResponse,
  errors: [],
  protocol: AcmeProtocol,
  retry: Retry.Retry,
}));

export type NewOrderError =
  | AcmeAccountDoesNotExist
  | AcmeBadNonce
  | AcmeMalformed
  | AcmeRateLimited
  | AcmeRejectedIdentifier
  | AcmeServerInternal
  | AcmeUnauthorized
  | AcmeUnsupportedIdentifier
  | AcmeUserActionRequired
  | AcmeOpError;
/** Create an order for a set of identifiers */
export const newOrder: API.OperationMethod<
  NewOrderRequest,
  OrderResponse,
  NewOrderError,
  AcmeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: NewOrderRequest,
  output: OrderResponse,
  errors: [
    AcmeAccountDoesNotExist,
    AcmeBadNonce,
    AcmeMalformed,
    AcmeRateLimited,
    AcmeRejectedIdentifier,
    AcmeServerInternal,
    AcmeUnauthorized,
    AcmeUnsupportedIdentifier,
    AcmeUserActionRequired,
  ],
  protocol: AcmeProtocol,
  retry: Retry.Retry,
}));

export type RespondChallengeError =
  | AcmeAccountDoesNotExist
  | AcmeBadNonce
  | AcmeCaa
  | AcmeConnection
  | AcmeDns
  | AcmeIncorrectResponse
  | AcmeMalformed
  | AcmeRateLimited
  | AcmeServerInternal
  | AcmeTls
  | AcmeUnauthorized
  | AcmeOpError;
/** Tell the CA the challenge at `url` is ready to be validated */
export const respondChallenge: API.OperationMethod<
  RespondChallengeRequest,
  Challenge,
  RespondChallengeError,
  AcmeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: RespondChallengeRequest,
  output: Challenge,
  errors: [
    AcmeAccountDoesNotExist,
    AcmeBadNonce,
    AcmeCaa,
    AcmeConnection,
    AcmeDns,
    AcmeIncorrectResponse,
    AcmeMalformed,
    AcmeRateLimited,
    AcmeServerInternal,
    AcmeTls,
    AcmeUnauthorized,
  ],
  protocol: AcmeProtocol,
  retry: Retry.Retry,
}));

export type RevokeCertificateError =
  | AcmeAccountDoesNotExist
  | AcmeAlreadyRevoked
  | AcmeBadNonce
  | AcmeBadRevocationReason
  | AcmeMalformed
  | AcmeRateLimited
  | AcmeServerInternal
  | AcmeUnauthorized
  | AcmeOpError;
/** Revoke a certificate */
export const revokeCertificate: API.OperationMethod<
  RevokeCertificateRequest,
  RevokeCertificateResponse,
  RevokeCertificateError,
  AcmeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: RevokeCertificateRequest,
  output: RevokeCertificateResponse,
  errors: [
    AcmeAccountDoesNotExist,
    AcmeAlreadyRevoked,
    AcmeBadNonce,
    AcmeBadRevocationReason,
    AcmeMalformed,
    AcmeRateLimited,
    AcmeServerInternal,
    AcmeUnauthorized,
  ],
  protocol: AcmeProtocol,
  retry: Retry.Retry,
}));

export type UpdateAccountError =
  | AcmeAccountDoesNotExist
  | AcmeBadNonce
  | AcmeInvalidContact
  | AcmeMalformed
  | AcmeRateLimited
  | AcmeServerInternal
  | AcmeUnauthorized
  | AcmeUnsupportedContact
  | AcmeOpError;
/** Update (or deactivate) the account at `url` */
export const updateAccount: API.OperationMethod<
  UpdateAccountRequest,
  AccountResponse,
  UpdateAccountError,
  AcmeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateAccountRequest,
  output: AccountResponse,
  errors: [
    AcmeAccountDoesNotExist,
    AcmeBadNonce,
    AcmeInvalidContact,
    AcmeMalformed,
    AcmeRateLimited,
    AcmeServerInternal,
    AcmeUnauthorized,
    AcmeUnsupportedContact,
  ],
  protocol: AcmeProtocol,
  retry: Retry.Retry,
}));
