import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/api-v1-native.json + api-v1-stable.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { paginateRelay } from "../pagination.ts";
import { WhopProtocol, type WhopOpError, type WhopOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { WhopOpError, WhopOpContext };

export class Conflict
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Conflict>()("Conflict", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withConflictError),
    [{ status: 409 }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

export type CreateAdConversionValueRuleRequestAdjustmentType = "fixed" | "percentage";
export const CreateAdConversionValueRuleRequestAdjustmentType = S.String;

export type CreateAdConversionValueRuleRequestEventsItemEventName =
  | "purchase"
  | "subscribe"
  | "start_trial"
  | "lead"
  | "complete_registration"
  | "submit_application"
  | "schedule"
  | "contact"
  | "view_content"
  | "add_to_cart"
  | "custom";
export const CreateAdConversionValueRuleRequestEventsItemEventName = S.String;

export interface CreateAdConversionValueRuleRequestEventsItem {
  /** Exact custom event name. Required for custom events; null for standard events. */
  custom_name?: string | null;
  event_name: CreateAdConversionValueRuleRequestEventsItemEventName | (string & {});
}
export const CreateAdConversionValueRuleRequestEventsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    custom_name: S.optional(S.NullOr(S.String)),
    event_name: CreateAdConversionValueRuleRequestEventsItemEventName,
  }),
).annotate({
  identifier: "CreateAdConversionValueRuleRequestEventsItem",
}) as any as S.Schema<CreateAdConversionValueRuleRequestEventsItem>;

/** Events adjusted on every selected target. Every platform must support every selected event. */
export type CreateAdConversionValueRuleRequestEventsList =
  Array<CreateAdConversionValueRuleRequestEventsItem>;
export const CreateAdConversionValueRuleRequestEventsList = /*@__PURE__*/ S.Array(
  CreateAdConversionValueRuleRequestEventsItem,
) as any as S.Schema<CreateAdConversionValueRuleRequestEventsList>;

export interface CreateAdConversionValueRuleRequestFixedValue {
  /** Decimal amount with at most 2 decimal places. Fixed values must be greater than 0 and at most 99999999.99. */
  amount: string;
  currency: string;
}
export const CreateAdConversionValueRuleRequestFixedValue = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    amount: S.String,
    currency: S.String,
  }),
).annotate({
  identifier: "CreateAdConversionValueRuleRequestFixedValue",
}) as any as S.Schema<CreateAdConversionValueRuleRequestFixedValue>;

export type CreateAdConversionValueRuleRequestMetadataMap = { [key: string]: string | undefined };
export const CreateAdConversionValueRuleRequestMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<CreateAdConversionValueRuleRequestMetadataMap>;

/** Exact IDs of active rules whose overlapping selections will be replaced. Other selections keep their values; remaining selections may split into separate rules. Broader rules remain as fallbacks for other items. Stale or incomplete conflict selections fail. */
export type CreateAdConversionValueRuleRequestReplaceRuleIdsList = Array<string>;
export const CreateAdConversionValueRuleRequestReplaceRuleIdsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreateAdConversionValueRuleRequestReplaceRuleIdsList>;

/** Initial rule status. Defaults to active. */
export type CreateAdConversionValueRuleRequestStatus = "active" | "paused";
export const CreateAdConversionValueRuleRequestStatus = S.String;

export type CreateAdConversionValueRuleRequestTargetsItemPlatform = "tiktok" | "meta" | "google";
export const CreateAdConversionValueRuleRequestTargetsItemPlatform = S.String;

export type CreateAdConversionValueRuleRequestTargetsItemScope =
  | "business"
  | "campaign"
  | "ad_group"
  | "ad";
export const CreateAdConversionValueRuleRequestTargetsItemScope = S.String;

export interface CreateAdConversionValueRuleRequestTargetsItem {
  platform: CreateAdConversionValueRuleRequestTargetsItemPlatform | (string & {});
  /** Campaign, ad group, or ad ID. Null for a business target. */
  resource_id?: string | null;
  scope: CreateAdConversionValueRuleRequestTargetsItemScope | (string & {});
}
export const CreateAdConversionValueRuleRequestTargetsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    platform: CreateAdConversionValueRuleRequestTargetsItemPlatform,
    resource_id: S.optional(S.NullOr(S.String)),
    scope: CreateAdConversionValueRuleRequestTargetsItemScope,
  }),
).annotate({
  identifier: "CreateAdConversionValueRuleRequestTargetsItem",
}) as any as S.Schema<CreateAdConversionValueRuleRequestTargetsItem>;

/** Targets sharing one scope. Every selected event applies to every target. At most 500 target and event combinations. */
export type CreateAdConversionValueRuleRequestTargetsList =
  Array<CreateAdConversionValueRuleRequestTargetsItem>;
export const CreateAdConversionValueRuleRequestTargetsList = /*@__PURE__*/ S.Array(
  CreateAdConversionValueRuleRequestTargetsItem,
) as any as S.Schema<CreateAdConversionValueRuleRequestTargetsList>;

export interface CreateAdConversionValueRuleRequest {
  /** Business that owns the rule. */
  account_id: string;
  adjustment_type: CreateAdConversionValueRuleRequestAdjustmentType | (string & {});
  /** Events adjusted on every selected target. Every platform must support every selected event. */
  events: CreateAdConversionValueRuleRequestEventsList;
  fixed_value?: CreateAdConversionValueRuleRequestFixedValue | null;
  metadata?: CreateAdConversionValueRuleRequestMetadataMap;
  /** Signed percent change from negative 100 to 10000. The sent value cannot go below zero. */
  percentage_change?: number | null;
  /** Exact IDs of active rules whose overlapping selections will be replaced. Other selections keep their values; remaining selections may split into separate rules. Broader rules remain as fallbacks for other items. Stale or incomplete conflict selections fail. */
  replace_rule_ids?: CreateAdConversionValueRuleRequestReplaceRuleIdsList;
  /** Initial rule status. Defaults to active. */
  status?: CreateAdConversionValueRuleRequestStatus | (string & {});
  /** Targets sharing one scope. Every selected event applies to every target. At most 500 target and event combinations. */
  targets: CreateAdConversionValueRuleRequestTargetsList;
  /** A unique key that makes this request safe to retry. See [Idempotent requests](https://docs.whop.com/developer/api/idempotency). */
  idempotency_key?: string;
}
export const CreateAdConversionValueRuleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.String,
    adjustment_type: CreateAdConversionValueRuleRequestAdjustmentType,
    events: CreateAdConversionValueRuleRequestEventsList,
    fixed_value: S.optional(S.NullOr(CreateAdConversionValueRuleRequestFixedValue)),
    metadata: S.optional(CreateAdConversionValueRuleRequestMetadataMap),
    percentage_change: S.optional(S.NullOr(S.Number)),
    replace_rule_ids: S.optional(CreateAdConversionValueRuleRequestReplaceRuleIdsList),
    status: S.optional(CreateAdConversionValueRuleRequestStatus),
    targets: CreateAdConversionValueRuleRequestTargetsList,
    idempotency_key: S.optional(S.String.pipe(T.Header("Idempotency-Key"))),
  }).pipe(T.Http({ method: "POST", uri: "/ad_conversion_value_rules", code: 200 })),
).annotate({
  identifier: "CreateAdConversionValueRuleRequest",
}) as any as S.Schema<CreateAdConversionValueRuleRequest>;

/** Set a fixed amount or change the original value by a signed percentage. */
export type AdConversionValueRuleAdjustmentType = "fixed" | "percentage";
export const AdConversionValueRuleAdjustmentType = S.String;

/** Event to adjust. Purchase includes Whop purchases and external purchase events. */
export type AdConversionValueRuleEventEventName =
  | "purchase"
  | "subscribe"
  | "start_trial"
  | "lead"
  | "complete_registration"
  | "submit_application"
  | "schedule"
  | "contact"
  | "view_content"
  | "add_to_cart"
  | "custom";
export const AdConversionValueRuleEventEventName = S.String;

export interface AdConversionValueRuleEvent {
  /** Exact custom event name. Null for standard events. */
  custom_name: string | null;
  /** Event to adjust. Purchase includes Whop purchases and external purchase events. */
  event_name: AdConversionValueRuleEventEventName;
}
export const AdConversionValueRuleEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    custom_name: S.NullOr(S.String),
    event_name: AdConversionValueRuleEventEventName,
  }),
).annotate({
  identifier: "AdConversionValueRuleEvent",
}) as any as S.Schema<AdConversionValueRuleEvent>;

export type AdConversionValueRuleEventsList = Array<AdConversionValueRuleEvent>;
export const AdConversionValueRuleEventsList = /*@__PURE__*/ S.Array(
  AdConversionValueRuleEvent,
) as any as S.Schema<AdConversionValueRuleEventsList>;

export interface Money {
  /** The amount in major units, as an exact decimal string — `"10.00"` is ten dollars. A string so no float rounds it in transit. */
  amount: string;
  /** Three-letter ISO 4217 currency code, lowercase. */
  currency: string;
  /** How many decimal places the amount CARRIES — the precision the charge itself runs at. */
  decimals: number;
  /** How many decimal places to SHOW. Usually equal to `decimals`, and deliberately not always: COP is charged in centavos but written in whole pesos, so it is `2` and `0`. Format the number in your own locale using this. */
  display_decimals: number;
}
export const Money = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    amount: S.String,
    currency: S.String,
    decimals: S.Number,
    display_decimals: S.Number,
  }),
).annotate({ identifier: "Money" }) as any as S.Schema<Money>;

/** Whether this rule is active or paused. */
export type AdConversionValueRuleStatus = "active" | "paused";
export const AdConversionValueRuleStatus = S.String;

/** Ad platform that receives the adjusted value. */
export type AdConversionValueRuleTargetPlatform = "tiktok" | "meta" | "google";
export const AdConversionValueRuleTargetPlatform = S.String;

/** Business, campaign, ad group, or ad covered by this target. */
export type AdConversionValueRuleTargetScope = "business" | "campaign" | "ad_group" | "ad";
export const AdConversionValueRuleTargetScope = S.String;

export interface AdConversionValueRuleTarget {
  /** Ad platform that receives the adjusted value. */
  platform: AdConversionValueRuleTargetPlatform;
  /** Selected campaign, ad group, or ad ID. Null for a business target. */
  resource_id: string | null;
  /** Name of the selected item. Null when it is no longer available. */
  resource_title: string | null;
  /** Business, campaign, ad group, or ad covered by this target. */
  scope: AdConversionValueRuleTargetScope;
}
export const AdConversionValueRuleTarget = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    platform: AdConversionValueRuleTargetPlatform,
    resource_id: S.NullOr(S.String),
    resource_title: S.NullOr(S.String),
    scope: AdConversionValueRuleTargetScope,
  }),
).annotate({
  identifier: "AdConversionValueRuleTarget",
}) as any as S.Schema<AdConversionValueRuleTarget>;

export type AdConversionValueRuleTargetsList = Array<AdConversionValueRuleTarget>;
export const AdConversionValueRuleTargetsList = /*@__PURE__*/ S.Array(
  AdConversionValueRuleTarget,
) as any as S.Schema<AdConversionValueRuleTargetsList>;

export interface AdConversionValueRule {
  /** Business that owns this shared, editable rule. */
  account_id: string;
  /** Set a fixed amount or change the original value by a signed percentage. */
  adjustment_type: AdConversionValueRuleAdjustmentType;
  /** When the rule was created, as an ISO 8601 timestamp. */
  created_at: string;
  events: AdConversionValueRuleEventsList;
  /** Amount sent for a fixed rule. Null for a percentage rule. */
  fixed_value: Money | null;
  /** Conversion value rule ID, prefixed adcvr_. */
  id: string;
  /** Free-form string keys and values for the caller. */
  metadata: unknown;
  /** Signed percent change: 20 increases by 20%, negative 20 decreases by 20%. The sent value cannot go below zero. Null for a fixed rule. */
  percentage_change: number | null;
  /** Whether this rule is active or paused. */
  status: AdConversionValueRuleStatus;
  targets: AdConversionValueRuleTargetsList;
  /** When the rule was edited, as an ISO 8601 timestamp. */
  updated_at: string;
}
export const AdConversionValueRule = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.String,
    adjustment_type: AdConversionValueRuleAdjustmentType,
    created_at: S.String,
    events: AdConversionValueRuleEventsList,
    fixed_value: S.NullOr(Money),
    id: S.String,
    metadata: S.Unknown,
    percentage_change: S.NullOr(S.Number),
    status: AdConversionValueRuleStatus,
    targets: AdConversionValueRuleTargetsList,
    updated_at: S.String,
  }),
).annotate({ identifier: "AdConversionValueRule" }) as any as S.Schema<AdConversionValueRule>;

export interface DeleteAdConversionValueRuleRequest {
  /** Conversion value rule ID. */
  id: string;
}
export const DeleteAdConversionValueRuleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "DELETE", uri: "/ad_conversion_value_rules/{id}", code: 200 })),
).annotate({
  identifier: "DeleteAdConversionValueRuleRequest",
}) as any as S.Schema<DeleteAdConversionValueRuleRequest>;

export interface DeleteAdConversionValueRuleResponse {
  deleted: boolean;
  id: string;
}
export const DeleteAdConversionValueRuleResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    deleted: S.Boolean,
    id: S.String,
  }),
).annotate({
  identifier: "DeleteAdConversionValueRuleResponse",
}) as any as S.Schema<DeleteAdConversionValueRuleResponse>;

export interface GetAdConversionValueRuleRequest {
  /** Conversion value rule ID. */
  id: string;
}
export const GetAdConversionValueRuleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/ad_conversion_value_rules/{id}", code: 200 })),
).annotate({
  identifier: "GetAdConversionValueRuleRequest",
}) as any as S.Schema<GetAdConversionValueRuleRequest>;

export type ListAdConversionValueRulesRequestStatus = "active" | "paused";
export const ListAdConversionValueRulesRequestStatus = S.String;

export type ListAdConversionValueRulesRequestPlatform = "tiktok" | "meta" | "google";
export const ListAdConversionValueRulesRequestPlatform = S.String;

export type ListAdConversionValueRulesRequestOrder = "created_at";
export const ListAdConversionValueRulesRequestOrder = S.String;

export type ListAdConversionValueRulesRequestDirection = "asc" | "desc";
export const ListAdConversionValueRulesRequestDirection = S.String;

export interface ListAdConversionValueRulesRequest {
  account_id?: string;
  status?: ListAdConversionValueRulesRequestStatus | (string & {});
  platform?: ListAdConversionValueRulesRequestPlatform | (string & {});
  /** Campaign, ad group, or ad ID. Return rules covering this item, its ancestors, or its descendants. */
  resource_id?: string;
  /** Number of results to return from the start of the range. */
  first?: number;
  /** Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page. */
  after?: string;
  /** Number of results to return from the end of the range. */
  last?: number;
  /** Return results before this cursor. Use `page_info.start_cursor` from the previous response to fetch the previous page. */
  before?: string;
  order?: ListAdConversionValueRulesRequestOrder | (string & {});
  direction?: ListAdConversionValueRulesRequestDirection | (string & {});
}
export const ListAdConversionValueRulesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.optional(S.String.pipe(T.Query())),
    status: S.optional(ListAdConversionValueRulesRequestStatus.pipe(T.Query())),
    platform: S.optional(ListAdConversionValueRulesRequestPlatform.pipe(T.Query())),
    resource_id: S.optional(S.String.pipe(T.Query())),
    first: S.optional(S.Number.pipe(T.Query())),
    after: S.optional(S.String.pipe(T.Query())),
    last: S.optional(S.Number.pipe(T.Query())),
    before: S.optional(S.String.pipe(T.Query())),
    order: S.optional(ListAdConversionValueRulesRequestOrder.pipe(T.Query())),
    direction: S.optional(ListAdConversionValueRulesRequestDirection.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/ad_conversion_value_rules", code: 200 })),
).annotate({
  identifier: "ListAdConversionValueRulesRequest",
}) as any as S.Schema<ListAdConversionValueRulesRequest>;

export type ListAdConversionValueRulesResponseDataList = Array<AdConversionValueRule>;
export const ListAdConversionValueRulesResponseDataList = /*@__PURE__*/ S.Array(
  AdConversionValueRule,
) as any as S.Schema<ListAdConversionValueRulesResponseDataList>;

export interface ListAdConversionValueRulesResponsePageInfo {
  end_cursor: string | null;
  has_next_page: boolean;
  has_previous_page: boolean;
  start_cursor: string | null;
}
export const ListAdConversionValueRulesResponsePageInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    end_cursor: S.NullOr(S.String),
    has_next_page: S.Boolean,
    has_previous_page: S.Boolean,
    start_cursor: S.NullOr(S.String),
  }),
).annotate({
  identifier: "ListAdConversionValueRulesResponsePageInfo",
}) as any as S.Schema<ListAdConversionValueRulesResponsePageInfo>;

export interface ListAdConversionValueRulesResponse {
  data: ListAdConversionValueRulesResponseDataList;
  page_info: ListAdConversionValueRulesResponsePageInfo;
}
export const ListAdConversionValueRulesResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: ListAdConversionValueRulesResponseDataList,
    page_info: ListAdConversionValueRulesResponsePageInfo,
  }),
).annotate({
  identifier: "ListAdConversionValueRulesResponse",
}) as any as S.Schema<ListAdConversionValueRulesResponse>;

export interface PauseAdConversionValueRuleRequest {
  /** Conversion value rule ID. */
  id: string;
  /** A unique key that makes this request safe to retry. See [Idempotent requests](https://docs.whop.com/developer/api/idempotency). */
  idempotency_key?: string;
}
export const PauseAdConversionValueRuleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
    idempotency_key: S.optional(S.String.pipe(T.Header("Idempotency-Key"))),
  }).pipe(T.Http({ method: "POST", uri: "/ad_conversion_value_rules/{id}/pause", code: 200 })),
).annotate({
  identifier: "PauseAdConversionValueRuleRequest",
}) as any as S.Schema<PauseAdConversionValueRuleRequest>;

export interface UnpauseAdConversionValueRuleRequest {
  /** Conversion value rule ID. */
  id: string;
  /** A unique key that makes this request safe to retry. See [Idempotent requests](https://docs.whop.com/developer/api/idempotency). */
  idempotency_key?: string;
}
export const UnpauseAdConversionValueRuleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
    idempotency_key: S.optional(S.String.pipe(T.Header("Idempotency-Key"))),
  }).pipe(T.Http({ method: "POST", uri: "/ad_conversion_value_rules/{id}/unpause", code: 200 })),
).annotate({
  identifier: "UnpauseAdConversionValueRuleRequest",
}) as any as S.Schema<UnpauseAdConversionValueRuleRequest>;

export type UpdateAdConversionValueRuleRequestAdjustmentType = "fixed" | "percentage";
export const UpdateAdConversionValueRuleRequestAdjustmentType = S.String;

export type UpdateAdConversionValueRuleRequestEventsItemEventName =
  | "purchase"
  | "subscribe"
  | "start_trial"
  | "lead"
  | "complete_registration"
  | "submit_application"
  | "schedule"
  | "contact"
  | "view_content"
  | "add_to_cart"
  | "custom";
export const UpdateAdConversionValueRuleRequestEventsItemEventName = S.String;

export interface UpdateAdConversionValueRuleRequestEventsItem {
  /** Exact custom event name. Required for custom events; null for standard events. */
  custom_name?: string | null;
  event_name: UpdateAdConversionValueRuleRequestEventsItemEventName | (string & {});
}
export const UpdateAdConversionValueRuleRequestEventsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    custom_name: S.optional(S.NullOr(S.String)),
    event_name: UpdateAdConversionValueRuleRequestEventsItemEventName,
  }),
).annotate({
  identifier: "UpdateAdConversionValueRuleRequestEventsItem",
}) as any as S.Schema<UpdateAdConversionValueRuleRequestEventsItem>;

/** Events adjusted on every selected target. Every platform must support every selected event. */
export type UpdateAdConversionValueRuleRequestEventsList =
  Array<UpdateAdConversionValueRuleRequestEventsItem>;
export const UpdateAdConversionValueRuleRequestEventsList = /*@__PURE__*/ S.Array(
  UpdateAdConversionValueRuleRequestEventsItem,
) as any as S.Schema<UpdateAdConversionValueRuleRequestEventsList>;

export type UpdateAdConversionValueRuleRequestFixedValue =
  CreateAdConversionValueRuleRequestFixedValue;
export const UpdateAdConversionValueRuleRequestFixedValue =
  CreateAdConversionValueRuleRequestFixedValue;

export type UpdateAdConversionValueRuleRequestMetadataMap = { [key: string]: string | undefined };
export const UpdateAdConversionValueRuleRequestMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<UpdateAdConversionValueRuleRequestMetadataMap>;

/** Exact IDs of active rules whose overlapping selections will be replaced. Other selections keep their values; remaining selections may split into separate rules. Broader rules remain as fallbacks for other items. Stale or incomplete conflict selections fail. */
export type UpdateAdConversionValueRuleRequestReplaceRuleIdsList = Array<string>;
export const UpdateAdConversionValueRuleRequestReplaceRuleIdsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<UpdateAdConversionValueRuleRequestReplaceRuleIdsList>;

export type UpdateAdConversionValueRuleRequestTargetsItemPlatform = "tiktok" | "meta" | "google";
export const UpdateAdConversionValueRuleRequestTargetsItemPlatform = S.String;

export type UpdateAdConversionValueRuleRequestTargetsItemScope =
  | "business"
  | "campaign"
  | "ad_group"
  | "ad";
export const UpdateAdConversionValueRuleRequestTargetsItemScope = S.String;

export interface UpdateAdConversionValueRuleRequestTargetsItem {
  platform: UpdateAdConversionValueRuleRequestTargetsItemPlatform | (string & {});
  /** Campaign, ad group, or ad ID. Null for a business target. */
  resource_id?: string | null;
  scope: UpdateAdConversionValueRuleRequestTargetsItemScope | (string & {});
}
export const UpdateAdConversionValueRuleRequestTargetsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    platform: UpdateAdConversionValueRuleRequestTargetsItemPlatform,
    resource_id: S.optional(S.NullOr(S.String)),
    scope: UpdateAdConversionValueRuleRequestTargetsItemScope,
  }),
).annotate({
  identifier: "UpdateAdConversionValueRuleRequestTargetsItem",
}) as any as S.Schema<UpdateAdConversionValueRuleRequestTargetsItem>;

/** Targets sharing one scope. Every selected event applies to every target. At most 500 target and event combinations. */
export type UpdateAdConversionValueRuleRequestTargetsList =
  Array<UpdateAdConversionValueRuleRequestTargetsItem>;
export const UpdateAdConversionValueRuleRequestTargetsList = /*@__PURE__*/ S.Array(
  UpdateAdConversionValueRuleRequestTargetsItem,
) as any as S.Schema<UpdateAdConversionValueRuleRequestTargetsList>;

export interface UpdateAdConversionValueRuleRequest {
  /** Conversion value rule ID. */
  id: string;
  adjustment_type?: UpdateAdConversionValueRuleRequestAdjustmentType | (string & {});
  /** Events adjusted on every selected target. Every platform must support every selected event. */
  events?: UpdateAdConversionValueRuleRequestEventsList;
  fixed_value?: CreateAdConversionValueRuleRequestFixedValue | null;
  metadata?: UpdateAdConversionValueRuleRequestMetadataMap;
  /** Signed percent change from negative 100 to 10000. The sent value cannot go below zero. */
  percentage_change?: number | null;
  /** Exact IDs of active rules whose overlapping selections will be replaced. Other selections keep their values; remaining selections may split into separate rules. Broader rules remain as fallbacks for other items. Stale or incomplete conflict selections fail. */
  replace_rule_ids?: UpdateAdConversionValueRuleRequestReplaceRuleIdsList;
  /** Targets sharing one scope. Every selected event applies to every target. At most 500 target and event combinations. */
  targets?: UpdateAdConversionValueRuleRequestTargetsList;
}
export const UpdateAdConversionValueRuleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
    adjustment_type: S.optional(UpdateAdConversionValueRuleRequestAdjustmentType),
    events: S.optional(UpdateAdConversionValueRuleRequestEventsList),
    fixed_value: S.optional(S.NullOr(CreateAdConversionValueRuleRequestFixedValue)),
    metadata: S.optional(UpdateAdConversionValueRuleRequestMetadataMap),
    percentage_change: S.optional(S.NullOr(S.Number)),
    replace_rule_ids: S.optional(UpdateAdConversionValueRuleRequestReplaceRuleIdsList),
    targets: S.optional(UpdateAdConversionValueRuleRequestTargetsList),
  }).pipe(T.Http({ method: "PATCH", uri: "/ad_conversion_value_rules/{id}", code: 200 })),
).annotate({
  identifier: "UpdateAdConversionValueRuleRequest",
}) as any as S.Schema<UpdateAdConversionValueRuleRequest>;

export type CreateAdConversionValueRuleError = Forbidden | Conflict | WhopOpError;
/** Create a conversion value rule Create one rule covering every selected target and event combination. Active rules cannot overlap for the same platform and event. Customer prices and Whop revenue stay unchanged. */
export const createAdConversionValueRule: API.OperationMethod<
  CreateAdConversionValueRuleRequest,
  AdConversionValueRule,
  CreateAdConversionValueRuleError,
  WhopOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateAdConversionValueRuleRequest,
  output: AdConversionValueRule,
  errors: [Forbidden, Conflict],
  protocol: WhopProtocol,
  retry: Retry.Retry,
}));

export type DeleteAdConversionValueRuleError = WhopOpError;
/** Delete a conversion value rule Soft-delete a rule and deactivate all its coverage. Preserve its stored settings. */
export const deleteAdConversionValueRule: API.OperationMethod<
  DeleteAdConversionValueRuleRequest,
  DeleteAdConversionValueRuleResponse,
  DeleteAdConversionValueRuleError,
  WhopOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteAdConversionValueRuleRequest,
  output: DeleteAdConversionValueRuleResponse,
  errors: [],
  protocol: WhopProtocol,
  retry: Retry.Retry,
}));

export type GetAdConversionValueRuleError = WhopOpError;
/** Retrieve a conversion value rule */
export const getAdConversionValueRule: API.OperationMethod<
  GetAdConversionValueRuleRequest,
  AdConversionValueRule,
  GetAdConversionValueRuleError,
  WhopOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetAdConversionValueRuleRequest,
  output: AdConversionValueRule,
  errors: [],
  protocol: WhopProtocol,
  retry: Retry.Retry,
}));

export type ListAdConversionValueRulesError = WhopOpError;
/** List conversion value rules List saved rules the caller can read. Filter by business with account_id. */
export const listAdConversionValueRules: API.PaginatedOperationMethod<
  ListAdConversionValueRulesRequest,
  ListAdConversionValueRulesResponse,
  ListAdConversionValueRulesError,
  WhopOpContext,
  AdConversionValueRule
> = /*@__PURE__*/ API.makePaginated(
  () => ({
    input: ListAdConversionValueRulesRequest,
    output: ListAdConversionValueRulesResponse,
    errors: [],
    protocol: WhopProtocol,
    retry: Retry.Retry,
    pagination: {
      mode: "relay",
      inputToken: "after",
      outputToken: "page_info.end_cursor",
      hasNextPage: "page_info.has_next_page",
      items: "data",
      pageSize: "first",
    } as const,
  }),
  paginateRelay,
) as any;

export type PauseAdConversionValueRuleError = Conflict | WhopOpError;
/** Pause a conversion value rule Pause the rule across all selected targets and events. */
export const pauseAdConversionValueRule: API.OperationMethod<
  PauseAdConversionValueRuleRequest,
  AdConversionValueRule,
  PauseAdConversionValueRuleError,
  WhopOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PauseAdConversionValueRuleRequest,
  output: AdConversionValueRule,
  errors: [Conflict],
  protocol: WhopProtocol,
  retry: Retry.Retry,
}));

export type UnpauseAdConversionValueRuleError = Conflict | WhopOpError;
/** Unpause a conversion value rule Resume the rule and automatically replace overlapping selections in the same transaction. Other selections keep their values, and broader rules remain as defaults. Rules with no remaining selections are paused. Resuming an already-active rule makes no changes. */
export const unpauseAdConversionValueRule: API.OperationMethod<
  UnpauseAdConversionValueRuleRequest,
  AdConversionValueRule,
  UnpauseAdConversionValueRuleError,
  WhopOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UnpauseAdConversionValueRuleRequest,
  output: AdConversionValueRule,
  errors: [Conflict],
  protocol: WhopProtocol,
  retry: Retry.Retry,
}));

export type UpdateAdConversionValueRuleError = WhopOpError;
/** Update a conversion value rule Edit a rule without changing its status. Supplied targets or events replace that selection in full. Omitted fields stay unchanged. All changes succeed or fail together. */
export const updateAdConversionValueRule: API.OperationMethod<
  UpdateAdConversionValueRuleRequest,
  AdConversionValueRule,
  UpdateAdConversionValueRuleError,
  WhopOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateAdConversionValueRuleRequest,
  output: AdConversionValueRule,
  errors: [],
  protocol: WhopProtocol,
  retry: Retry.Retry,
}));
