import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/api-v1-native.json + api-v1-stable.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { WhopProtocol, type WhopOpError, type WhopOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { WhopOpError, WhopOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

export class UnprocessableEntity
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<UnprocessableEntity>()("UnprocessableEntity", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 422 }],
  ) {}

/** The available currencies on the platform */
export type LegacyCurrencies =
  | "usd"
  | "sgd"
  | "inr"
  | "aud"
  | "brl"
  | "cad"
  | "dkk"
  | "eur"
  | "nok"
  | "gbp"
  | "sek"
  | "chf"
  | "hkd"
  | "huf"
  | "jpy"
  | "mxn"
  | "myr"
  | "pln"
  | "czk"
  | "nzd"
  | "aed"
  | "eth"
  | "ape"
  | "cop"
  | "ron"
  | "thb"
  | "bgn"
  | "idr"
  | "dop"
  | "php"
  | "try"
  | "krw"
  | "twd"
  | "vnd"
  | "pkr"
  | "clp"
  | "uyu"
  | "ars"
  | "zar"
  | "dzd"
  | "tnd"
  | "mad"
  | "kes"
  | "kwd"
  | "jod"
  | "all"
  | "xcd"
  | "amd"
  | "bsd"
  | "bhd"
  | "bob"
  | "bam"
  | "khr"
  | "crc"
  | "xof"
  | "egp"
  | "etb"
  | "gmd"
  | "ghs"
  | "gtq"
  | "gyd"
  | "ils"
  | "jmd"
  | "mop"
  | "mga"
  | "mur"
  | "mdl"
  | "mnt"
  | "nad"
  | "ngn"
  | "mkd"
  | "omr"
  | "pyg"
  | "pen"
  | "qar"
  | "rwf"
  | "sar"
  | "rsd"
  | "lkr"
  | "tzs"
  | "ttd"
  | "uzs"
  | "rub"
  | "btc"
  | "cny"
  | "usdt"
  | "kzt"
  | "awg"
  | "whop_usd"
  | "xau";
export const LegacyCurrencies = S.String;

export interface CreateTopupRequest {
  /** The unique identifier of the company to add funds to, starting with 'biz_'. */
  account_id: string;
  /** The amount to add to the balance in the specified currency. For example, 50.00 for $50.00 USD. */
  amount: number;
  /** The currency for the top-up amount, such as 'usd'. */
  currency: LegacyCurrencies | (string & {});
  /** The unique identifier of the stored payment method to charge for the top-up. */
  payment_method_id: string;
}
export const CreateTopupRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.String,
    amount: S.Number,
    currency: LegacyCurrencies,
    payment_method_id: S.String,
  }).pipe(T.Http({ method: "POST", uri: "/topups", code: 200 })),
).annotate({ identifier: "CreateTopupRequest" }) as any as S.Schema<CreateTopupRequest>;

/** The status of a receipt */
export type LegacyReceiptStatus =
  | "draft"
  | "open"
  | "authorized"
  | "paid"
  | "pending"
  | "uncollectible"
  | "unresolved"
  | "void";
export const LegacyReceiptStatus = S.String;

/** A payment represents a completed or attempted charge. Payments track the amount, status, currency, and payment method used. */
export interface Topup {
  /** The datetime the payment was created. */
  created_at: string;
  /** The three-letter ISO currency code for this payment (e.g., 'usd', 'eur'). */
  currency: LegacyCurrencies | null;
  /** If the payment failed, the reason for the failure. */
  failure_message: string | null;
  /** The unique identifier for the payment. */
  id: string;
  /** The time at which this payment was successfully collected. Null if the payment has not yet succeeded. As a Unix timestamp. */
  paid_at: string | null;
  /** The current lifecycle state of this payment (e.g., 'draft', 'open', 'paid', 'void'). */
  status: LegacyReceiptStatus | null;
  /** The total to show to the creator (excluding buyer fees). */
  total: number | null;
}
export const Topup = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    created_at: S.String,
    currency: S.NullOr(LegacyCurrencies),
    failure_message: S.NullOr(S.String),
    id: S.String,
    paid_at: S.NullOr(S.String),
    status: S.NullOr(LegacyReceiptStatus),
    total: S.NullOr(S.Number),
  }),
).annotate({ identifier: "Topup" }) as any as S.Schema<Topup>;

export type CreateTopupError =
  | BadRequest
  | Forbidden
  | NotFound
  | UnprocessableEntity
  | WhopOpError;
/** Create topup [Legacy API — https://docs.whop.com/api-reference] Add funds to a company's platform balance by charging a stored payment method. Top-ups have no fees or taxes and do not count as revenue. Required permissions: - `payment:charge` */
export const createTopup: API.OperationMethod<
  CreateTopupRequest,
  Topup,
  CreateTopupError,
  WhopOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateTopupRequest,
  output: Topup,
  errors: [BadRequest, Forbidden, NotFound, UnprocessableEntity],
  protocol: WhopProtocol,
  retry: Retry.Retry,
}));
