import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/api-v1-native.json + api-v1-stable.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { paginateRelay } from "../pagination.ts";
import { WhopProtocol, type WhopOpError, type WhopOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { WhopOpError, WhopOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Conflict
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Conflict>()("Conflict", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withConflictError),
    [{ status: 409 }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

export interface CheckUserAccessRequest {
  /** The user_ tag or username to check access for. */
  id: string;
  /** An account (biz_), product (prod_), or experience (exp_) ID. */
  resource_id: string;
}
export const CheckUserAccessRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
    resource_id: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/users/{id}/access/{resource_id}", code: 200 })),
).annotate({ identifier: "CheckUserAccessRequest" }) as any as S.Schema<CheckUserAccessRequest>;

export type CheckUserAccessResponseAccessLevel = "no_access" | "admin" | "customer";
export const CheckUserAccessResponseAccessLevel = S.String;

export interface CheckUserAccessResponse {
  access_level: CheckUserAccessResponseAccessLevel;
  has_access: boolean;
}
export const CheckUserAccessResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    access_level: CheckUserAccessResponseAccessLevel,
    has_access: S.Boolean,
  }),
).annotate({ identifier: "CheckUserAccessResponse" }) as any as S.Schema<CheckUserAccessResponse>;

/** How `code_challenge` was derived. Only `S256` is accepted. */
export type CreateOauthGrantRequestCodeChallengeMethod = "S256";
export const CreateOauthGrantRequestCodeChallengeMethod = S.String;

/** The permissions the app is asking for, for example `member:basic:read`. `GET /api_keys/permissions` names and describes each one. Granting adds to whatever the user already granted this app rather than replacing it. */
export type CreateOauthGrantRequestRequestedScopesList = Array<string>;
export const CreateOauthGrantRequestRequestedScopesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreateOauthGrantRequestRequestedScopesList>;

/** The OAuth response type. Only `code` is accepted; defaults to `code`. */
export type CreateOauthGrantRequestResponseType = "code";
export const CreateOauthGrantRequestResponseType = S.String;

export interface CreateOauthGrantRequest {
  /** Authorize the app for one of the user's accounts rather than for the user alone, prefixed `biz_`. The user must have access to it. */
  account_id?: string;
  /** The app being authorized, prefixed `app_`. */
  client_id: string;
  /** The PKCE code challenge: the base64url-encoded SHA-256 of your code verifier, without padding. */
  code_challenge: string;
  /** How `code_challenge` was derived. Only `S256` is accepted. */
  code_challenge_method: CreateOauthGrantRequestCodeChallengeMethod | (string & {});
  /** Whether the consent UI listed these scopes for the user. Sending `false` succeeds only when the user has already granted every scope requested. */
  consent_shown?: boolean;
  /** OIDC nonce, echoed into the resulting ID token. Required when `requested_scopes` includes `openid`. */
  nonce?: string;
  /** Where to send the user once they have consented. Must match one of the app's registered redirect URIs exactly — it is compared as a string, not normalized. */
  redirect_uri: string;
  /** The permissions the app is asking for, for example `member:basic:read`. `GET /api_keys/permissions` names and describes each one. Granting adds to whatever the user already granted this app rather than replacing it. */
  requested_scopes: CreateOauthGrantRequestRequestedScopesList;
  /** The OAuth response type. Only `code` is accepted; defaults to `code`. */
  response_type?: CreateOauthGrantRequestResponseType | (string & {});
  /** Opaque value appended to `redirect_url` unchanged, for the client to correlate the response with its request. */
  state?: string;
  /** A unique key that makes this request safe to retry. See [Idempotent requests](https://docs.whop.com/developer/api/idempotency). */
  idempotency_key?: string;
}
export const CreateOauthGrantRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.optional(S.String),
    client_id: S.String,
    code_challenge: S.String,
    code_challenge_method: CreateOauthGrantRequestCodeChallengeMethod,
    consent_shown: S.optional(S.Boolean),
    nonce: S.optional(S.String),
    redirect_uri: S.String,
    requested_scopes: CreateOauthGrantRequestRequestedScopesList,
    response_type: S.optional(CreateOauthGrantRequestResponseType),
    state: S.optional(S.String),
    idempotency_key: S.optional(S.String.pipe(T.Header("Idempotency-Key"))),
  }).pipe(T.Http({ method: "POST", uri: "/users/me/oauth_grants", code: 200 })),
).annotate({ identifier: "CreateOauthGrantRequest" }) as any as S.Schema<CreateOauthGrantRequest>;

export type OauthGrantScopesList = Array<string>;
export const OauthGrantScopesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<OauthGrantScopesList>;

export interface OauthGrant {
  /** The account the grant is scoped to, prefixed `biz_`. `null` when the user authorized the app for themselves rather than for one of their accounts. */
  account_id: string | null;
  /** The app this grant authorizes, prefixed `app_`. */
  app_id: string;
  /** When the user last authorized the app, as an ISO 8601 timestamp. */
  authorized_at: string | null;
  /** When the user first authorized the app, as an ISO 8601 timestamp. */
  created_at: string;
  /** Grant ID, prefixed `oag_`. */
  id: string;
  /** Where to send the user to finish the flow: the `redirect_uri` you supplied with the authorization `code` appended, and `state` when you supplied one. Its scheme, host, port, and path come back exactly as sent — never re-cased or re-encoded — because the client matches them against its registered URI. Returned only once, on create: the code is single-use and expires 10 minutes after it is issued, so redirect immediately. */
  redirect_url?: string;
  /** When the grant was revoked, as an ISO 8601 timestamp, or `null` while it is still in force. A revoked grant authorizes nothing — treat its `scopes` as no longer granted. */
  revoked_at: string | null;
  scopes: OauthGrantScopesList;
}
export const OauthGrant = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.NullOr(S.String),
    app_id: S.String,
    authorized_at: S.NullOr(S.String),
    created_at: S.String,
    id: S.String,
    redirect_url: S.optional(S.String),
    revoked_at: S.NullOr(S.String),
    scopes: OauthGrantScopesList,
  }),
).annotate({ identifier: "OauthGrant" }) as any as S.Schema<OauthGrant>;

export interface CreatePasskeyRequest {
  /** The `attestationObject` from the WebAuthn attestation response, base64url-encoded. */
  attestation_object: string;
  /** The `clientDataJSON` from the WebAuthn attestation response, base64url-encoded. */
  client_data_json: string;
  /** The WebAuthn credential ID the authenticator returned, base64url-encoded. */
  credential_id: string;
  /** A name for this passkey, usually the device it lives on. 255 characters or fewer. */
  nickname: string;
  /** A unique key that makes this request safe to retry. See [Idempotent requests](https://docs.whop.com/developer/api/idempotency). */
  idempotency_key?: string;
}
export const CreatePasskeyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    attestation_object: S.String,
    client_data_json: S.String,
    credential_id: S.String,
    nickname: S.String,
    idempotency_key: S.optional(S.String.pipe(T.Header("Idempotency-Key"))),
  }).pipe(T.Http({ method: "POST", uri: "/users/me/passkeys", code: 200 })),
).annotate({ identifier: "CreatePasskeyRequest" }) as any as S.Schema<CreatePasskeyRequest>;

export interface Passkey {
  /** When the user registered this passkey, as an ISO 8601 timestamp. */
  created_at: string;
  /** The WebAuthn credential ID as a base64url string. Pass it in `allowCredentials` when you run a ceremony against this specific passkey. */
  credential_id: string;
  /** Passkey ID, prefixed `wcred_`. Use it to delete the passkey. */
  id: string;
  /** When this passkey last completed a WebAuthn ceremony, as an ISO 8601 timestamp, or `null` if it never has. */
  last_used_at: string | null;
  /** The name the user gave this passkey, usually the device it lives on. */
  nickname: string;
}
export const Passkey = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    created_at: S.String,
    credential_id: S.String,
    id: S.String,
    last_used_at: S.NullOr(S.String),
    nickname: S.String,
  }),
).annotate({ identifier: "Passkey" }) as any as S.Schema<Passkey>;

/** The ceremony this challenge is for. */
export type CreatePasskeyChallengeRequestChallengeType = "registration" | "deletion";
export const CreatePasskeyChallengeRequestChallengeType = S.String;

export interface CreatePasskeyChallengeRequest {
  /** The ceremony this challenge is for. */
  challenge_type: CreatePasskeyChallengeRequestChallengeType | (string & {});
  /** The passkey the ceremony targets, prefixed `wcred_`. Required when `challenge_type` is `deletion`, ignored otherwise. */
  passkey_id?: string;
  /** A unique key that makes this request safe to retry. See [Idempotent requests](https://docs.whop.com/developer/api/idempotency). */
  idempotency_key?: string;
}
export const CreatePasskeyChallengeRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    challenge_type: CreatePasskeyChallengeRequestChallengeType,
    passkey_id: S.optional(S.String),
    idempotency_key: S.optional(S.String.pipe(T.Header("Idempotency-Key"))),
  }).pipe(T.Http({ method: "POST", uri: "/users/me/passkeys/challenge", code: 200 })),
).annotate({
  identifier: "CreatePasskeyChallengeRequest",
}) as any as S.Schema<CreatePasskeyChallengeRequest>;

export interface CreatePasskeyChallengeResponse {
  /** The challenge to pass to the WebAuthn ceremony, base64url-encoded without padding. */
  challenge: string;
}
export const CreatePasskeyChallengeResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    challenge: S.String,
  }),
).annotate({
  identifier: "CreatePasskeyChallengeResponse",
}) as any as S.Schema<CreatePasskeyChallengeResponse>;

export interface DeletePasskeyRequest {
  /** Passkey ID, prefixed `wcred_`. */
  id: string;
  /** The `authenticatorData` from the WebAuthn assertion, base64url-encoded. */
  authenticator_data: string;
  /** The `clientDataJSON` from the WebAuthn assertion, base64url-encoded. */
  client_data_json: string;
  /** The `signature` from the WebAuthn assertion, base64url-encoded. */
  signature: string;
}
export const DeletePasskeyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
    authenticator_data: S.String,
    client_data_json: S.String,
    signature: S.String,
  }).pipe(T.Http({ method: "DELETE", uri: "/users/me/passkeys/{id}", code: 200 })),
).annotate({ identifier: "DeletePasskeyRequest" }) as any as S.Schema<DeletePasskeyRequest>;

export interface DeletePasskeyResponse {
  /** Always `true`: the passkey was removed. */
  deleted: boolean;
  /** The ID of the deleted passkey. */
  id: string;
}
export const DeletePasskeyResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    deleted: S.Boolean,
    id: S.String,
  }),
).annotate({ identifier: "DeletePasskeyResponse" }) as any as S.Schema<DeletePasskeyResponse>;

export type GetUserRequestInterval = "hour" | "day" | "week" | "month";
export const GetUserRequestInterval = S.String;

export interface GetUserRequest {
  /** User ID (prefixed `user_`), username, or `me` for the authenticated user. */
  id: string;
  /** Also retrieve live trading state under `trading`. Only honored on the self view (me) with crypto_wallet:trade:read, crypto_wallet:trade, or crypto_wallet:manage permission and an Ethereum wallet. Provider failures return 503. */
  include_trading?: boolean;
  /** When set, returns the user's account-specific profile overrides for this account. */
  account_id?: string;
  /** Compute live wallet and owned-account balances on the self view (default true). Set false for identity-only reads. Ignored when the id is not `me` or the caller lacks balance-read scope. */
  include_balance?: boolean;
  /** Also compute your balance history (opt-in; runs a heavier query). Only applies when the id is `me`; ignored for callers without balance-read scope. */
  include_balance_history?: boolean;
  /** Balance-history window start, ISO 8601 date or datetime. Defaults to 30 days ago. Only used with `include_balance_history`. */
  from?: string;
  /** Balance-history window end, ISO 8601 date or datetime. Defaults to now. Only used with `include_balance_history`. */
  to?: string;
  /** Balance-history point granularity. Defaults to `day`. Only used with `include_balance_history`. */
  interval?: GetUserRequestInterval | (string & {});
  /** IANA time zone the balance-history points are bucketed in. Defaults to `UTC`. Only used with `include_balance_history`. */
  time_zone?: string;
}
export const GetUserRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
    include_trading: S.optional(S.Boolean.pipe(T.Query())),
    account_id: S.optional(S.String.pipe(T.Query())),
    include_balance: S.optional(S.Boolean.pipe(T.Query())),
    include_balance_history: S.optional(S.Boolean.pipe(T.Query())),
    from: S.optional(S.String.pipe(T.Query())),
    to: S.optional(S.String.pipe(T.Query())),
    interval: S.optional(GetUserRequestInterval.pipe(T.Query())),
    time_zone: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/users/{id}", code: 200 })),
).annotate({ identifier: "GetUserRequest" }) as any as S.Schema<GetUserRequest>;

export interface UserBalanceBusiness {
  /** The account's total balance in USD. */
  balance_usd: string;
  /** The account ID, which looks like biz_*************. */
  id: string;
  /** The account's logo URL. */
  logo_url: string | null;
  /** The account's display name. */
  name: string | null;
}
export const UserBalanceBusiness = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    balance_usd: S.String,
    id: S.String,
    logo_url: S.NullOr(S.String),
    name: S.NullOr(S.String),
  }),
).annotate({ identifier: "UserBalanceBusiness" }) as any as S.Schema<UserBalanceBusiness>;

export type UserBalanceBusinessesList = Array<UserBalanceBusiness>;
export const UserBalanceBusinessesList = /*@__PURE__*/ S.Array(
  UserBalanceBusiness,
) as any as S.Schema<UserBalanceBusinessesList>;

export interface UserBalanceCash {
  /** Available balance in the native currency. */
  balance: number;
  /** Available balance converted to USD. */
  balance_usd: number;
  /** Lowercase ISO currency code, such as `usd` or `eur`. */
  currency: string;
  /** Balance moving to the user's own wallet or card, converted to USD. */
  in_transit_balance_usd: number;
  /** Pending balance converted to USD. */
  pending_balance_usd: number;
  /** USD price per native currency unit, or `null` when no exchange rate is available. */
  price_usd: number | null;
  /** Reserved balance converted to USD. */
  reserve_balance_usd: number;
  /** Withdrawable amount in the native currency. */
  total_withdrawable_balance: number;
}
export const UserBalanceCash = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    balance: S.Number,
    balance_usd: S.Number,
    currency: S.String,
    in_transit_balance_usd: S.Number,
    pending_balance_usd: S.Number,
    price_usd: S.NullOr(S.Number),
    reserve_balance_usd: S.Number,
    total_withdrawable_balance: S.Number,
  }),
).annotate({ identifier: "UserBalanceCash" }) as any as S.Schema<UserBalanceCash>;

export type UserBalanceCashList = Array<UserBalanceCash>;
export const UserBalanceCashList = /*@__PURE__*/ S.Array(
  UserBalanceCash,
) as any as S.Schema<UserBalanceCashList>;

export interface AccountBalanceSettlement {
  /** Amount expected that day, in native units, as a decimal string. */
  amount: string;
  /** The day this money is expected to finish settling, as an ISO 8601 date. */
  date: string;
}
export const AccountBalanceSettlement = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    amount: S.String,
    date: S.String,
  }),
).annotate({ identifier: "AccountBalanceSettlement" }) as any as S.Schema<AccountBalanceSettlement>;

export type AccountBalanceBreakdownPendingSettlementsList = Array<AccountBalanceSettlement>;
export const AccountBalanceBreakdownPendingSettlementsList = /*@__PURE__*/ S.Array(
  AccountBalanceSettlement,
) as any as S.Schema<AccountBalanceBreakdownPendingSettlementsList>;

export interface AccountBalanceBreakdown {
  /** Amount you can spend, send, or withdraw now, in native units, as a decimal string. */
  available: string;
  /** Amount moving between the account's own destinations, such as a treasury sweep to its crypto wallet or a card top-up. In native units, as a decimal string. */
  in_transit: string;
  /** Amount from recent payments still settling, in native units, as a decimal string. */
  pending: string;
  pending_settlements: AccountBalanceBreakdownPendingSettlementsList;
  /** Amount held back, in native units, as a decimal string. Retrieve the account's reserves for why it is held and when it unlocks. */
  reserve: string;
}
export const AccountBalanceBreakdown = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    available: S.String,
    in_transit: S.String,
    pending: S.String,
    pending_settlements: AccountBalanceBreakdownPendingSettlementsList,
    reserve: S.String,
  }),
).annotate({ identifier: "AccountBalanceBreakdown" }) as any as S.Schema<AccountBalanceBreakdown>;

export interface UserBalanceToken {
  /** Amount held in native token units, as a decimal string. */
  balance: string;
  /** Balance split into available, pending, in-transit, and reserve amounts, as native-unit decimal strings. Transfers between the user's own wallet and card are reported in `in_transit` until they arrive. */
  breakdown: AccountBalanceBreakdown;
  /** Token icon URL. */
  icon_url: string | null;
  /** The token's display name. */
  name: string | null;
  /** USD price per token, or `null` when unknown. */
  price_usd: number | null;
  /** Token display symbol, such as `USDT`, `XAUT`, or `cbBTC`. */
  symbol: string;
  /** Holding USD value. */
  value_usd: number;
}
export const UserBalanceToken = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    balance: S.String,
    breakdown: AccountBalanceBreakdown,
    icon_url: S.NullOr(S.String),
    name: S.NullOr(S.String),
    price_usd: S.NullOr(S.Number),
    symbol: S.String,
    value_usd: S.Number,
  }),
).annotate({ identifier: "UserBalanceToken" }) as any as S.Schema<UserBalanceToken>;

export type UserBalanceCryptoList = Array<UserBalanceToken>;
export const UserBalanceCryptoList = /*@__PURE__*/ S.Array(
  UserBalanceToken,
) as any as S.Schema<UserBalanceCryptoList>;

export interface UserBalance {
  businesses: UserBalanceBusinessesList;
  /** Combined USD balance across every account the user owns. */
  businesses_total_usd: string;
  cash: UserBalanceCashList;
  /** Fiat cash in USD, including pending, in-transit, and reserve. */
  cash_usd: string;
  crypto: UserBalanceCryptoList;
  /** Crypto holdings in USD. */
  crypto_usd: string;
  /** Fiat pending and in-transit balances, plus in-flight treasury deposits, in USD. */
  pending_usd: string;
  /** The user's personal balance in USD: cash (available + pending + in-transit + reserve) + crypto + in-flight treasury deposits. Excludes account balances (see businesses_total_usd). */
  total_usd: string;
  /** Balance-to-wallet USDT0 payouts still in flight, in USD. */
  treasury_pending_usd: string;
}
export const UserBalance = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    businesses: UserBalanceBusinessesList,
    businesses_total_usd: S.String,
    cash: UserBalanceCashList,
    cash_usd: S.String,
    crypto: UserBalanceCryptoList,
    crypto_usd: S.String,
    pending_usd: S.String,
    total_usd: S.String,
    treasury_pending_usd: S.String,
  }),
).annotate({ identifier: "UserBalance" }) as any as S.Schema<UserBalance>;

export interface UserBalanceHistoryPoint {
  /** Point timestamp, in Unix seconds. */
  t: number;
  /** Cumulative wallet balance at this point, in USD. */
  v: number;
}
export const UserBalanceHistoryPoint = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    t: S.Number,
    v: S.Number,
  }),
).annotate({ identifier: "UserBalanceHistoryPoint" }) as any as S.Schema<UserBalanceHistoryPoint>;

export type UserBalanceHistoryDataList = Array<UserBalanceHistoryPoint>;
export const UserBalanceHistoryDataList = /*@__PURE__*/ S.Array(
  UserBalanceHistoryPoint,
) as any as S.Schema<UserBalanceHistoryDataList>;

export interface UserBalanceHistory {
  data: UserBalanceHistoryDataList;
  /** Value of the most recent point, in USD. */
  last: number;
  /** Maximum value across the window, in USD. */
  max: number;
  /** Minimum value across the window, in USD. */
  min: number;
}
export const UserBalanceHistory = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: UserBalanceHistoryDataList,
    last: S.Number,
    max: S.Number,
    min: S.Number,
  }),
).annotate({ identifier: "UserBalanceHistory" }) as any as S.Schema<UserBalanceHistory>;

export interface UserBanner {
  /** Profile banner image URL. */
  url: string;
}
export const UserBanner = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.String,
  }),
).annotate({ identifier: "UserBanner" }) as any as S.Schema<UserBanner>;

export interface UserEarningsAmount {
  /** Gross income in USD over the last 24 hours. */
  last_24_hours: string;
  /** Gross income in USD over the last 30 days. */
  last_30_days: string;
  /** Gross income in USD over the last 7 days. */
  last_7_days: string;
  /** All-time gross income in USD. */
  lifetime: string;
}
export const UserEarningsAmount = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    last_24_hours: S.String,
    last_30_days: S.String,
    last_7_days: S.String,
    lifetime: S.String,
  }),
).annotate({ identifier: "UserEarningsAmount" }) as any as S.Schema<UserEarningsAmount>;

export interface UserEarnings {
  /** The first time the user earned gross income, as an ISO 8601 timestamp. */
  first_earned_at: string | null;
  /** Gross income from accounts the user owns or is owner-authorized on. */
  owned_accounts: UserEarningsAmount;
  /** Partner commissions posted to the user's wallet. Pending Partner payouts are excluded until they post; later reversals do not reduce gross income. */
  partners: UserEarningsAmount;
  /** Gross income from the user's personal wallet. */
  personal: UserEarningsAmount;
  /** Gross income from the user's personal wallet plus accounts they own or are owner-authorized on. */
  total: UserEarningsAmount;
}
export const UserEarnings = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    first_earned_at: S.NullOr(S.String),
    owned_accounts: UserEarningsAmount,
    partners: UserEarningsAmount,
    personal: UserEarningsAmount,
    total: UserEarningsAmount,
  }),
).annotate({ identifier: "UserEarnings" }) as any as S.Schema<UserEarnings>;

export interface UserProfilePicture {
  /** Avatar image URL. Always present — a generated placeholder when the user set no picture. */
  url: string;
}
export const UserProfilePicture = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.String,
  }),
).annotate({ identifier: "UserProfilePicture" }) as any as S.Schema<UserProfilePicture>;

/** The platform the parent social account exists on. */
export type SocialAccountParentPlatform =
  | "x"
  | "instagram"
  | "youtube"
  | "tiktok"
  | "facebook"
  | "discord"
  | "telegram"
  | "linkedin"
  | "snapchat";
export const SocialAccountParentPlatform = S.String;

export interface SocialAccountParent {
  /** The platform-specific ID for the parent social account. */
  external_id: string | null;
  /** Social account ID, prefixed `sacc_`. */
  id: string;
  /** The display name of the parent social account on the platform. */
  name: string | null;
  /** The platform the parent social account exists on. */
  platform: SocialAccountParentPlatform;
  /** The URL where the profile picture of the parent social account can be accessed. */
  profile_picture_url: string | null;
  /** The username of the parent social account on the platform. */
  username: string | null;
  /** Whether the parent social account is verified on the platform. */
  verified: boolean;
}
export const SocialAccountParent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    external_id: S.NullOr(S.String),
    id: S.String,
    name: S.NullOr(S.String),
    platform: SocialAccountParentPlatform,
    profile_picture_url: S.NullOr(S.String),
    username: S.NullOr(S.String),
    verified: S.Boolean,
  }),
).annotate({ identifier: "SocialAccountParent" }) as any as S.Schema<SocialAccountParent>;

/** The platform the social account exists on. */
export type SocialAccountPlatform =
  | "x"
  | "instagram"
  | "youtube"
  | "tiktok"
  | "facebook"
  | "discord"
  | "telegram"
  | "linkedin"
  | "snapchat";
export const SocialAccountPlatform = S.String;

export type SocialAccountScopesList = Array<string>;
export const SocialAccountScopesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<SocialAccountScopesList>;

export interface SocialAccount {
  /** Why this social account currently can't be used for advertising — a failed share or a Meta-side restriction. Null when the account is healthy. */
  error: string | null;
  /** The platform-specific ID for this social account. */
  external_id: string | null;
  /** Unique identifier for the social account. */
  id: string;
  /** The display name of the social account on the platform. */
  name: string | null;
  /** The social account this one belongs to on the platform, such as the Facebook page that owns an Instagram account. Null when the social account stands on its own. */
  parent_social_account: SocialAccountParent | null;
  /** The platform the social account exists on. */
  platform: SocialAccountPlatform;
  /** The URL where the profile picture of the social account can be accessed. */
  profile_picture_url: string | null;
  scopes: SocialAccountScopesList;
  /** The URL where the social account can be accessed on the platform. Null while a Whop-owned account is still being provisioned. */
  url: string | null;
  /** The username of the social account on the platform. Null while a Whop-owned account is still being provisioned. */
  username: string | null;
  /** Whether the social account is verified on the platform. */
  verified: boolean;
}
export const SocialAccount = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    error: S.NullOr(S.String),
    external_id: S.NullOr(S.String),
    id: S.String,
    name: S.NullOr(S.String),
    parent_social_account: S.NullOr(SocialAccountParent),
    platform: SocialAccountPlatform,
    profile_picture_url: S.NullOr(S.String),
    scopes: SocialAccountScopesList,
    url: S.NullOr(S.String),
    username: S.NullOr(S.String),
    verified: S.Boolean,
  }),
).annotate({ identifier: "SocialAccount" }) as any as S.Schema<SocialAccount>;

export type UserSocialAccountsList = Array<SocialAccount>;
export const UserSocialAccountsList = /*@__PURE__*/ S.Array(
  SocialAccount,
) as any as S.Schema<UserSocialAccountsList>;

export interface UserStaffAccess {
  /** Whether the user holds the admin staff role with a valid second factor. */
  admin: boolean;
  /** Whether the user can open Whop-internal investigation tooling right now: a qualifying staff role plus their investigation toggle switched on. */
  investigation_access: boolean;
  /** Whether the user holds the manager staff role with a valid second factor. */
  manager: boolean;
  /** Whether the user holds the support staff role with a valid second factor. */
  support: boolean;
}
export const UserStaffAccess = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    admin: S.Boolean,
    investigation_access: S.Boolean,
    manager: S.Boolean,
    support: S.Boolean,
  }),
).annotate({ identifier: "UserStaffAccess" }) as any as S.Schema<UserStaffAccess>;

export interface Money {
  /** The amount in major units, as an exact decimal string — `"10.00"` is ten dollars. A string so no float rounds it in transit. */
  amount: string;
  /** Three-letter ISO 4217 currency code, lowercase. */
  currency: string;
  /** How many decimal places the amount CARRIES — the precision the charge itself runs at. */
  decimals: number;
  /** How many decimal places to SHOW. Usually equal to `decimals`, and deliberately not always: COP is charged in centavos but written in whole pesos, so it is `2` and `0`. Format the number in your own locale using this. */
  display_decimals: number;
}
export const Money = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    amount: S.String,
    currency: S.String,
    decimals: S.Number,
    display_decimals: S.Number,
  }),
).annotate({ identifier: "Money" }) as any as S.Schema<Money>;

export interface TradingMarginSummary {
  /** Total account value in USD, including unrealized profit and loss. */
  account_value: Money;
  /** Margin allocated across open positions, in USD. */
  total_margin_used: Money;
  /** Combined notional value of open positions, in USD. */
  total_position_notional: Money;
  /** Raw USD balance as Hyperliquid reports it, excluding position value. */
  total_raw_usd: Money;
  /** USD that can be withdrawn now without closing positions. */
  withdrawable: Money;
}
export const TradingMarginSummary = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_value: Money,
    total_margin_used: Money,
    total_position_notional: Money,
    total_raw_usd: Money,
    withdrawable: Money,
  }),
).annotate({ identifier: "TradingMarginSummary" }) as any as S.Schema<TradingMarginSummary>;

/** The live update stream this subscription opens. */
export type TradingWebsocketSubscriptionChannel =
  | "clearinghouse_state"
  | "open_orders"
  | "order_updates"
  | "user_fills"
  | "user_events";
export const TradingWebsocketSubscriptionChannel = S.String;

export interface TradingWebsocketSubscription {
  /** The live update stream this subscription opens. */
  channel: TradingWebsocketSubscriptionChannel;
  /** JSON subscription message to send unchanged over the Hyperliquid WebSocket. */
  message: string;
}
export const TradingWebsocketSubscription = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    channel: TradingWebsocketSubscriptionChannel,
    message: S.String,
  }),
).annotate({
  identifier: "TradingWebsocketSubscription",
}) as any as S.Schema<TradingWebsocketSubscription>;

export type TradingHyperliquidAccountWebsocketSubscriptionsList =
  Array<TradingWebsocketSubscription>;
export const TradingHyperliquidAccountWebsocketSubscriptionsList = /*@__PURE__*/ S.Array(
  TradingWebsocketSubscription,
) as any as S.Schema<TradingHyperliquidAccountWebsocketSubscriptionsList>;

export interface TradingHyperliquidAccount {
  /** Lowercase wallet address that holds the Hyperliquid account. */
  address: string;
  /** Builder fee Whop charges on orders, in basis points as a decimal string, or `null` when no fee is configured. */
  builder_fee_bps: string | null;
  /** Account value, margin, and withdrawable balance, all in USD. */
  margin_summary: TradingMarginSummary;
  websocket_subscriptions: TradingHyperliquidAccountWebsocketSubscriptionsList;
  /** Hyperliquid WebSocket URL to connect to directly for live updates. */
  websocket_url: string;
}
export const TradingHyperliquidAccount = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    address: S.String,
    builder_fee_bps: S.NullOr(S.String),
    margin_summary: TradingMarginSummary,
    websocket_subscriptions: TradingHyperliquidAccountWebsocketSubscriptionsList,
    websocket_url: S.String,
  }),
).annotate({
  identifier: "TradingHyperliquidAccount",
}) as any as S.Schema<TradingHyperliquidAccount>;

export type TradingAccountObject = "trading_account";
export const TradingAccountObject = S.String;

export interface TradingHyperliquidOrder {
  /** Whether the order can only reduce an existing position, or `null` when Hyperliquid omits it. */
  reduce_only: boolean | null;
  /** Trigger price in USD for take-profit and stop-loss orders, or `null` for orders without a trigger. */
  trigger_price: Money | null;
}
export const TradingHyperliquidOrder = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    reduce_only: S.NullOr(S.Boolean),
    trigger_price: S.NullOr(Money),
  }),
).annotate({ identifier: "TradingHyperliquidOrder" }) as any as S.Schema<TradingHyperliquidOrder>;

export type TradingOrderObject = "trading_order";
export const TradingOrderObject = S.String;

export type TradingOrderOrderType = "limit" | "market" | "take_profit" | "stop_loss";
export const TradingOrderOrderType = S.String;

export type TradingOrderSide = "buy" | "sell";
export const TradingOrderSide = S.String;

export type TradingOrderStatus = "open" | "filled" | "canceled" | "triggered" | "rejected";
export const TradingOrderStatus = S.String;

/** How long the order stays active. `null` when the provider omits it or reports a policy outside the supported values. */
export type TradingOrderTimeInForce =
  | "add_liquidity_only"
  | "good_til_canceled"
  | "immediate_or_cancel";
export const TradingOrderTimeInForce = S.String;

export interface TradingOrder {
  /** Client order ID, prefixed `trdcloid_`, or `null` when the order was placed without one. */
  client_order_id: string | null;
  /** When the order was placed, as an ISO 8601 timestamp, or `null` when the provider omits it. */
  created_at: string | null;
  /** Hyperliquid-specific order details. Present on Hyperliquid orders, otherwise `null`. */
  hyperliquid: TradingHyperliquidOrder | null;
  /** Trading order ID, prefixed `trdord_`. */
  id: string;
  /** Market symbol on the provider, such as `ETH`. */
  market: string;
  object: TradingOrderObject;
  order_type: TradingOrderOrderType;
  /** Size when the order was placed, as a decimal string, or `null` when the provider omits it. */
  original_size: string | null;
  /** Limit price in USD. */
  price: Money;
  /** The provider's own order ID, as a string. */
  provider_order_id: string | null;
  side: TradingOrderSide;
  /** Remaining order size as a decimal string. */
  size: string;
  status: TradingOrderStatus;
  /** When the status last changed, as an ISO 8601 timestamp, or `null` when the provider omits it. */
  status_updated_at: string | null;
  /** How long the order stays active. `null` when the provider omits it or reports a policy outside the supported values. */
  time_in_force: TradingOrderTimeInForce | null;
}
export const TradingOrder = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    client_order_id: S.NullOr(S.String),
    created_at: S.NullOr(S.String),
    hyperliquid: S.NullOr(TradingHyperliquidOrder),
    id: S.String,
    market: S.String,
    object: TradingOrderObject,
    order_type: TradingOrderOrderType,
    original_size: S.NullOr(S.String),
    price: Money,
    provider_order_id: S.NullOr(S.String),
    side: TradingOrderSide,
    size: S.String,
    status: TradingOrderStatus,
    status_updated_at: S.NullOr(S.String),
    time_in_force: S.NullOr(TradingOrderTimeInForce),
  }),
).annotate({ identifier: "TradingOrder" }) as any as S.Schema<TradingOrder>;

export type TradingAccountOpenOrdersList = Array<TradingOrder>;
export const TradingAccountOpenOrdersList = /*@__PURE__*/ S.Array(
  TradingOrder,
) as any as S.Schema<TradingAccountOpenOrdersList>;

export interface TradingCumulativeFunding {
  /** Funding paid on this market across the account's history, in USD, or `null` when unavailable. */
  all_time: Money | null;
  /** Funding paid since the position size last changed, in USD, or `null` when unavailable. */
  since_change: Money | null;
  /** Funding paid since the position opened, in USD, or `null` when unavailable. */
  since_open: Money | null;
}
export const TradingCumulativeFunding = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    all_time: S.NullOr(Money),
    since_change: S.NullOr(Money),
    since_open: S.NullOr(Money),
  }),
).annotate({ identifier: "TradingCumulativeFunding" }) as any as S.Schema<TradingCumulativeFunding>;

/** `cross` shares margin across positions; `isolated` limits margin to this position. */
export type TradingPositionLeverageType = "cross" | "isolated";
export const TradingPositionLeverageType = S.String;

export interface TradingPositionLeverage {
  /** `cross` shares margin across positions; `isolated` limits margin to this position. */
  type: TradingPositionLeverageType;
  /** Multiplier applied to the position's margin, such as `10` for 10x. */
  value: number;
}
export const TradingPositionLeverage = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: TradingPositionLeverageType,
    value: S.Number,
  }),
).annotate({ identifier: "TradingPositionLeverage" }) as any as S.Schema<TradingPositionLeverage>;

export interface TradingHyperliquidPosition {
  /** Funding paid on the position over several windows, in USD. */
  cumulative_funding: TradingCumulativeFunding;
  /** Margin mode and multiplier for the position. */
  leverage: TradingPositionLeverage;
  /** Estimated liquidation price in USD, or `null` when Hyperliquid reports none. */
  liquidation_price: Money | null;
  /** Margin allocated to the position, in USD. */
  margin_used: Money;
  /** Return on equity as a decimal ratio string, such as `0.1` for 10%. */
  return_on_equity: string;
}
export const TradingHyperliquidPosition = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    cumulative_funding: TradingCumulativeFunding,
    leverage: TradingPositionLeverage,
    liquidation_price: S.NullOr(Money),
    margin_used: Money,
    return_on_equity: S.String,
  }),
).annotate({
  identifier: "TradingHyperliquidPosition",
}) as any as S.Schema<TradingHyperliquidPosition>;

export type TradingPositionObject = "trading_position";
export const TradingPositionObject = S.String;

export type TradingPositionSide = "long" | "short";
export const TradingPositionSide = S.String;

export interface TradingPosition {
  /** Average entry price in USD, or `null` when the provider omits it. */
  entry_price: Money | null;
  /** Hyperliquid perpetual details. Present on Hyperliquid positions, otherwise `null`. */
  hyperliquid: TradingHyperliquidPosition | null;
  /** Trading position ID, prefixed `trdpos_`. Stable for a market within one trading account. */
  id: string;
  /** Market symbol on the provider, such as `ETH`. */
  market: string;
  object: TradingPositionObject;
  /** Current position value in USD. */
  position_value: Money;
  side: TradingPositionSide;
  /** Absolute position size as a decimal string. */
  size: string;
  /** Unrealized profit or loss in USD. Negative for a loss. */
  unrealized_pnl: Money;
}
export const TradingPosition = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    entry_price: S.NullOr(Money),
    hyperliquid: S.NullOr(TradingHyperliquidPosition),
    id: S.String,
    market: S.String,
    object: TradingPositionObject,
    position_value: Money,
    side: TradingPositionSide,
    size: S.String,
    unrealized_pnl: Money,
  }),
).annotate({ identifier: "TradingPosition" }) as any as S.Schema<TradingPosition>;

export type TradingAccountPositionsList = Array<TradingPosition>;
export const TradingAccountPositionsList = /*@__PURE__*/ S.Array(
  TradingPosition,
) as any as S.Schema<TradingAccountPositionsList>;

/** Trading venue that holds the positions and orders. */
export type TradingAccountProvider = "hyperliquid";
export const TradingAccountProvider = S.String;

export interface TradingAccount {
  /** The account that owns this trading account, prefixed `biz_`. `null` when a user owns it. */
  account_id: string | null;
  /** Hyperliquid-specific state. Present when `provider` is `hyperliquid`, otherwise `null`. */
  hyperliquid: TradingHyperliquidAccount | null;
  /** The Whop wallet ID backing this trading account, prefixed `cwal_`. */
  id: string;
  object: TradingAccountObject;
  open_orders: TradingAccountOpenOrdersList;
  positions: TradingAccountPositionsList;
  /** Trading venue that holds the positions and orders. */
  provider: TradingAccountProvider;
  /** The user who owns this trading account, prefixed `user_`. `null` when an account owns it. */
  user_id: string | null;
}
export const TradingAccount = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.NullOr(S.String),
    hyperliquid: S.NullOr(TradingHyperliquidAccount),
    id: S.String,
    object: TradingAccountObject,
    open_orders: TradingAccountOpenOrdersList,
    positions: TradingAccountPositionsList,
    provider: TradingAccountProvider,
    user_id: S.NullOr(S.String),
  }),
).annotate({ identifier: "TradingAccount" }) as any as S.Schema<TradingAccount>;

export interface User {
  /** The user's balance: personal cash + crypto + in-flight treasury deposits, plus account balances for accounts they own. Computed only on the self view (retrieved with the reserved id `me`) for callers with balance-read scope; `null` otherwise, or when `include_balance=false`. */
  balance: UserBalance | null;
  /** The user's cumulative wallet balance over time (USD `{ t, v }` points plus last/min/max), for the balance chart. Opt in with `include_balance_history=true` when retrieving yourself with the reserved id `me`; populated only for callers with balance-read scope and `null` otherwise. A user with no wallet activity returns an empty series. */
  balance_history: UserBalanceHistory | null;
  /** The user's profile banner wrapper. `null` when the user has no banner. */
  banner: UserBanner | null;
  /** The user's biography */
  bio: string | null;
  /** When the user was created, as an ISO 8601 timestamp */
  created_at: string;
  /** The user's gross USD income over time, including a Partner commission breakdown. Populated only on single-user self reads for callers with balance-read scope; `null` otherwise. */
  earnings_usd: UserEarnings | null;
  /** The user's email address. Populated only on the self view (retrieved with the reserved id `me`) for callers with email-read scope; `null` otherwise, or while the account has no confirmed email yet. */
  email: string | null;
  /** User ID, prefixed `user_`. */
  id: string;
  /** The user's display name */
  name: string | null;
  /** Avatar wrapper; its `url` is always present, using a generated placeholder when the user set no picture. */
  profile_picture: UserProfilePicture;
  social_accounts: UserSocialAccountsList;
  /** Whop staff access flags. Populated only on the self view (retrieved with the reserved id `me`) for callers with staff-read scope; `null` there for every user who is not Whop staff, and always `null` elsewhere. */
  staff: UserStaffAccess | null;
  /** Live trading state. Opt in with `include_trading=true` when retrieving `me`; `null` otherwise, without trading permission, or without an Ethereum wallet. Provider failures return an error, not a zero balance. */
  trading: TradingAccount | null;
  /** The user's unique username */
  username: string;
  /** Identity verification status for the user's `individual` (KYC) and `business` (KYB) profiles. Each is `null` until created, otherwise a `status` of `not_started`, `pending`, `approved`, or `rejected`. */
  verification: unknown;
  /** When the user became an enrolled Whop Partner, as an ISO 8601 timestamp. `null` if never enrolled. */
  whop_partner_enabled_at: string | null;
}
export const User = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    balance: S.NullOr(UserBalance),
    balance_history: S.NullOr(UserBalanceHistory),
    banner: S.NullOr(UserBanner),
    bio: S.NullOr(S.String),
    created_at: S.String,
    earnings_usd: S.NullOr(UserEarnings),
    email: S.NullOr(S.String),
    id: S.String,
    name: S.NullOr(S.String),
    profile_picture: UserProfilePicture,
    social_accounts: UserSocialAccountsList,
    staff: S.NullOr(UserStaffAccess),
    trading: S.NullOr(TradingAccount),
    username: S.String,
    verification: S.Unknown,
    whop_partner_enabled_at: S.NullOr(S.String),
  }),
).annotate({ identifier: "User" }) as any as S.Schema<User>;

export interface GetUserPreferencesRequest {}
export const GetUserPreferencesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/users/me/preferences", code: 200 })),
).annotate({
  identifier: "GetUserPreferencesRequest",
}) as any as S.Schema<GetUserPreferencesRequest>;

export interface UserPreferences {
  /** Whether the user has dismissed the first-time bounty worker onboarding. Set to `false` to show it again. */
  bounty_worker_onboarding_dismissed: boolean;
  /** Whether investigation mode is enabled for the user. Only meaningful for staff users with investigation access. */
  investigation_enabled: boolean;
  /** Whether the user has accepted Whop's terms and policies. `false` until recorded via `PATCH` with `terms_accepted: true`. */
  terms_accepted: boolean;
  /** When the user most recently accepted Whop's terms and policies, as an ISO 8601 timestamp. `null` until accepted. */
  terms_accepted_at: string | null;
}
export const UserPreferences = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    bounty_worker_onboarding_dismissed: S.Boolean,
    investigation_enabled: S.Boolean,
    terms_accepted: S.Boolean,
    terms_accepted_at: S.NullOr(S.String),
  }),
).annotate({ identifier: "UserPreferences" }) as any as S.Schema<UserPreferences>;

export type ListOauthGrantsRequestOrder = "created_at";
export const ListOauthGrantsRequestOrder = S.String;

export type ListOauthGrantsRequestDirection = "asc" | "desc";
export const ListOauthGrantsRequestDirection = S.String;

export interface ListOauthGrantsRequest {
  /** Only return grants for this app, prefixed `app_`. An app the user has never authorized returns an empty list. */
  app_id?: string;
  /** Number of results to return from the start of the range. */
  first?: number;
  /** Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page. */
  after?: string;
  /** Number of results to return from the end of the range. */
  last?: number;
  /** Return results before this cursor. Use `page_info.start_cursor` from the previous response to fetch the previous page. */
  before?: string;
  /** The field to sort grants by. */
  order?: ListOauthGrantsRequestOrder | (string & {});
  /** Sort direction. */
  direction?: ListOauthGrantsRequestDirection | (string & {});
}
export const ListOauthGrantsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    app_id: S.optional(S.String.pipe(T.Query())),
    first: S.optional(S.Number.pipe(T.Query())),
    after: S.optional(S.String.pipe(T.Query())),
    last: S.optional(S.Number.pipe(T.Query())),
    before: S.optional(S.String.pipe(T.Query())),
    order: S.optional(ListOauthGrantsRequestOrder.pipe(T.Query())),
    direction: S.optional(ListOauthGrantsRequestDirection.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/users/me/oauth_grants", code: 200 })),
).annotate({ identifier: "ListOauthGrantsRequest" }) as any as S.Schema<ListOauthGrantsRequest>;

export type ListOauthGrantsResponseDataList = Array<OauthGrant>;
export const ListOauthGrantsResponseDataList = /*@__PURE__*/ S.Array(
  OauthGrant,
) as any as S.Schema<ListOauthGrantsResponseDataList>;

export interface ListOauthGrantsResponsePageInfo {
  end_cursor: string | null;
  has_next_page: boolean;
  has_previous_page: boolean;
  start_cursor: string | null;
}
export const ListOauthGrantsResponsePageInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    end_cursor: S.NullOr(S.String),
    has_next_page: S.Boolean,
    has_previous_page: S.Boolean,
    start_cursor: S.NullOr(S.String),
  }),
).annotate({
  identifier: "ListOauthGrantsResponsePageInfo",
}) as any as S.Schema<ListOauthGrantsResponsePageInfo>;

export interface ListOauthGrantsResponse {
  data: ListOauthGrantsResponseDataList;
  page_info: ListOauthGrantsResponsePageInfo;
}
export const ListOauthGrantsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: ListOauthGrantsResponseDataList,
    page_info: ListOauthGrantsResponsePageInfo,
  }),
).annotate({ identifier: "ListOauthGrantsResponse" }) as any as S.Schema<ListOauthGrantsResponse>;

export type ListPasskeysRequestOrder = "created_at";
export const ListPasskeysRequestOrder = S.String;

export type ListPasskeysRequestDirection = "asc" | "desc";
export const ListPasskeysRequestDirection = S.String;

export interface ListPasskeysRequest {
  /** Number of results to return from the start of the range. */
  first?: number;
  /** Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page. */
  after?: string;
  /** Number of results to return from the end of the range. */
  last?: number;
  /** Return results before this cursor. Use `page_info.start_cursor` from the previous response to fetch the previous page. */
  before?: string;
  /** The field to sort passkeys by. */
  order?: ListPasskeysRequestOrder | (string & {});
  /** Sort direction. */
  direction?: ListPasskeysRequestDirection | (string & {});
}
export const ListPasskeysRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    first: S.optional(S.Number.pipe(T.Query())),
    after: S.optional(S.String.pipe(T.Query())),
    last: S.optional(S.Number.pipe(T.Query())),
    before: S.optional(S.String.pipe(T.Query())),
    order: S.optional(ListPasskeysRequestOrder.pipe(T.Query())),
    direction: S.optional(ListPasskeysRequestDirection.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/users/me/passkeys", code: 200 })),
).annotate({ identifier: "ListPasskeysRequest" }) as any as S.Schema<ListPasskeysRequest>;

export type ListPasskeysResponseDataList = Array<Passkey>;
export const ListPasskeysResponseDataList = /*@__PURE__*/ S.Array(
  Passkey,
) as any as S.Schema<ListPasskeysResponseDataList>;

export type ListPasskeysResponsePageInfo = ListOauthGrantsResponsePageInfo;
export const ListPasskeysResponsePageInfo = ListOauthGrantsResponsePageInfo;

export interface ListPasskeysResponse {
  data: ListPasskeysResponseDataList;
  page_info: ListOauthGrantsResponsePageInfo;
}
export const ListPasskeysResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: ListPasskeysResponseDataList,
    page_info: ListOauthGrantsResponsePageInfo,
  }),
).annotate({ identifier: "ListPasskeysResponse" }) as any as S.Schema<ListPasskeysResponse>;

export interface ListUserNotificationExperiencePreferencesRequest {
  /** Number of results to return from the start of the range. */
  first?: number;
  /** Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page. */
  after?: string;
}
export const ListUserNotificationExperiencePreferencesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    first: S.optional(S.Number.pipe(T.Query())),
    after: S.optional(S.String.pipe(T.Query())),
  }).pipe(
    T.Http({ method: "GET", uri: "/users/me/preferences/notifications/experiences", code: 200 }),
  ),
).annotate({
  identifier: "ListUserNotificationExperiencePreferencesRequest",
}) as any as S.Schema<ListUserNotificationExperiencePreferencesRequest>;

/** What the user is notified about in the experience: `all` notifications, only `mentions`, or `nothing`. */
export type ExperienceNotificationPreferenceLevel = "all" | "mentions" | "nothing";
export const ExperienceNotificationPreferenceLevel = S.String;

/** The type of object. Always `experience_notification_preference`. */
export type ExperienceNotificationPreferenceObject = "experience_notification_preference";
export const ExperienceNotificationPreferenceObject = S.String;

/** Delivery channel the preference applies to. `null` applies to every channel. */
export type NotificationPreferenceScopeChannel = "in_app" | "mobile";
export const NotificationPreferenceScopeChannel = S.String;

export interface NotificationPreferenceScope {
  /** Account the preference is scoped to (member notifications), prefixed `biz_`. */
  account_id: string | null;
  /** Delivery channel the preference applies to. `null` applies to every channel. */
  channel: NotificationPreferenceScopeChannel | null;
  /** Experience the preference is scoped to, prefixed `exp_`. */
  experience_id: string | null;
  /** Account whose team notifications the preference is scoped to, prefixed `biz_`. */
  team_account_id: string | null;
  /** Notification topic the preference is scoped to, prefixed `topic_`. */
  topic_id: string | null;
}
export const NotificationPreferenceScope = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.NullOr(S.String),
    channel: S.NullOr(NotificationPreferenceScopeChannel),
    experience_id: S.NullOr(S.String),
    team_account_id: S.NullOr(S.String),
    topic_id: S.NullOr(S.String),
  }),
).annotate({
  identifier: "NotificationPreferenceScope",
}) as any as S.Schema<NotificationPreferenceScope>;

export interface ExperienceNotificationPreference {
  /** What the user is notified about in the experience: `all` notifications, only `mentions`, or `nothing`. */
  level: ExperienceNotificationPreferenceLevel;
  /** The type of object. Always `experience_notification_preference`. */
  object: ExperienceNotificationPreferenceObject;
  /** What the preference applies to. Echo it back to `PATCH /users/me/preferences/notifications` to change this preference. */
  scope: NotificationPreferenceScope;
}
export const ExperienceNotificationPreference = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    level: ExperienceNotificationPreferenceLevel,
    object: ExperienceNotificationPreferenceObject,
    scope: NotificationPreferenceScope,
  }),
).annotate({
  identifier: "ExperienceNotificationPreference",
}) as any as S.Schema<ExperienceNotificationPreference>;

export type ListUserNotificationExperiencePreferencesResponseDataList =
  Array<ExperienceNotificationPreference>;
export const ListUserNotificationExperiencePreferencesResponseDataList = /*@__PURE__*/ S.Array(
  ExperienceNotificationPreference,
) as any as S.Schema<ListUserNotificationExperiencePreferencesResponseDataList>;

export type ListUserNotificationExperiencePreferencesResponsePageInfo =
  ListOauthGrantsResponsePageInfo;
export const ListUserNotificationExperiencePreferencesResponsePageInfo =
  ListOauthGrantsResponsePageInfo;

export interface ListUserNotificationExperiencePreferencesResponse {
  data: ListUserNotificationExperiencePreferencesResponseDataList;
  page_info: ListOauthGrantsResponsePageInfo;
}
export const ListUserNotificationExperiencePreferencesResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: ListUserNotificationExperiencePreferencesResponseDataList,
    page_info: ListOauthGrantsResponsePageInfo,
  }),
).annotate({
  identifier: "ListUserNotificationExperiencePreferencesResponse",
}) as any as S.Schema<ListUserNotificationExperiencePreferencesResponse>;

export type ListUserNotificationTopicPreferencesRequestChannel = "in_app" | "mobile";
export const ListUserNotificationTopicPreferencesRequestChannel = S.String;

export interface ListUserNotificationTopicPreferencesRequest {
  /** Only return preferences for this delivery channel (or not narrowed to a channel). */
  channel?: ListUserNotificationTopicPreferencesRequestChannel | (string & {});
  /** Only return preferences scoped to this account's member notifications (`biz_` tag). */
  account_id?: string;
  /** Only return preferences scoped to this account's team notifications (`biz_` tag). */
  team_account_id?: string;
  /** Only return preferences scoped to this experience (`exp_` tag). */
  experience_id?: string;
  /** Only return preferences scoped to this notification topic (`topic_` tag). */
  topic_id?: string;
  /** Number of results to return from the start of the range. */
  first?: number;
  /** Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page. */
  after?: string;
}
export const ListUserNotificationTopicPreferencesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    channel: S.optional(ListUserNotificationTopicPreferencesRequestChannel.pipe(T.Query())),
    account_id: S.optional(S.String.pipe(T.Query())),
    team_account_id: S.optional(S.String.pipe(T.Query())),
    experience_id: S.optional(S.String.pipe(T.Query())),
    topic_id: S.optional(S.String.pipe(T.Query())),
    first: S.optional(S.Number.pipe(T.Query())),
    after: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/users/me/preferences/notifications/topics", code: 200 })),
).annotate({
  identifier: "ListUserNotificationTopicPreferencesRequest",
}) as any as S.Schema<ListUserNotificationTopicPreferencesRequest>;

/** What the user is notified about in this scope: `all` or `nothing`. */
export type UserNotificationPreferenceLevel = "all" | "nothing";
export const UserNotificationPreferenceLevel = S.String;

/** The type of object. Always `notification_preference`. */
export type UserNotificationPreferenceObject = "notification_preference";
export const UserNotificationPreferenceObject = S.String;

export interface UserNotificationPreference {
  /** When the preference was created, as an ISO 8601 timestamp. */
  created_at: string;
  /** Notification preference ID, prefixed `unpf_`. */
  id: string;
  /** What the user is notified about in this scope: `all` or `nothing`. */
  level: UserNotificationPreferenceLevel;
  /** The type of object. Always `notification_preference`. */
  object: UserNotificationPreferenceObject;
  /** What the preference applies to. Echo it back to `PATCH /users/me/preferences/notifications` to change this preference. */
  scope: NotificationPreferenceScope;
  /** When the preference was last changed, as an ISO 8601 timestamp. */
  updated_at: string;
}
export const UserNotificationPreference = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    created_at: S.String,
    id: S.String,
    level: UserNotificationPreferenceLevel,
    object: UserNotificationPreferenceObject,
    scope: NotificationPreferenceScope,
    updated_at: S.String,
  }),
).annotate({
  identifier: "UserNotificationPreference",
}) as any as S.Schema<UserNotificationPreference>;

export type ListUserNotificationTopicPreferencesResponseDataList =
  Array<UserNotificationPreference>;
export const ListUserNotificationTopicPreferencesResponseDataList = /*@__PURE__*/ S.Array(
  UserNotificationPreference,
) as any as S.Schema<ListUserNotificationTopicPreferencesResponseDataList>;

export type ListUserNotificationTopicPreferencesResponsePageInfo = ListOauthGrantsResponsePageInfo;
export const ListUserNotificationTopicPreferencesResponsePageInfo = ListOauthGrantsResponsePageInfo;

export interface ListUserNotificationTopicPreferencesResponse {
  data: ListUserNotificationTopicPreferencesResponseDataList;
  page_info: ListOauthGrantsResponsePageInfo;
}
export const ListUserNotificationTopicPreferencesResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: ListUserNotificationTopicPreferencesResponseDataList,
    page_info: ListOauthGrantsResponsePageInfo,
  }),
).annotate({
  identifier: "ListUserNotificationTopicPreferencesResponse",
}) as any as S.Schema<ListUserNotificationTopicPreferencesResponse>;

export interface ListUserRecommendedActionsRequest {
  /** `me`, or the authenticated user's own `user_` tag or username. */
  id: string;
}
export const ListUserRecommendedActionsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/users/{id}/recommend_actions", code: 200 })),
).annotate({
  identifier: "ListUserRecommendedActionsRequest",
}) as any as S.Schema<ListUserRecommendedActionsRequest>;

/** The recommendation; new values may be added, so handle unknown actions gracefully */
export type UserRecommendedActionAction =
  | "create_business"
  | "become_affiliate"
  | "become_whop_partner"
  | "theme_business"
  | "create_product"
  | "create_plan"
  | "verify_identity"
  | "connect_affiliate_program"
  | "create_promotion"
  | "migrate_from_stripe"
  | "accept_first_payment"
  | "launch_first_ad"
  | "launch_draft_campaign"
  | "increase_ad_budget"
  | "refresh_ad_creatives"
  | "fix_ad_billing"
  | "exclude_customers_from_ads"
  | "retarget_abandoned_checkouts"
  | "fix_funnel_dropoff"
  | "invite_team_member"
  | "enable_tax_collection"
  | "create_card"
  | "apply_for_financing";
export const UserRecommendedActionAction = S.String;

export type UserRecommendedActionBlockedCapabilitiesList = Array<string>;
export const UserRecommendedActionBlockedCapabilitiesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<UserRecommendedActionBlockedCapabilitiesList>;

/** Always optional — never blocking */
export type UserRecommendedActionStatus = "optional";
export const UserRecommendedActionStatus = S.String;

export interface UserRecommendedAction {
  /** The account (`biz_`) a business recommendation is for, or `null` for personal recommendations */
  account_id: string | null;
  /** The account's display name, or `null` */
  account_name: string | null;
  /** The recommendation; new values may be added, so handle unknown actions gracefully */
  action: UserRecommendedActionAction;
  blocked_capabilities: UserRecommendedActionBlockedCapabilitiesList;
  /** The URL the call-to-action links to */
  cta: string;
  /** Button label */
  cta_label: string;
  /** Supporting copy, or empty */
  description: string;
  /** Illustration icon URL, or `null` */
  icon_url: string | null;
  /** Estimated impact from 0-100, or `null` when not ranked */
  impact_score: number | null;
  /** Why this action was recommended, or `null` */
  reasoning: string | null;
  /** Always optional — never blocking */
  status: UserRecommendedActionStatus;
  /** Headline for the recommendation */
  title: string;
}
export const UserRecommendedAction = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.NullOr(S.String),
    account_name: S.NullOr(S.String),
    action: UserRecommendedActionAction,
    blocked_capabilities: UserRecommendedActionBlockedCapabilitiesList,
    cta: S.String,
    cta_label: S.String,
    description: S.String,
    icon_url: S.NullOr(S.String),
    impact_score: S.NullOr(S.Number),
    reasoning: S.NullOr(S.String),
    status: UserRecommendedActionStatus,
    title: S.String,
  }),
).annotate({ identifier: "UserRecommendedAction" }) as any as S.Schema<UserRecommendedAction>;

export type ListUserRecommendedActionsResponseDataList = Array<UserRecommendedAction>;
export const ListUserRecommendedActionsResponseDataList = /*@__PURE__*/ S.Array(
  UserRecommendedAction,
) as any as S.Schema<ListUserRecommendedActionsResponseDataList>;

export interface ListUserRecommendedActionsResponse {
  data: ListUserRecommendedActionsResponseDataList;
}
export const ListUserRecommendedActionsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: ListUserRecommendedActionsResponseDataList,
  }),
).annotate({
  identifier: "ListUserRecommendedActionsResponse",
}) as any as S.Schema<ListUserRecommendedActionsResponse>;

export interface ListUsersRequest {
  /** A search term to filter users by name or username. */
  query?: string;
  /** Number of results to return from the start of the range. */
  first?: number;
  /** Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page. */
  after?: string;
  /** Number of results to return from the end of the range. */
  last?: number;
  /** Return results before this cursor. Use `page_info.start_cursor` from the previous response to fetch the previous page. */
  before?: string;
}
export const ListUsersRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    query: S.optional(S.String.pipe(T.Query())),
    first: S.optional(S.Number.pipe(T.Query())),
    after: S.optional(S.String.pipe(T.Query())),
    last: S.optional(S.Number.pipe(T.Query())),
    before: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/users", code: 200 })),
).annotate({ identifier: "ListUsersRequest" }) as any as S.Schema<ListUsersRequest>;

export type ListUsersResponseDataList = Array<User>;
export const ListUsersResponseDataList = /*@__PURE__*/ S.Array(
  User,
) as any as S.Schema<ListUsersResponseDataList>;

export type ListUsersResponsePageInfo = ListOauthGrantsResponsePageInfo;
export const ListUsersResponsePageInfo = ListOauthGrantsResponsePageInfo;

export interface ListUsersResponse {
  data: ListUsersResponseDataList;
  page_info: ListOauthGrantsResponsePageInfo;
}
export const ListUsersResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: ListUsersResponseDataList,
    page_info: ListOauthGrantsResponsePageInfo,
  }),
).annotate({ identifier: "ListUsersResponse" }) as any as S.Schema<ListUsersResponse>;

/** What the user is notified about in this scope. `mentions` is only valid for an experience level. `null` clears the preference. */
export type SetUserNotificationPreferencesRequestPreferencesItemLevel =
  | "all"
  | "mentions"
  | "nothing";
export const SetUserNotificationPreferencesRequestPreferencesItemLevel = S.String;

/** Delivery channel the preference applies to. Omit it (or pass `null`) to apply the preference to every channel. */
export type SetUserNotificationPreferencesRequestPreferencesItemScopeChannel = "in_app" | "mobile";
export const SetUserNotificationPreferencesRequestPreferencesItemScopeChannel = S.String;

/** What the preference applies to. `null` on a dimension means the preference is not narrowed there. */
export interface SetUserNotificationPreferencesRequestPreferencesItemScope {
  /** Account to scope the preference to (member notifications), `biz_` tag. */
  account_id?: string | null;
  /** Delivery channel the preference applies to. Omit it (or pass `null`) to apply the preference to every channel. */
  channel?: SetUserNotificationPreferencesRequestPreferencesItemScopeChannel | (string & {}) | null;
  /** Experience to scope the preference to (`exp_` tag). Requires `account_id` when a `topic_id` is also given. */
  experience_id?: string | null;
  /** Account whose team notifications the preference is scoped to, `biz_` tag. */
  team_account_id?: string | null;
  /** Notification topic to scope the preference to, `topic_` tag. */
  topic_id?: string | null;
}
export const SetUserNotificationPreferencesRequestPreferencesItemScope = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      account_id: S.optional(S.NullOr(S.String)),
      channel: S.optional(
        S.NullOr(SetUserNotificationPreferencesRequestPreferencesItemScopeChannel),
      ),
      experience_id: S.optional(S.NullOr(S.String)),
      team_account_id: S.optional(S.NullOr(S.String)),
      topic_id: S.optional(S.NullOr(S.String)),
    }),
).annotate({
  identifier: "SetUserNotificationPreferencesRequestPreferencesItemScope",
}) as any as S.Schema<SetUserNotificationPreferencesRequestPreferencesItemScope>;

export interface SetUserNotificationPreferencesRequestPreferencesItem {
  /** What the user is notified about in this scope. `mentions` is only valid for an experience level. `null` clears the preference. */
  level: SetUserNotificationPreferencesRequestPreferencesItemLevel | (string & {}) | null;
  /** What the preference applies to. `null` on a dimension means the preference is not narrowed there. */
  scope: SetUserNotificationPreferencesRequestPreferencesItemScope;
}
export const SetUserNotificationPreferencesRequestPreferencesItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    level: S.NullOr(SetUserNotificationPreferencesRequestPreferencesItemLevel),
    scope: SetUserNotificationPreferencesRequestPreferencesItemScope,
  }),
).annotate({
  identifier: "SetUserNotificationPreferencesRequestPreferencesItem",
}) as any as S.Schema<SetUserNotificationPreferencesRequestPreferencesItem>;

/** The preferences to set, at most 100 per request. */
export type SetUserNotificationPreferencesRequestPreferencesList =
  Array<SetUserNotificationPreferencesRequestPreferencesItem>;
export const SetUserNotificationPreferencesRequestPreferencesList = /*@__PURE__*/ S.Array(
  SetUserNotificationPreferencesRequestPreferencesItem,
) as any as S.Schema<SetUserNotificationPreferencesRequestPreferencesList>;

export interface SetUserNotificationPreferencesRequest {
  /** The preferences to set, at most 100 per request. */
  preferences: SetUserNotificationPreferencesRequestPreferencesList;
}
export const SetUserNotificationPreferencesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    preferences: SetUserNotificationPreferencesRequestPreferencesList,
  }).pipe(T.Http({ method: "PATCH", uri: "/users/me/preferences/notifications", code: 200 })),
).annotate({
  identifier: "SetUserNotificationPreferencesRequest",
}) as any as S.Schema<SetUserNotificationPreferencesRequest>;

/** What the user is now notified about in this scope, or `null` if the preference was cleared and the scope inherits its default again. */
export type NotificationPreferenceStateLevel = "all" | "mentions" | "nothing";
export const NotificationPreferenceStateLevel = S.String;

/** Which kind of preference was written: `experience_notification_preference` for an experience level, `notification_preference` for a topic override. */
export type NotificationPreferenceStateObject =
  | "notification_preference"
  | "experience_notification_preference";
export const NotificationPreferenceStateObject = S.String;

export interface NotificationPreferenceState {
  /** What the user is now notified about in this scope, or `null` if the preference was cleared and the scope inherits its default again. */
  level: NotificationPreferenceStateLevel | null;
  /** Which kind of preference was written: `experience_notification_preference` for an experience level, `notification_preference` for a topic override. */
  object: NotificationPreferenceStateObject;
  /** The scope that was written, resolved. `null` on a dimension means the preference is not narrowed there. */
  scope: NotificationPreferenceScope;
}
export const NotificationPreferenceState = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    level: S.NullOr(NotificationPreferenceStateLevel),
    object: NotificationPreferenceStateObject,
    scope: NotificationPreferenceScope,
  }),
).annotate({
  identifier: "NotificationPreferenceState",
}) as any as S.Schema<NotificationPreferenceState>;

export type SetUserNotificationPreferencesResponseDataList = Array<NotificationPreferenceState>;
export const SetUserNotificationPreferencesResponseDataList = /*@__PURE__*/ S.Array(
  NotificationPreferenceState,
) as any as S.Schema<SetUserNotificationPreferencesResponseDataList>;

export interface SetUserNotificationPreferencesResponse {
  data: SetUserNotificationPreferencesResponseDataList;
}
export const SetUserNotificationPreferencesResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: SetUserNotificationPreferencesResponseDataList,
  }),
).annotate({
  identifier: "SetUserNotificationPreferencesResponse",
}) as any as S.Schema<SetUserNotificationPreferencesResponse>;

export interface UpdateUserRequestBanner {
  direct_upload_id?: string;
  id?: string;
}
export const UpdateUserRequestBanner = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    direct_upload_id: S.optional(S.String),
    id: S.optional(S.String),
  }),
).annotate({ identifier: "UpdateUserRequestBanner" }) as any as S.Schema<UpdateUserRequestBanner>;

export type UpdateUserRequestProfilePicture = UpdateUserRequestBanner;
export const UpdateUserRequestProfilePicture = UpdateUserRequestBanner;

export interface UpdateUserRequest {
  /** User ID (prefixed `user_`), username, or `me` for the authenticated user. */
  id: string;
  /** The account whose profile override to update. Required for API key callers. */
  account_id?: string;
  banner?: UpdateUserRequestBanner | null;
  bio?: string;
  name?: string;
  profile_picture?: UpdateUserRequestBanner;
  username?: string;
}
export const UpdateUserRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
    account_id: S.optional(S.String.pipe(T.Query())),
    banner: S.optional(S.NullOr(UpdateUserRequestBanner)),
    bio: S.optional(S.String),
    name: S.optional(S.String),
    profile_picture: S.optional(UpdateUserRequestBanner),
    username: S.optional(S.String),
  }).pipe(T.Http({ method: "PATCH", uri: "/users/{id}", code: 200 })),
).annotate({ identifier: "UpdateUserRequest" }) as any as S.Schema<UpdateUserRequest>;

export interface UpdateUserPreferencesRequest {
  /** Whether the user has dismissed the first-time bounty worker onboarding. Set to `false` to show it again. */
  bounty_worker_onboarding_dismissed?: boolean;
  /** Whether investigation mode is enabled for the user. Only meaningful for staff users with investigation access. */
  investigation_enabled?: boolean;
  /** Records the user's acceptance of Whop's terms and policies. Only `true` is accepted — the server stamps `terms_accepted_at` and acceptance cannot be withdrawn here. */
  terms_accepted?: boolean;
}
export const UpdateUserPreferencesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    bounty_worker_onboarding_dismissed: S.optional(S.Boolean),
    investigation_enabled: S.optional(S.Boolean),
    terms_accepted: S.optional(S.Boolean),
  }).pipe(T.Http({ method: "PATCH", uri: "/users/me/preferences", code: 200 })),
).annotate({
  identifier: "UpdateUserPreferencesRequest",
}) as any as S.Schema<UpdateUserPreferencesRequest>;

export type CheckUserAccessError = WhopOpError;
/** Check User Access Checks whether a user has access to an account, product, or experience the caller can reach. */
export const checkUserAccess: API.OperationMethod<
  CheckUserAccessRequest,
  CheckUserAccessResponse,
  CheckUserAccessError,
  WhopOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CheckUserAccessRequest,
  output: CheckUserAccessResponse,
  errors: [],
  protocol: WhopProtocol,
  retry: Retry.Retry,
}));

export type CreateOauthGrantError = BadRequest | Forbidden | NotFound | Conflict | WhopOpError;
/** Authorize an App Completes the OAuth authorization step for the authenticated user: records their consent for the scopes an app asked for and mints the authorization code to hand back to it. Returns the grant, plus a `redirect_url` carrying that code — the one and only time it is returned. Exchange the code at `POST /oauth/token` with the verifier for `code_challenge`. Requires a user session, because consent has to come from the account holder: an API key or an OAuth token is refused, so an app can never authorize itself. Send an `Idempotency-Key` to make a retry safe — a replay returns the original `redirect_url` and its code rather than issuing a second one. */
export const createOauthGrant: API.OperationMethod<
  CreateOauthGrantRequest,
  OauthGrant,
  CreateOauthGrantError,
  WhopOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateOauthGrantRequest,
  output: OauthGrant,
  errors: [BadRequest, Forbidden, NotFound, Conflict],
  protocol: WhopProtocol,
  retry: Retry.Retry,
}));

export type CreatePasskeyError = BadRequest | Forbidden | Conflict | WhopOpError;
/** Register Registers a passkey for the authenticated user from the attestation a browser produced for a `registration` challenge. Mint that challenge first with `POST /users/me/passkeys/challenge`; it is single-use and expires 5 minutes after it is issued. Requires a user session. */
export const createPasskey: API.OperationMethod<
  CreatePasskeyRequest,
  Passkey,
  CreatePasskeyError,
  WhopOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreatePasskeyRequest,
  output: Passkey,
  errors: [BadRequest, Forbidden, Conflict],
  protocol: WhopProtocol,
  retry: Retry.Retry,
}));

export type CreatePasskeyChallengeError =
  | BadRequest
  | Forbidden
  | NotFound
  | Conflict
  | WhopOpError;
/** Create Challenge Mints the challenge a browser needs to run a WebAuthn ceremony against the authenticated user's own passkeys. A `registration` challenge enrolls a new passkey; a `deletion` challenge is bound to the one passkey named by `passkey_id` and proves the user still holds it. Challenges are single-use and expire 5 minutes after they are issued, so send a fresh `Idempotency-Key` per ceremony — a replayed key returns the original challenge, which may already have expired. Requires a user session. */
export const createPasskeyChallenge: API.OperationMethod<
  CreatePasskeyChallengeRequest,
  CreatePasskeyChallengeResponse,
  CreatePasskeyChallengeError,
  WhopOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreatePasskeyChallengeRequest,
  output: CreatePasskeyChallengeResponse,
  errors: [BadRequest, Forbidden, NotFound, Conflict],
  protocol: WhopProtocol,
  retry: Retry.Retry,
}));

export type DeletePasskeyError = BadRequest | Forbidden | NotFound | WhopOpError;
/** Delete Deletes one of the authenticated user's own passkeys. The request body carries a WebAuthn assertion from the passkey being deleted, so possession of the credential is proven before it is removed: mint a `deletion` challenge for it first, run the ceremony with that passkey, and send the result here. Deleting the user's last passkey is allowed — their other step-up factors remain. Requires a user session. */
export const deletePasskey: API.OperationMethod<
  DeletePasskeyRequest,
  DeletePasskeyResponse,
  DeletePasskeyError,
  WhopOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeletePasskeyRequest,
  output: DeletePasskeyResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: WhopProtocol,
  retry: Retry.Retry,
}));

export type GetUserError = NotFound | WhopOpError;
/** Retrieve User Retrieves a user by `user_` tag or username, or the authenticated user with the reserved id `me`. Profiles include linked social accounts — reading your own profile returns every linked account, other profiles only what is public on Whop (the primary Discord and the X account). The self-only fields are populated only when the id is `me`: `email` (email-read scope), `staff` (Whop staff only, staff-read scope), `balance` and `earnings_usd` (balance-read scope), and the opt-in `balance_history`. They are always `null` when addressing a user by tag or username. */
export const getUser: API.OperationMethod<GetUserRequest, User, GetUserError, WhopOpContext> =
  /*@__PURE__*/ API.make(() => ({
    input: GetUserRequest,
    output: User,
    errors: [NotFound],
    protocol: WhopProtocol,
    retry: Retry.Retry,
  }));

export type GetUserPreferencesError = WhopOpError;
/** Retrieve Retrieves the authenticated user's settings document. Addressed only as `me` — the document always belongs to the session user. */
export const getUserPreferences: API.OperationMethod<
  GetUserPreferencesRequest,
  UserPreferences,
  GetUserPreferencesError,
  WhopOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetUserPreferencesRequest,
  output: UserPreferences,
  errors: [],
  protocol: WhopProtocol,
  retry: Retry.Retry,
}));

export type ListOauthGrantsError = BadRequest | Forbidden | WhopOpError;
/** List OAuth Grants Lists the authenticated user's own OAuth grants — one per app they have authorized, per account they authorized it for. The list is always the caller's own; there is no parameter for reading another user's grants. Requires a user session: an API key or an OAuth token is refused, so an app can never enumerate the other apps a user has authorized. */
export const listOauthGrants: API.PaginatedOperationMethod<
  ListOauthGrantsRequest,
  ListOauthGrantsResponse,
  ListOauthGrantsError,
  WhopOpContext,
  OauthGrant
> = /*@__PURE__*/ API.makePaginated(
  () => ({
    input: ListOauthGrantsRequest,
    output: ListOauthGrantsResponse,
    errors: [BadRequest, Forbidden],
    protocol: WhopProtocol,
    retry: Retry.Retry,
    pagination: {
      mode: "relay",
      inputToken: "after",
      outputToken: "page_info.end_cursor",
      hasNextPage: "page_info.has_next_page",
      items: "data",
      pageSize: "first",
    } as const,
  }),
  paginateRelay,
) as any;

export type ListPasskeysError = BadRequest | Forbidden | WhopOpError;
/** List Lists the authenticated user's own passkeys, newest first. The list is always the caller's own; there is no parameter for reading another user's passkeys. Requires a user session: an API key or an OAuth token is refused, because a passkey confirms the account holder before a sensitive action and no app may enumerate one. */
export const listPasskeys: API.PaginatedOperationMethod<
  ListPasskeysRequest,
  ListPasskeysResponse,
  ListPasskeysError,
  WhopOpContext,
  Passkey
> = /*@__PURE__*/ API.makePaginated(
  () => ({
    input: ListPasskeysRequest,
    output: ListPasskeysResponse,
    errors: [BadRequest, Forbidden],
    protocol: WhopProtocol,
    retry: Retry.Retry,
    pagination: {
      mode: "relay",
      inputToken: "after",
      outputToken: "page_info.end_cursor",
      hasNextPage: "page_info.has_next_page",
      items: "data",
      pageSize: "first",
    } as const,
  }),
  paginateRelay,
) as any;

export type ListUserNotificationExperiencePreferencesError = WhopOpError;
/** List Experiences Lists the authenticated user's per-experience notification levels. Experiences the user never set a level for are omitted — their effective level is `all`. */
export const listUserNotificationExperiencePreferences: API.PaginatedOperationMethod<
  ListUserNotificationExperiencePreferencesRequest,
  ListUserNotificationExperiencePreferencesResponse,
  ListUserNotificationExperiencePreferencesError,
  WhopOpContext,
  ExperienceNotificationPreference
> = /*@__PURE__*/ API.makePaginated(
  () => ({
    input: ListUserNotificationExperiencePreferencesRequest,
    output: ListUserNotificationExperiencePreferencesResponse,
    errors: [],
    protocol: WhopProtocol,
    retry: Retry.Retry,
    pagination: {
      mode: "relay",
      inputToken: "after",
      outputToken: "page_info.end_cursor",
      hasNextPage: "page_info.has_next_page",
      items: "data",
      pageSize: "first",
    } as const,
  }),
  paginateRelay,
) as any;

export type ListUserNotificationTopicPreferencesError = WhopOpError;
/** List Topics Lists the authenticated user's topic-scoped notification preferences, plus user-agnostic platform defaults. Each filter matches preferences scoped to its value or not narrowed on that dimension. Per-experience levels are listed separately, by `GET /users/me/preferences/notifications/experiences`. */
export const listUserNotificationTopicPreferences: API.PaginatedOperationMethod<
  ListUserNotificationTopicPreferencesRequest,
  ListUserNotificationTopicPreferencesResponse,
  ListUserNotificationTopicPreferencesError,
  WhopOpContext,
  UserNotificationPreference
> = /*@__PURE__*/ API.makePaginated(
  () => ({
    input: ListUserNotificationTopicPreferencesRequest,
    output: ListUserNotificationTopicPreferencesResponse,
    errors: [],
    protocol: WhopProtocol,
    retry: Retry.Retry,
    pagination: {
      mode: "relay",
      inputToken: "after",
      outputToken: "page_info.end_cursor",
      hasNextPage: "page_info.has_next_page",
      items: "data",
      pageSize: "first",
    } as const,
  }),
  paginateRelay,
) as any;

export type ListUserRecommendedActionsError = Forbidden | WhopOpError;
/** List Recommended Actions Lists the recommended actions computed for the user: personal suggestions (e.g. start a business or become an affiliate) pooled with the highest-impact actions across the accounts the user owns. Business actions are tagged with their `account_id`/`account_name`; personal actions leave those `null`. Self-only: `id` must be `me` or the authenticated user's own tag/username. */
export const listUserRecommendedActions: API.OperationMethod<
  ListUserRecommendedActionsRequest,
  ListUserRecommendedActionsResponse,
  ListUserRecommendedActionsError,
  WhopOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListUserRecommendedActionsRequest,
  output: ListUserRecommendedActionsResponse,
  errors: [Forbidden],
  protocol: WhopProtocol,
  retry: Retry.Retry,
}));

export type ListUsersError = WhopOpError;
/** List Users Search for users by name or username, ranked by social proximity to the authenticated user. Returns the user's most recently followed users when no query is given. */
export const listUsers: API.PaginatedOperationMethod<
  ListUsersRequest,
  ListUsersResponse,
  ListUsersError,
  WhopOpContext,
  User
> = /*@__PURE__*/ API.makePaginated(
  () => ({
    input: ListUsersRequest,
    output: ListUsersResponse,
    errors: [],
    protocol: WhopProtocol,
    retry: Retry.Retry,
    pagination: {
      mode: "relay",
      inputToken: "after",
      outputToken: "page_info.end_cursor",
      hasNextPage: "page_info.has_next_page",
      items: "data",
      pageSize: "first",
    } as const,
  }),
  paginateRelay,
) as any;

export type SetUserNotificationPreferencesError = BadRequest | NotFound | WhopOpError;
/** Set Sets the authenticated user's notification preferences. Each preference is addressed by `scope`, not by id, so a scope read back from either list endpoint can be sent straight here. A scope naming an experience with no topic sets that experience's level, and accepts all three levels. Any other scope sets a topic override, which is binary — `all` or `nothing`. A topic override with no `channel` applies to every delivery channel. `level: null` clears the preference. Preferences are stored as overrides, so clearing one means the scope inherits its default again rather than being switched off. The batch is applied in one transaction: if any entry is rejected, none are written. Experience levels are applied before topic overrides, because setting a level replaces every topic preference for that experience — so an override sent alongside a level wins. The response reports what each scope now resolves to, in the order the entries were sent. */
export const setUserNotificationPreferences: API.OperationMethod<
  SetUserNotificationPreferencesRequest,
  SetUserNotificationPreferencesResponse,
  SetUserNotificationPreferencesError,
  WhopOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SetUserNotificationPreferencesRequest,
  output: SetUserNotificationPreferencesResponse,
  errors: [BadRequest, NotFound],
  protocol: WhopProtocol,
  retry: Retry.Retry,
}));

export type UpdateUserError = WhopOpError;
/** Update User Updates a user, addressed by `user_` tag, username, or the reserved id `me` for the authenticated user. A user token updates their own global profile; an API key updates the user's account-specific profile override (account_id required). */
export const updateUser: API.OperationMethod<
  UpdateUserRequest,
  User,
  UpdateUserError,
  WhopOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateUserRequest,
  output: User,
  errors: [],
  protocol: WhopProtocol,
  retry: Retry.Retry,
}));

export type UpdateUserPreferencesError = BadRequest | WhopOpError;
/** Update Updates the authenticated user's settings document. Replaces the top-level keys it is given and leaves the rest untouched. */
export const updateUserPreferences: API.OperationMethod<
  UpdateUserPreferencesRequest,
  UserPreferences,
  UpdateUserPreferencesError,
  WhopOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateUserPreferencesRequest,
  output: UserPreferences,
  errors: [BadRequest],
  protocol: WhopProtocol,
  retry: Retry.Retry,
}));
