// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-freestyle/specs/openapi.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
import * as T from "../traits.ts";
import {
  FreestyleProtocol,
  type FreestyleOpError,
  type FreestyleOpContext,
} from "../protocol.ts";
import { paginateOffset } from "../pagination.ts";
import { UnknownFreestyleError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { FreestyleOpError, FreestyleOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Conflict
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Conflict>()("Conflict", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withConflictError),
    [{ status: 409 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

/** What a rule does with the traffic it matches. Only `allow` exists today, and it is required on every rule rather than defaulted: a default would mean that the day `deny` arrives, every rule written before it silently acquires an action it never stated. */
export type FirewallAction = "allow";
export const FirewallAction = S.String;

/** The transport a matcher is restricted to. */
export type FirewallProtocol = "tcp" | "udp" | "icmp";
export const FirewallProtocol = S.String;

/** One end of a rule: which traffic this side matches. Fields intersect — `{ vpcId, port, protocol }` is "traffic in that network, on that port, over that protocol". `vmId`/`vpcId`/`tunnelId` select by identity (the VM however it is addressed); `cidr`/`public` select by address. Unknown fields are rejected rather than ignored: a matcher is a security statement, and a typo'd `porrt: 22` that quietly became "every port" is the wrong failure. */
export interface FirewallEndpoint {
  /** An address range, IPv4 or IPv6, in canonical `network/prefix` form. */
  cidr?: string | null;
  /** A single port, 1–65535. Requires `protocol`. */
  port?: number | null;
  protocol?: FirewallProtocol | (string & {}) | null;
  /** Every publicly routable address, whoever owns it — including another Freestyle VM reached at its public address. Only `true` is meaningful; omit the field otherwise. Not combined with `vmId` or `vpcId`. */
  public?: boolean | null;
  /** Whatever is on the far side of one tunnel — the client that dials it, and any remote range routed over it. Tunnels have no slug, so this is a tunnel id: `tun-…`, or `wg-…` for one carried over from the per-VPC VPN records tunnels replaced. */
  tunnelId?: string | null;
  /** A single VM, by id or by your slug for it. Answers hold its id. */
  vmId?: string | null;
  /** Everything on one private network, by id or by your slug for it. Answers hold its id. */
  vpcId?: string | null;
}
export const FirewallEndpoint = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    cidr: S.optional(S.NullOr(S.String)),
    port: S.optional(S.NullOr(S.Number)),
    protocol: S.optional(S.NullOr(FirewallProtocol)),
    public: S.optional(S.NullOr(S.Boolean)),
    tunnelId: S.optional(S.NullOr(S.String)),
    vmId: S.optional(S.NullOr(S.String)),
    vpcId: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "FirewallEndpoint",
}) as any as S.Schema<FirewallEndpoint>;

export interface CreateFirewallRuleRequest {
  /** Required, and `allow` is the only accepted value. */
  action: FirewallAction | (string & {});
  /** A free-form note, up to 1024 characters. */
  description?: string | null;
  destination: FirewallEndpoint;
  source: FirewallEndpoint;
}
export const CreateFirewallRuleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    action: FirewallAction,
    description: S.optional(S.NullOr(S.String)),
    destination: FirewallEndpoint,
    source: FirewallEndpoint,
  }).pipe(T.Http({ method: "POST", uri: "/v5/firewall/rules", code: 200 })),
).annotate({
  identifier: "CreateFirewallRuleRequest",
}) as any as S.Schema<CreateFirewallRuleRequest>;

/** A resource a rule cannot outlive: deleting it deletes the rule. */
export interface FirewallDependency {
  /** Your label for the named resource, under the same rules as `slug`. */
  displayName?: string | null;
  /** The resource's id. */
  id: string;
  /** `vm`, `vpc`, or `tunnel` today. New selectors add new kinds. */
  kind: string;
  /** Your handle for the named resource, when it has one — so a rule says what it points at without a lookup per id. */
  slug?: string | null;
}
export const FirewallDependency = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    displayName: S.optional(S.NullOr(S.String)),
    id: S.String,
    kind: S.String,
    slug: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "FirewallDependency",
}) as any as S.Schema<FirewallDependency>;

/** What this rule depends on. Deleting any of them deletes this rule, so no rule is ever left pointing at something that no longer exists. */
export type FirewallRuleDependenciesList = Array<FirewallDependency>;
export const FirewallRuleDependenciesList = /*@__PURE__*/ S.Array(
  FirewallDependency,
) as any as S.Schema<FirewallRuleDependenciesList>;

/** An allowed path through the network, as intent: traffic matching `source` may reach `destination`. */
export interface FirewallRule {
  action: FirewallAction;
  createdAt: string;
  /** What this rule depends on. Deleting any of them deletes this rule, so no rule is ever left pointing at something that no longer exists. */
  dependencies?: FirewallRuleDependenciesList;
  description?: string | null;
  destination: FirewallEndpoint;
  id: string;
  source: FirewallEndpoint;
  updatedAt: string;
}
export const FirewallRule = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    action: FirewallAction,
    createdAt: S.String,
    dependencies: S.optional(FirewallRuleDependenciesList),
    description: S.optional(S.NullOr(S.String)),
    destination: FirewallEndpoint,
    id: S.String,
    source: FirewallEndpoint,
    updatedAt: S.String,
  }),
).annotate({ identifier: "FirewallRule" }) as any as S.Schema<FirewallRule>;

export interface DeleteFirewallRuleRequest {
  /** Firewall rule id */
  ruleId: string;
}
export const DeleteFirewallRuleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ruleId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({ method: "DELETE", uri: "/v5/firewall/rules/{ruleId}", code: 200 }),
  ),
).annotate({
  identifier: "DeleteFirewallRuleRequest",
}) as any as S.Schema<DeleteFirewallRuleRequest>;

export interface DeleteFirewallRuleResponse {}
export const DeleteFirewallRuleResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteFirewallRuleResponse",
}) as any as S.Schema<DeleteFirewallRuleResponse>;

/** Every private network this party is on; a rule naming one of them matches. */
export type TrafficPartyVpcIdsList = Array<string>;
export const TrafficPartyVpcIdsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<TrafficPartyVpcIdsList>;

/** One end of a connection to ask about: everything true about the party, not a pattern. */
export interface TrafficParty {
  /** The address in use, when there is one — what `cidr` rules are tested against. */
  address?: string | null;
  /** Freestyle's own ingress — the web proxy serving a mapped domain, or the SSH proxy. Always allowed, whatever the rules say. */
  platform?: boolean;
  port?: number | null;
  /** Whether that address is publicly routable — what `public: true` matches. */
  public?: boolean;
  tunnelId?: string | null;
  vmId?: string | null;
  /** Every private network this party is on; a rule naming one of them matches. */
  vpcIds?: TrafficPartyVpcIdsList;
}
export const TrafficParty = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    address: S.optional(S.NullOr(S.String)),
    platform: S.optional(S.Boolean),
    port: S.optional(S.NullOr(S.Number)),
    public: S.optional(S.Boolean),
    tunnelId: S.optional(S.NullOr(S.String)),
    vmId: S.optional(S.NullOr(S.String)),
    vpcIds: S.optional(TrafficPartyVpcIdsList),
  }),
).annotate({ identifier: "TrafficParty" }) as any as S.Schema<TrafficParty>;

export interface EvaluateFirewallRequest {
  destination: TrafficParty;
  protocol?: FirewallProtocol | (string & {}) | null;
  source: TrafficParty;
}
export const EvaluateFirewallRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    destination: TrafficParty,
    protocol: S.optional(S.NullOr(FirewallProtocol)),
    source: TrafficParty,
  }).pipe(T.Http({ method: "POST", uri: "/v5/firewall/evaluate", code: 200 })),
).annotate({
  identifier: "EvaluateFirewallRequest",
}) as any as S.Schema<EvaluateFirewallRequest>;

/** Why a connection would be allowed, or that it would not. `outcome` is `allowedByPlatform` (Freestyle's own ingress, e.g. a mapped domain — no rule involved), `allowedByRule` (with the `ruleId` that matched), `deniedByPlatform` (with the `reason`, e.g. `outboundMail`, that no rule can override), or `denied`. */
export interface FirewallDecision {
  outcome: string;
  /** Which platform policy closed it, on `deniedByPlatform`. */
  reason?: string | null;
  /** The rule that matched, on `allowedByRule`. */
  ruleId?: string | null;
  /** Which end was Freestyle's ingress, on `allowedByPlatform`. */
  side?: string | null;
}
export const FirewallDecision = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    outcome: S.String,
    reason: S.optional(S.NullOr(S.String)),
    ruleId: S.optional(S.NullOr(S.String)),
    side: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "FirewallDecision",
}) as any as S.Schema<FirewallDecision>;

export interface GetFirewallRuleRequest {
  /** Firewall rule id */
  ruleId: string;
}
export const GetFirewallRuleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ruleId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({ method: "GET", uri: "/v5/firewall/rules/{ruleId}", code: 200 }),
  ),
).annotate({
  identifier: "GetFirewallRuleRequest",
}) as any as S.Schema<GetFirewallRuleRequest>;

export interface ListFirewallRulesRequest {
  /** Rules that apply to this VM: those naming it, plus those naming a private network it is attached to. Its id, or your slug for it. */
  vmId?: string;
  /** Rules naming this private network. Its id, or your slug for it. */
  vpcId?: string;
  /** Rules naming this tunnel, by its id. */
  tunnelId?: string;
  limit?: number;
  offset?: number;
}
export const ListFirewallRulesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    vmId: S.optional(S.String.pipe(T.Query())),
    vpcId: S.optional(S.String.pipe(T.Query())),
    tunnelId: S.optional(S.String.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/v5/firewall/rules", code: 200 })),
).annotate({
  identifier: "ListFirewallRulesRequest",
}) as any as S.Schema<ListFirewallRulesRequest>;

/** Newest first. */
export type ListFirewallRulesResponseRulesList = Array<FirewallRule>;
export const ListFirewallRulesResponseRulesList = /*@__PURE__*/ S.Array(
  FirewallRule,
) as any as S.Schema<ListFirewallRulesResponseRulesList>;

export interface ListFirewallRulesResponse {
  /** Newest first. */
  rules: ListFirewallRulesResponseRulesList;
  totalCount: number;
}
export const ListFirewallRulesResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    rules: ListFirewallRulesResponseRulesList,
    totalCount: S.Number,
  }),
).annotate({
  identifier: "ListFirewallRulesResponse",
}) as any as S.Schema<ListFirewallRulesResponse>;

export type CreateFirewallRuleError =
  | BadRequest
  | NotFound
  | Conflict
  | FreestyleOpError;
/** Allow traffic from one place to another. Both `source` and `destination` are matchers whose fields intersect; use `public: true` for the public Internet. A rule naming a VM, a private network, or a tunnel is deleted automatically when that resource is. */
export const createFirewallRule: API.OperationMethod<
  CreateFirewallRuleRequest,
  FirewallRule,
  CreateFirewallRuleError,
  FreestyleOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateFirewallRuleRequest,
  output: FirewallRule,
  errors: [BadRequest, NotFound, Conflict, UnknownFreestyleError],
  protocol: FreestyleProtocol,
  retry: Retry.Retry,
}));

export type DeleteFirewallRuleError = NotFound | FreestyleOpError;
/** Delete a firewall rule. The resources it named are untouched — the dependency runs one way. */
export const deleteFirewallRule: API.OperationMethod<
  DeleteFirewallRuleRequest,
  DeleteFirewallRuleResponse,
  DeleteFirewallRuleError,
  FreestyleOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteFirewallRuleRequest,
  output: DeleteFirewallRuleResponse,
  errors: [NotFound, UnknownFreestyleError],
  protocol: FreestyleProtocol,
  retry: Retry.Retry,
}));

export type EvaluateFirewallError = BadRequest | FreestyleOpError;
/** Ask whether a connection would be allowed by your rules, without changing anything. Useful for checking a rule set before you rely on it. Traffic Freestyle itself delivers — a mapped domain, the SSH proxy — answers `allowedByPlatform`: it is allowed whatever your rules say, and no rule can block it. Outbound mail answers `deniedByPlatform`: a connection to a mail port on the public Internet is closed whatever your rules say, and goes through an `smtp` TLS rule instead. */
export const evaluateFirewall: API.OperationMethod<
  EvaluateFirewallRequest,
  FirewallDecision,
  EvaluateFirewallError,
  FreestyleOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: EvaluateFirewallRequest,
  output: FirewallDecision,
  errors: [BadRequest, UnknownFreestyleError],
  protocol: FreestyleProtocol,
  retry: Retry.Retry,
}));

export type GetFirewallRuleError = NotFound | FreestyleOpError;
/** Fetch one firewall rule. */
export const getFirewallRule: API.OperationMethod<
  GetFirewallRuleRequest,
  FirewallRule,
  GetFirewallRuleError,
  FreestyleOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetFirewallRuleRequest,
  output: FirewallRule,
  errors: [NotFound, UnknownFreestyleError],
  protocol: FreestyleProtocol,
  retry: Retry.Retry,
}));

export type ListFirewallRulesError = NotFound | FreestyleOpError;
/** List your firewall rules, newest first. Filter by `vmId` to get the rules that apply to one VM — those naming it, plus those naming a private network it is attached to — or by `vpcId`/`tunnelId` for the rules naming one of those. */
export const listFirewallRules: API.PaginatedOperationMethod<
  ListFirewallRulesRequest,
  ListFirewallRulesResponse,
  ListFirewallRulesError,
  FreestyleOpContext,
  FirewallRule
> = /*@__PURE__*/ API.makePaginated(
  () => ({
    input: ListFirewallRulesRequest,
    output: ListFirewallRulesResponse,
    errors: [NotFound, UnknownFreestyleError],
    protocol: FreestyleProtocol,
    retry: Retry.Retry,
    pagination: {
      inputToken: "offset",
      outputToken: "totalCount",
      items: "rules",
      pageSize: "limit",
    } as const,
  }),
  paginateOffset,
) as any;
