import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-vercel/specs/openapi.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { VercelProtocol, type VercelOpError, type VercelOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { VercelOpError, VercelOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

/** The project role that will be added to this Access Group. "null" will remove this project level role. */
export type CreateAccessGroupRequestProjectsItemRole =
  | "ADMIN"
  | "PROJECT_VIEWER"
  | "PROJECT_DEVELOPER";
export const CreateAccessGroupRequestProjectsItemRole = S.String;

export interface CreateAccessGroupRequestProjectsItem {
  /** The ID of the project. */
  projectId: string;
  /** The project role that will be added to this Access Group. "null" will remove this project level role. */
  role: CreateAccessGroupRequestProjectsItemRole | (string & {}) | null;
}
export const CreateAccessGroupRequestProjectsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String,
    role: S.NullOr(CreateAccessGroupRequestProjectsItemRole),
  }),
).annotate({
  identifier: "CreateAccessGroupRequestProjectsItem",
}) as any as S.Schema<CreateAccessGroupRequestProjectsItem>;

export type CreateAccessGroupRequestProjectsList = Array<CreateAccessGroupRequestProjectsItem>;
export const CreateAccessGroupRequestProjectsList = /*@__PURE__*/ S.Array(
  CreateAccessGroupRequestProjectsItem,
) as any as S.Schema<CreateAccessGroupRequestProjectsList>;

/** List of members to add to the access group. */
export type CreateAccessGroupRequestMembersToAddList = Array<string>;
export const CreateAccessGroupRequestMembersToAddList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreateAccessGroupRequestMembersToAddList>;

export interface CreateAccessGroupRequest {
  /** The Team identifier to perform the request on behalf of. */
  teamId?: string;
  /** The Team slug to perform the request on behalf of. */
  slug?: string;
  /** The name of the access group */
  name: string;
  projects?: CreateAccessGroupRequestProjectsList;
  /** List of members to add to the access group. */
  membersToAdd?: CreateAccessGroupRequestMembersToAddList;
}
export const CreateAccessGroupRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    teamId: S.optional(S.String.pipe(T.Query())),
    slug: S.optional(S.String.pipe(T.Query())),
    name: S.String,
    projects: S.optional(CreateAccessGroupRequestProjectsList),
    membersToAdd: S.optional(CreateAccessGroupRequestMembersToAddList),
  }).pipe(T.Http({ method: "POST", uri: "/v1/access-groups", code: 200 })),
).annotate({ identifier: "CreateAccessGroupRequest" }) as any as S.Schema<CreateAccessGroupRequest>;

export type CreateAccessGroupResponseEntitlementsItem = "v0";
export const CreateAccessGroupResponseEntitlementsItem = S.String;

export type CreateAccessGroupResponseEntitlementsList =
  Array<CreateAccessGroupResponseEntitlementsItem>;
export const CreateAccessGroupResponseEntitlementsList = /*@__PURE__*/ S.Array(
  CreateAccessGroupResponseEntitlementsItem,
) as any as S.Schema<CreateAccessGroupResponseEntitlementsList>;

/** Permissions that the team has in the access group. */
export type CreateAccessGroupResponseTeamPermissionsList = Array<string>;
export const CreateAccessGroupResponseTeamPermissionsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreateAccessGroupResponseTeamPermissionsList>;

/** Roles that the team has in the access group. */
export type CreateAccessGroupResponseTeamRolesList = Array<string>;
export const CreateAccessGroupResponseTeamRolesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreateAccessGroupResponseTeamRolesList>;

export interface CreateAccessGroupResponse {
  /** ID of the access group. */
  accessGroupId: string;
  /** Timestamp in milliseconds when the access group was created. */
  createdAt: string;
  entitlements: CreateAccessGroupResponseEntitlementsList;
  membersCount: number;
  /** The name of this access group. */
  name: string;
  projectsCount: number;
  /** ID of the team that this access group belongs to. */
  teamId: string;
  /** Permissions that the team has in the access group. */
  teamPermissions?: CreateAccessGroupResponseTeamPermissionsList;
  /** Roles that the team has in the access group. */
  teamRoles?: CreateAccessGroupResponseTeamRolesList;
  /** Timestamp in milliseconds when the access group was last updated. */
  updatedAt: string;
}
export const CreateAccessGroupResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accessGroupId: S.String,
    createdAt: S.String,
    entitlements: CreateAccessGroupResponseEntitlementsList,
    membersCount: S.Number,
    name: S.String,
    projectsCount: S.Number,
    teamId: S.String,
    teamPermissions: S.optional(CreateAccessGroupResponseTeamPermissionsList),
    teamRoles: S.optional(CreateAccessGroupResponseTeamRolesList),
    updatedAt: S.String,
  }),
).annotate({
  identifier: "CreateAccessGroupResponse",
}) as any as S.Schema<CreateAccessGroupResponse>;

/** The project role that will be added to this Access Group. */
export type CreateAccessGroupProjectRequestRole = "ADMIN" | "PROJECT_VIEWER" | "PROJECT_DEVELOPER";
export const CreateAccessGroupProjectRequestRole = S.String;

export interface CreateAccessGroupProjectRequest {
  accessGroupIdOrName: string;
  /** The Team identifier to perform the request on behalf of. */
  teamId?: string;
  /** The Team slug to perform the request on behalf of. */
  slug?: string;
  /** The ID of the project. */
  projectId: string;
  /** The project role that will be added to this Access Group. */
  role: CreateAccessGroupProjectRequestRole | (string & {});
}
export const CreateAccessGroupProjectRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accessGroupIdOrName: S.String.pipe(T.Label()),
    teamId: S.optional(S.String.pipe(T.Query())),
    slug: S.optional(S.String.pipe(T.Query())),
    projectId: S.String,
    role: CreateAccessGroupProjectRequestRole,
  }).pipe(
    T.Http({ method: "POST", uri: "/v1/access-groups/{accessGroupIdOrName}/projects", code: 200 }),
  ),
).annotate({
  identifier: "CreateAccessGroupProjectRequest",
}) as any as S.Schema<CreateAccessGroupProjectRequest>;

export type CreateAccessGroupProjectResponseRole =
  | "ADMIN"
  | "PROJECT_DEVELOPER"
  | "PROJECT_GUEST"
  | "PROJECT_VIEWER";
export const CreateAccessGroupProjectResponseRole = S.String;

export interface CreateAccessGroupProjectResponse {
  accessGroupId: string;
  createdAt: string;
  projectId: string;
  role: CreateAccessGroupProjectResponseRole;
  teamId: string;
  updatedAt: string;
}
export const CreateAccessGroupProjectResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accessGroupId: S.String,
    createdAt: S.String,
    projectId: S.String,
    role: CreateAccessGroupProjectResponseRole,
    teamId: S.String,
    updatedAt: S.String,
  }),
).annotate({
  identifier: "CreateAccessGroupProjectResponse",
}) as any as S.Schema<CreateAccessGroupProjectResponse>;

export interface DeleteAccessGroupRequest {
  idOrName: string;
  /** The Team identifier to perform the request on behalf of. */
  teamId?: string;
  /** The Team slug to perform the request on behalf of. */
  slug?: string;
}
export const DeleteAccessGroupRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    idOrName: S.String.pipe(T.Label()),
    teamId: S.optional(S.String.pipe(T.Query())),
    slug: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "DELETE", uri: "/v1/access-groups/{idOrName}", code: 200 })),
).annotate({ identifier: "DeleteAccessGroupRequest" }) as any as S.Schema<DeleteAccessGroupRequest>;

export interface DeleteAccessGroupResponse {}
export const DeleteAccessGroupResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "DeleteAccessGroupResponse",
}) as any as S.Schema<DeleteAccessGroupResponse>;

export interface DeleteAccessGroupProjectRequest {
  accessGroupIdOrName: string;
  projectId: string;
  /** The Team identifier to perform the request on behalf of. */
  teamId?: string;
  /** The Team slug to perform the request on behalf of. */
  slug?: string;
}
export const DeleteAccessGroupProjectRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accessGroupIdOrName: S.String.pipe(T.Label()),
    projectId: S.String.pipe(T.Label()),
    teamId: S.optional(S.String.pipe(T.Query())),
    slug: S.optional(S.String.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/v1/access-groups/{accessGroupIdOrName}/projects/{projectId}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "DeleteAccessGroupProjectRequest",
}) as any as S.Schema<DeleteAccessGroupProjectRequest>;

export interface DeleteAccessGroupProjectResponse {}
export const DeleteAccessGroupProjectResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteAccessGroupProjectResponse",
}) as any as S.Schema<DeleteAccessGroupProjectResponse>;

export interface ListAccessGroupMembersRequest {
  /** The ID or name of the Access Group. */
  idOrName: string;
  /** Limit how many access group members should be returned. */
  limit?: number;
  /** Continuation cursor to retrieve the next page of results. */
  next?: string;
  /** Search project members by their name, username, and email. */
  search?: string;
  /** The Team identifier to perform the request on behalf of. */
  teamId?: string;
  /** The Team slug to perform the request on behalf of. */
  slug?: string;
}
export const ListAccessGroupMembersRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    idOrName: S.String.pipe(T.Label()),
    limit: S.optional(S.Number.pipe(T.Query())),
    next: S.optional(S.String.pipe(T.Query())),
    search: S.optional(S.String.pipe(T.Query())),
    teamId: S.optional(S.String.pipe(T.Query())),
    slug: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/v1/access-groups/{idOrName}/members", code: 200 })),
).annotate({
  identifier: "ListAccessGroupMembersRequest",
}) as any as S.Schema<ListAccessGroupMembersRequest>;

export type ListAccessGroupMembersResponseMembersItemTeamRole =
  | "BILLING"
  | "CONTRIBUTOR"
  | "DEVELOPER"
  | "MEMBER"
  | "OWNER"
  | "SECURITY"
  | "VIEWER"
  | "VIEWER_FOR_PLUS";
export const ListAccessGroupMembersResponseMembersItemTeamRole = S.String;

export interface ListAccessGroupMembersResponseMembersItem {
  avatar?: string;
  createdAt?: string;
  email: string;
  name?: string;
  teamRole: ListAccessGroupMembersResponseMembersItemTeamRole;
  uid: string;
  username: string;
}
export const ListAccessGroupMembersResponseMembersItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    avatar: S.optional(S.String),
    createdAt: S.optional(S.String),
    email: S.String,
    name: S.optional(S.String),
    teamRole: ListAccessGroupMembersResponseMembersItemTeamRole,
    uid: S.String,
    username: S.String,
  }),
).annotate({
  identifier: "ListAccessGroupMembersResponseMembersItem",
}) as any as S.Schema<ListAccessGroupMembersResponseMembersItem>;

export type ListAccessGroupMembersResponseMembersList =
  Array<ListAccessGroupMembersResponseMembersItem>;
export const ListAccessGroupMembersResponseMembersList = /*@__PURE__*/ S.Array(
  ListAccessGroupMembersResponseMembersItem,
) as any as S.Schema<ListAccessGroupMembersResponseMembersList>;

export interface ListAccessGroupMembersResponsePagination {
  count: number;
  next: string | null;
}
export const ListAccessGroupMembersResponsePagination = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.Number,
    next: S.NullOr(S.String),
  }),
).annotate({
  identifier: "ListAccessGroupMembersResponsePagination",
}) as any as S.Schema<ListAccessGroupMembersResponsePagination>;

export interface ListAccessGroupMembersResponse {
  members: ListAccessGroupMembersResponseMembersList;
  pagination: ListAccessGroupMembersResponsePagination;
}
export const ListAccessGroupMembersResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    members: ListAccessGroupMembersResponseMembersList,
    pagination: ListAccessGroupMembersResponsePagination,
  }),
).annotate({
  identifier: "ListAccessGroupMembersResponse",
}) as any as S.Schema<ListAccessGroupMembersResponse>;

export interface ListAccessGroupProjectsRequest {
  /** The ID or name of the Access Group. */
  idOrName: string;
  /** Limit how many access group projects should be returned. */
  limit?: number;
  /** Continuation cursor to retrieve the next page of results. */
  next?: string;
  /** The Team identifier to perform the request on behalf of. */
  teamId?: string;
  /** The Team slug to perform the request on behalf of. */
  slug?: string;
}
export const ListAccessGroupProjectsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    idOrName: S.String.pipe(T.Label()),
    limit: S.optional(S.Number.pipe(T.Query())),
    next: S.optional(S.String.pipe(T.Query())),
    teamId: S.optional(S.String.pipe(T.Query())),
    slug: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/v1/access-groups/{idOrName}/projects", code: 200 })),
).annotate({
  identifier: "ListAccessGroupProjectsRequest",
}) as any as S.Schema<ListAccessGroupProjectsRequest>;

export type ListAccessGroupProjectsResponsePagination = ListAccessGroupMembersResponsePagination;
export const ListAccessGroupProjectsResponsePagination = ListAccessGroupMembersResponsePagination;

export interface ListAccessGroupProjectsResponseProjectsItemProject {
  framework?: string | null;
  latestDeploymentId?: string;
  name?: string;
}
export const ListAccessGroupProjectsResponseProjectsItemProject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    framework: S.optional(S.NullOr(S.String)),
    latestDeploymentId: S.optional(S.String),
    name: S.optional(S.String),
  }),
).annotate({
  identifier: "ListAccessGroupProjectsResponseProjectsItemProject",
}) as any as S.Schema<ListAccessGroupProjectsResponseProjectsItemProject>;

export type ListAccessGroupProjectsResponseProjectsItemRole =
  | "ADMIN"
  | "PROJECT_DEVELOPER"
  | "PROJECT_GUEST"
  | "PROJECT_VIEWER";
export const ListAccessGroupProjectsResponseProjectsItemRole = S.String;

export interface ListAccessGroupProjectsResponseProjectsItem {
  createdAt: string;
  project: ListAccessGroupProjectsResponseProjectsItemProject;
  projectId: string;
  role: ListAccessGroupProjectsResponseProjectsItemRole;
  updatedAt: string;
}
export const ListAccessGroupProjectsResponseProjectsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    createdAt: S.String,
    project: ListAccessGroupProjectsResponseProjectsItemProject,
    projectId: S.String,
    role: ListAccessGroupProjectsResponseProjectsItemRole,
    updatedAt: S.String,
  }),
).annotate({
  identifier: "ListAccessGroupProjectsResponseProjectsItem",
}) as any as S.Schema<ListAccessGroupProjectsResponseProjectsItem>;

export type ListAccessGroupProjectsResponseProjectsList =
  Array<ListAccessGroupProjectsResponseProjectsItem>;
export const ListAccessGroupProjectsResponseProjectsList = /*@__PURE__*/ S.Array(
  ListAccessGroupProjectsResponseProjectsItem,
) as any as S.Schema<ListAccessGroupProjectsResponseProjectsList>;

export interface ListAccessGroupProjectsResponse {
  pagination: ListAccessGroupMembersResponsePagination;
  projects: ListAccessGroupProjectsResponseProjectsList;
}
export const ListAccessGroupProjectsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    pagination: ListAccessGroupMembersResponsePagination,
    projects: ListAccessGroupProjectsResponseProjectsList,
  }),
).annotate({
  identifier: "ListAccessGroupProjectsResponse",
}) as any as S.Schema<ListAccessGroupProjectsResponse>;

export interface ListAccessGroupsRequest {
  /** Filter access groups by project. */
  projectId?: string;
  /** Search for access groups by name. */
  search?: string;
  /** Number of members to include in the response. */
  membersLimit?: number;
  /** Number of projects to include in the response. */
  projectsLimit?: number;
  /** Limit how many access group should be returned. */
  limit?: number;
  /** Continuation cursor to retrieve the next page of results. */
  next?: string;
  /** The Team identifier to perform the request on behalf of. */
  teamId?: string;
  /** The Team slug to perform the request on behalf of. */
  slug?: string;
}
export const ListAccessGroupsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.optional(S.String.pipe(T.Query())),
    search: S.optional(S.String.pipe(T.Query())),
    membersLimit: S.optional(S.Number.pipe(T.Query())),
    projectsLimit: S.optional(S.Number.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    next: S.optional(S.String.pipe(T.Query())),
    teamId: S.optional(S.String.pipe(T.Query())),
    slug: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/v1/access-groups", code: 200 })),
).annotate({ identifier: "ListAccessGroupsRequest" }) as any as S.Schema<ListAccessGroupsRequest>;

export type ListAccessGroupsResponseBodyCase1AccessGroupsItemEntitlementsList = Array<string>;
export const ListAccessGroupsResponseBodyCase1AccessGroupsItemEntitlementsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<ListAccessGroupsResponseBodyCase1AccessGroupsItemEntitlementsList>;

export type ListAccessGroupsResponseBodyCase1AccessGroupsItemMembersList = Array<string>;
export const ListAccessGroupsResponseBodyCase1AccessGroupsItemMembersList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<ListAccessGroupsResponseBodyCase1AccessGroupsItemMembersList>;

export type ListAccessGroupsResponseBodyCase1AccessGroupsItemProjectsList = Array<string>;
export const ListAccessGroupsResponseBodyCase1AccessGroupsItemProjectsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<ListAccessGroupsResponseBodyCase1AccessGroupsItemProjectsList>;

export type ListAccessGroupsResponseBodyCase1AccessGroupsItemTeamPermissionsList = Array<string>;
export const ListAccessGroupsResponseBodyCase1AccessGroupsItemTeamPermissionsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<ListAccessGroupsResponseBodyCase1AccessGroupsItemTeamPermissionsList>;

/** Roles that the team has in the access group. */
export type ListAccessGroupsResponseBodyCase1AccessGroupsItemTeamRolesList = Array<string>;
export const ListAccessGroupsResponseBodyCase1AccessGroupsItemTeamRolesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<ListAccessGroupsResponseBodyCase1AccessGroupsItemTeamRolesList>;

export interface ListAccessGroupsResponseBodyCase1AccessGroupsItem {
  /** ID of the access group. */
  accessGroupId: string;
  /** Timestamp in milliseconds when the access group was created. */
  createdAt: string;
  entitlements?: ListAccessGroupsResponseBodyCase1AccessGroupsItemEntitlementsList;
  isDsyncManaged: boolean;
  members?: ListAccessGroupsResponseBodyCase1AccessGroupsItemMembersList;
  /** Number of members in the access group. */
  membersCount: number;
  /** The name of this access group. */
  name: string;
  projects?: ListAccessGroupsResponseBodyCase1AccessGroupsItemProjectsList;
  /** Number of projects in the access group. */
  projectsCount: number;
  /** ID of the team that this access group belongs to. */
  teamId: string;
  teamPermissions?: ListAccessGroupsResponseBodyCase1AccessGroupsItemTeamPermissionsList;
  /** Roles that the team has in the access group. */
  teamRoles?: ListAccessGroupsResponseBodyCase1AccessGroupsItemTeamRolesList;
  /** Timestamp in milliseconds when the access group was last updated. */
  updatedAt: string;
}
export const ListAccessGroupsResponseBodyCase1AccessGroupsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accessGroupId: S.String,
    createdAt: S.String,
    entitlements: S.optional(ListAccessGroupsResponseBodyCase1AccessGroupsItemEntitlementsList),
    isDsyncManaged: S.Boolean,
    members: S.optional(ListAccessGroupsResponseBodyCase1AccessGroupsItemMembersList),
    membersCount: S.Number,
    name: S.String,
    projects: S.optional(ListAccessGroupsResponseBodyCase1AccessGroupsItemProjectsList),
    projectsCount: S.Number,
    teamId: S.String,
    teamPermissions: S.optional(
      ListAccessGroupsResponseBodyCase1AccessGroupsItemTeamPermissionsList,
    ),
    teamRoles: S.optional(ListAccessGroupsResponseBodyCase1AccessGroupsItemTeamRolesList),
    updatedAt: S.String,
  }),
).annotate({
  identifier: "ListAccessGroupsResponseBodyCase1AccessGroupsItem",
}) as any as S.Schema<ListAccessGroupsResponseBodyCase1AccessGroupsItem>;

export type ListAccessGroupsResponseBodyCase1AccessGroupsList =
  Array<ListAccessGroupsResponseBodyCase1AccessGroupsItem>;
export const ListAccessGroupsResponseBodyCase1AccessGroupsList = /*@__PURE__*/ S.Array(
  ListAccessGroupsResponseBodyCase1AccessGroupsItem,
) as any as S.Schema<ListAccessGroupsResponseBodyCase1AccessGroupsList>;

export type ListAccessGroupsResponseBodyCase1Pagination = ListAccessGroupMembersResponsePagination;
export const ListAccessGroupsResponseBodyCase1Pagination = ListAccessGroupMembersResponsePagination;

export interface ListAccessGroupsResponseBodyCase1 {
  accessGroups: ListAccessGroupsResponseBodyCase1AccessGroupsList;
  pagination: ListAccessGroupMembersResponsePagination;
}
export const ListAccessGroupsResponseBodyCase1 = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accessGroups: ListAccessGroupsResponseBodyCase1AccessGroupsList,
    pagination: ListAccessGroupMembersResponsePagination,
  }),
).annotate({
  identifier: "ListAccessGroupsResponseBodyCase1",
}) as any as S.Schema<ListAccessGroupsResponseBodyCase1>;

export type ListAccessGroupsResponseBody = unknown | ListAccessGroupsResponseBodyCase1;
export const ListAccessGroupsResponseBody =
  S.Unknown as any as S.Schema<ListAccessGroupsResponseBody>;

export type ListAccessGroupsResponse = ListAccessGroupsResponseBody;
export const ListAccessGroupsResponse = /*@__PURE__*/ S.suspend(() =>
  ListAccessGroupsResponseBody.pipe(T.RawResponseRoot()),
).annotate({ identifier: "ListAccessGroupsResponse" }) as any as S.Schema<ListAccessGroupsResponse>;

export interface ReadAccessGroupRequest {
  idOrName: string;
  /** The Team identifier to perform the request on behalf of. */
  teamId?: string;
  /** The Team slug to perform the request on behalf of. */
  slug?: string;
}
export const ReadAccessGroupRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    idOrName: S.String.pipe(T.Label()),
    teamId: S.optional(S.String.pipe(T.Query())),
    slug: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/v1/access-groups/{idOrName}", code: 200 })),
).annotate({ identifier: "ReadAccessGroupRequest" }) as any as S.Schema<ReadAccessGroupRequest>;

export type ReadAccessGroupResponseEntitlementsItem = "v0";
export const ReadAccessGroupResponseEntitlementsItem = S.String;

export type ReadAccessGroupResponseEntitlementsList =
  Array<ReadAccessGroupResponseEntitlementsItem>;
export const ReadAccessGroupResponseEntitlementsList = /*@__PURE__*/ S.Array(
  ReadAccessGroupResponseEntitlementsItem,
) as any as S.Schema<ReadAccessGroupResponseEntitlementsList>;

export type ReadAccessGroupResponseTeamPermissionsItem =
  | "AiGatewayBudgetManager"
  | "AiGatewayCredits"
  | "AiGatewaySettings"
  | "AiGatewayTranscriptsManager"
  | "AiGatewayTranscriptsViewer"
  | "AiGatewayUser"
  | "ConnectorManager"
  | "CreateProject"
  | "EnvVariableManager"
  | "EnvironmentManager"
  | "FullProductionDeployment"
  | "IntegrationManager"
  | "OrgAdmin"
  | "OrgViewer"
  | "UsageViewer"
  | "V0Builder"
  | "V0Chatter"
  | "V0Viewer"
  | "WorkflowDecryptor";
export const ReadAccessGroupResponseTeamPermissionsItem = S.String;

export type ReadAccessGroupResponseTeamPermissionsList =
  Array<ReadAccessGroupResponseTeamPermissionsItem>;
export const ReadAccessGroupResponseTeamPermissionsList = /*@__PURE__*/ S.Array(
  ReadAccessGroupResponseTeamPermissionsItem,
) as any as S.Schema<ReadAccessGroupResponseTeamPermissionsList>;

/** Roles that the team has in the access group. */
export type ReadAccessGroupResponseTeamRolesList = Array<string>;
export const ReadAccessGroupResponseTeamRolesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<ReadAccessGroupResponseTeamRolesList>;

export interface ReadAccessGroupResponse {
  /** ID of the access group. */
  accessGroupId: string;
  /** Timestamp in milliseconds when the access group was created. */
  createdAt: string;
  entitlements?: ReadAccessGroupResponseEntitlementsList;
  isDsyncManaged: boolean;
  /** Number of members in the access group. */
  membersCount: number;
  /** The name of this access group. */
  name: string;
  /** Number of projects in the access group. */
  projectsCount: number;
  /** ID of the team that this access group belongs to. */
  teamId: string;
  teamPermissions?: ReadAccessGroupResponseTeamPermissionsList;
  /** Roles that the team has in the access group. */
  teamRoles?: ReadAccessGroupResponseTeamRolesList;
  /** Timestamp in milliseconds when the access group was last updated. */
  updatedAt: string;
}
export const ReadAccessGroupResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accessGroupId: S.String,
    createdAt: S.String,
    entitlements: S.optional(ReadAccessGroupResponseEntitlementsList),
    isDsyncManaged: S.Boolean,
    membersCount: S.Number,
    name: S.String,
    projectsCount: S.Number,
    teamId: S.String,
    teamPermissions: S.optional(ReadAccessGroupResponseTeamPermissionsList),
    teamRoles: S.optional(ReadAccessGroupResponseTeamRolesList),
    updatedAt: S.String,
  }),
).annotate({ identifier: "ReadAccessGroupResponse" }) as any as S.Schema<ReadAccessGroupResponse>;

export interface ReadAccessGroupProjectRequest {
  accessGroupIdOrName: string;
  projectId: string;
  /** The Team identifier to perform the request on behalf of. */
  teamId?: string;
  /** The Team slug to perform the request on behalf of. */
  slug?: string;
}
export const ReadAccessGroupProjectRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accessGroupIdOrName: S.String.pipe(T.Label()),
    projectId: S.String.pipe(T.Label()),
    teamId: S.optional(S.String.pipe(T.Query())),
    slug: S.optional(S.String.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/v1/access-groups/{accessGroupIdOrName}/projects/{projectId}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ReadAccessGroupProjectRequest",
}) as any as S.Schema<ReadAccessGroupProjectRequest>;

export type ReadAccessGroupProjectResponseRole =
  | "ADMIN"
  | "PROJECT_DEVELOPER"
  | "PROJECT_GUEST"
  | "PROJECT_VIEWER";
export const ReadAccessGroupProjectResponseRole = S.String;

export interface ReadAccessGroupProjectResponse {
  accessGroupId: string;
  createdAt: string;
  projectId: string;
  role: ReadAccessGroupProjectResponseRole;
  teamId: string;
  updatedAt: string;
}
export const ReadAccessGroupProjectResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accessGroupId: S.String,
    createdAt: S.String,
    projectId: S.String,
    role: ReadAccessGroupProjectResponseRole,
    teamId: S.String,
    updatedAt: S.String,
  }),
).annotate({
  identifier: "ReadAccessGroupProjectResponse",
}) as any as S.Schema<ReadAccessGroupProjectResponse>;

/** The project role that will be added to this Access Group. "null" will remove this project level role. */
export type UpdateAccessGroupRequestProjectsItemRole =
  | "ADMIN"
  | "PROJECT_VIEWER"
  | "PROJECT_DEVELOPER";
export const UpdateAccessGroupRequestProjectsItemRole = S.String;

export interface UpdateAccessGroupRequestProjectsItem {
  /** The ID of the project. */
  projectId: string;
  /** The project role that will be added to this Access Group. "null" will remove this project level role. */
  role: UpdateAccessGroupRequestProjectsItemRole | (string & {}) | null;
}
export const UpdateAccessGroupRequestProjectsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String,
    role: S.NullOr(UpdateAccessGroupRequestProjectsItemRole),
  }),
).annotate({
  identifier: "UpdateAccessGroupRequestProjectsItem",
}) as any as S.Schema<UpdateAccessGroupRequestProjectsItem>;

export type UpdateAccessGroupRequestProjectsList = Array<UpdateAccessGroupRequestProjectsItem>;
export const UpdateAccessGroupRequestProjectsList = /*@__PURE__*/ S.Array(
  UpdateAccessGroupRequestProjectsItem,
) as any as S.Schema<UpdateAccessGroupRequestProjectsList>;

/** List of members to add to the access group. */
export type UpdateAccessGroupRequestMembersToAddList = Array<string>;
export const UpdateAccessGroupRequestMembersToAddList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<UpdateAccessGroupRequestMembersToAddList>;

/** List of members to remove from the access group. */
export type UpdateAccessGroupRequestMembersToRemoveList = Array<string>;
export const UpdateAccessGroupRequestMembersToRemoveList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<UpdateAccessGroupRequestMembersToRemoveList>;

export interface UpdateAccessGroupRequest {
  idOrName: string;
  /** The Team identifier to perform the request on behalf of. */
  teamId?: string;
  /** The Team slug to perform the request on behalf of. */
  slug?: string;
  /** The name of the access group */
  name?: string;
  projects?: UpdateAccessGroupRequestProjectsList;
  /** List of members to add to the access group. */
  membersToAdd?: UpdateAccessGroupRequestMembersToAddList;
  /** List of members to remove from the access group. */
  membersToRemove?: UpdateAccessGroupRequestMembersToRemoveList;
}
export const UpdateAccessGroupRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    idOrName: S.String.pipe(T.Label()),
    teamId: S.optional(S.String.pipe(T.Query())),
    slug: S.optional(S.String.pipe(T.Query())),
    name: S.optional(S.String),
    projects: S.optional(UpdateAccessGroupRequestProjectsList),
    membersToAdd: S.optional(UpdateAccessGroupRequestMembersToAddList),
    membersToRemove: S.optional(UpdateAccessGroupRequestMembersToRemoveList),
  }).pipe(T.Http({ method: "POST", uri: "/v1/access-groups/{idOrName}", code: 200 })),
).annotate({ identifier: "UpdateAccessGroupRequest" }) as any as S.Schema<UpdateAccessGroupRequest>;

export type UpdateAccessGroupResponseEntitlementsItem = "v0";
export const UpdateAccessGroupResponseEntitlementsItem = S.String;

export type UpdateAccessGroupResponseEntitlementsList =
  Array<UpdateAccessGroupResponseEntitlementsItem>;
export const UpdateAccessGroupResponseEntitlementsList = /*@__PURE__*/ S.Array(
  UpdateAccessGroupResponseEntitlementsItem,
) as any as S.Schema<UpdateAccessGroupResponseEntitlementsList>;

/** Permissions that the team has in the access group. */
export type UpdateAccessGroupResponseTeamPermissionsList = Array<string>;
export const UpdateAccessGroupResponseTeamPermissionsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<UpdateAccessGroupResponseTeamPermissionsList>;

/** Roles that the team has in the access group. */
export type UpdateAccessGroupResponseTeamRolesList = Array<string>;
export const UpdateAccessGroupResponseTeamRolesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<UpdateAccessGroupResponseTeamRolesList>;

export interface UpdateAccessGroupResponse {
  /** ID of the access group. */
  accessGroupId: string;
  /** Timestamp in milliseconds when the access group was created. */
  createdAt: string;
  entitlements: UpdateAccessGroupResponseEntitlementsList;
  /** Number of members in the access group. */
  membersCount: number;
  /** The name of this access group. */
  name: string;
  /** Number of projects in the access group. */
  projectsCount: number;
  /** ID of the team that this access group belongs to. */
  teamId: string;
  /** Permissions that the team has in the access group. */
  teamPermissions?: UpdateAccessGroupResponseTeamPermissionsList;
  /** Roles that the team has in the access group. */
  teamRoles?: UpdateAccessGroupResponseTeamRolesList;
  /** Timestamp in milliseconds when the access group was last updated. */
  updatedAt: string;
}
export const UpdateAccessGroupResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accessGroupId: S.String,
    createdAt: S.String,
    entitlements: UpdateAccessGroupResponseEntitlementsList,
    membersCount: S.Number,
    name: S.String,
    projectsCount: S.Number,
    teamId: S.String,
    teamPermissions: S.optional(UpdateAccessGroupResponseTeamPermissionsList),
    teamRoles: S.optional(UpdateAccessGroupResponseTeamRolesList),
    updatedAt: S.String,
  }),
).annotate({
  identifier: "UpdateAccessGroupResponse",
}) as any as S.Schema<UpdateAccessGroupResponse>;

/** The project role that will be added to this Access Group. */
export type UpdateAccessGroupProjectRequestRole = "ADMIN" | "PROJECT_VIEWER" | "PROJECT_DEVELOPER";
export const UpdateAccessGroupProjectRequestRole = S.String;

export interface UpdateAccessGroupProjectRequest {
  accessGroupIdOrName: string;
  projectId: string;
  /** The Team identifier to perform the request on behalf of. */
  teamId?: string;
  /** The Team slug to perform the request on behalf of. */
  slug?: string;
  /** The project role that will be added to this Access Group. */
  role: UpdateAccessGroupProjectRequestRole | (string & {});
}
export const UpdateAccessGroupProjectRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accessGroupIdOrName: S.String.pipe(T.Label()),
    projectId: S.String.pipe(T.Label()),
    teamId: S.optional(S.String.pipe(T.Query())),
    slug: S.optional(S.String.pipe(T.Query())),
    role: UpdateAccessGroupProjectRequestRole,
  }).pipe(
    T.Http({
      method: "PATCH",
      uri: "/v1/access-groups/{accessGroupIdOrName}/projects/{projectId}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "UpdateAccessGroupProjectRequest",
}) as any as S.Schema<UpdateAccessGroupProjectRequest>;

export type UpdateAccessGroupProjectResponseRole =
  | "ADMIN"
  | "PROJECT_DEVELOPER"
  | "PROJECT_GUEST"
  | "PROJECT_VIEWER";
export const UpdateAccessGroupProjectResponseRole = S.String;

export interface UpdateAccessGroupProjectResponse {
  accessGroupId: string;
  createdAt: string;
  projectId: string;
  role: UpdateAccessGroupProjectResponseRole;
  teamId: string;
  updatedAt: string;
}
export const UpdateAccessGroupProjectResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accessGroupId: S.String,
    createdAt: S.String,
    projectId: S.String,
    role: UpdateAccessGroupProjectResponseRole,
    teamId: S.String,
    updatedAt: S.String,
  }),
).annotate({
  identifier: "UpdateAccessGroupProjectResponse",
}) as any as S.Schema<UpdateAccessGroupProjectResponse>;

export type CreateAccessGroupError = BadRequest | Forbidden | NotFound | VercelOpError;
/** Creates an access group Allows to create an access group */
export const createAccessGroup: API.OperationMethod<
  CreateAccessGroupRequest,
  CreateAccessGroupResponse,
  CreateAccessGroupError,
  VercelOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateAccessGroupRequest,
  output: CreateAccessGroupResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: VercelProtocol,
  retry: Retry.Retry,
}));

export type CreateAccessGroupProjectError = BadRequest | Forbidden | NotFound | VercelOpError;
/** Create an access group project Allows creation of an access group project */
export const createAccessGroupProject: API.OperationMethod<
  CreateAccessGroupProjectRequest,
  CreateAccessGroupProjectResponse,
  CreateAccessGroupProjectError,
  VercelOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateAccessGroupProjectRequest,
  output: CreateAccessGroupProjectResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: VercelProtocol,
  retry: Retry.Retry,
}));

export type DeleteAccessGroupError = BadRequest | Forbidden | NotFound | VercelOpError;
/** Deletes an access group Allows to delete an access group */
export const deleteAccessGroup: API.OperationMethod<
  DeleteAccessGroupRequest,
  DeleteAccessGroupResponse,
  DeleteAccessGroupError,
  VercelOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteAccessGroupRequest,
  output: DeleteAccessGroupResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: VercelProtocol,
  retry: Retry.Retry,
}));

export type DeleteAccessGroupProjectError = BadRequest | Forbidden | NotFound | VercelOpError;
/** Delete an access group project Allows deletion of an access group project */
export const deleteAccessGroupProject: API.OperationMethod<
  DeleteAccessGroupProjectRequest,
  DeleteAccessGroupProjectResponse,
  DeleteAccessGroupProjectError,
  VercelOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteAccessGroupProjectRequest,
  output: DeleteAccessGroupProjectResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: VercelProtocol,
  retry: Retry.Retry,
}));

export type ListAccessGroupMembersError = BadRequest | Forbidden | NotFound | VercelOpError;
/** List members of an access group List members of an access group */
export const listAccessGroupMembers: API.OperationMethod<
  ListAccessGroupMembersRequest,
  ListAccessGroupMembersResponse,
  ListAccessGroupMembersError,
  VercelOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListAccessGroupMembersRequest,
  output: ListAccessGroupMembersResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: VercelProtocol,
  retry: Retry.Retry,
}));

export type ListAccessGroupProjectsError = BadRequest | Forbidden | NotFound | VercelOpError;
/** List projects of an access group List projects of an access group */
export const listAccessGroupProjects: API.OperationMethod<
  ListAccessGroupProjectsRequest,
  ListAccessGroupProjectsResponse,
  ListAccessGroupProjectsError,
  VercelOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListAccessGroupProjectsRequest,
  output: ListAccessGroupProjectsResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: VercelProtocol,
  retry: Retry.Retry,
}));

export type ListAccessGroupsError = BadRequest | Forbidden | NotFound | VercelOpError;
/** List access groups for a team, project or member List access groups */
export const listAccessGroups: API.OperationMethod<
  ListAccessGroupsRequest,
  ListAccessGroupsResponse,
  ListAccessGroupsError,
  VercelOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListAccessGroupsRequest,
  output: ListAccessGroupsResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: VercelProtocol,
  retry: Retry.Retry,
}));

export type ReadAccessGroupError = BadRequest | Forbidden | NotFound | VercelOpError;
/** Reads an access group Allows to read an access group */
export const readAccessGroup: API.OperationMethod<
  ReadAccessGroupRequest,
  ReadAccessGroupResponse,
  ReadAccessGroupError,
  VercelOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ReadAccessGroupRequest,
  output: ReadAccessGroupResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: VercelProtocol,
  retry: Retry.Retry,
}));

export type ReadAccessGroupProjectError = BadRequest | Forbidden | NotFound | VercelOpError;
/** Reads an access group project Allows reading an access group project */
export const readAccessGroupProject: API.OperationMethod<
  ReadAccessGroupProjectRequest,
  ReadAccessGroupProjectResponse,
  ReadAccessGroupProjectError,
  VercelOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ReadAccessGroupProjectRequest,
  output: ReadAccessGroupProjectResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: VercelProtocol,
  retry: Retry.Retry,
}));

export type UpdateAccessGroupError = BadRequest | Forbidden | NotFound | VercelOpError;
/** Update an access group Allows to update an access group metadata */
export const updateAccessGroup: API.OperationMethod<
  UpdateAccessGroupRequest,
  UpdateAccessGroupResponse,
  UpdateAccessGroupError,
  VercelOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateAccessGroupRequest,
  output: UpdateAccessGroupResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: VercelProtocol,
  retry: Retry.Retry,
}));

export type UpdateAccessGroupProjectError = BadRequest | Forbidden | NotFound | VercelOpError;
/** Update an access group project Allows update of an access group project */
export const updateAccessGroupProject: API.OperationMethod<
  UpdateAccessGroupProjectRequest,
  UpdateAccessGroupProjectResponse,
  UpdateAccessGroupProjectError,
  VercelOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateAccessGroupProjectRequest,
  output: UpdateAccessGroupProjectResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: VercelProtocol,
  retry: Retry.Retry,
}));
