import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-vercel/specs/openapi.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { VercelProtocol, type VercelOpError, type VercelOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { VercelOpError, VercelOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Conflict
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Conflict>()("Conflict", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withConflictError),
    [{ status: 409 }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

export class PaymentRequired
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<PaymentRequired>()("PaymentRequired", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withQuotaError),
    [{ status: 402 }],
  ) {}

export type CreateStorageStoresBlobRequestRegion =
  | "arn1"
  | "bom1"
  | "cdg1"
  | "cle1"
  | "cpt1"
  | "dub1"
  | "dxb1"
  | "fra1"
  | "gru1"
  | "hkg1"
  | "hnd1"
  | "iad1"
  | "icn1"
  | "kix1"
  | "lhr1"
  | "pdx1"
  | "sfo1"
  | "sin1"
  | "syd1"
  | "yul1";
export const CreateStorageStoresBlobRequestRegion = S.String;

export type CreateStorageStoresBlobRequestAccess = "public" | "private";
export const CreateStorageStoresBlobRequestAccess = S.String;

export interface CreateStorageStoresBlobRequest {
  name: string;
  region?: CreateStorageStoresBlobRequestRegion | (string & {});
  access?: CreateStorageStoresBlobRequestAccess | (string & {});
  projectId?: string;
}
export const CreateStorageStoresBlobRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String,
    region: S.optional(CreateStorageStoresBlobRequestRegion),
    access: S.optional(CreateStorageStoresBlobRequestAccess),
    projectId: S.optional(S.String),
  }).pipe(T.Http({ method: "POST", uri: "/storage/stores/blob", code: 200 })),
).annotate({
  identifier: "CreateStorageStoresBlobRequest",
}) as any as S.Schema<CreateStorageStoresBlobRequest>;

export type CreateStorageStoresBlobResponseStoreProjectFilterGitOwnersList = Array<string>;
export const CreateStorageStoresBlobResponseStoreProjectFilterGitOwnersList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreateStorageStoresBlobResponseStoreProjectFilterGitOwnersList>;

export type CreateStorageStoresBlobResponseStoreProjectFilterGitProvidersCase0Item =
  | "bitbucket"
  | "github"
  | "gitlab";
export const CreateStorageStoresBlobResponseStoreProjectFilterGitProvidersCase0Item = S.String;

export type CreateStorageStoresBlobResponseStoreProjectFilterGitProvidersCase0List =
  Array<CreateStorageStoresBlobResponseStoreProjectFilterGitProvidersCase0Item>;
export const CreateStorageStoresBlobResponseStoreProjectFilterGitProvidersCase0List =
  /*@__PURE__*/ S.Array(
    CreateStorageStoresBlobResponseStoreProjectFilterGitProvidersCase0Item,
  ) as any as S.Schema<CreateStorageStoresBlobResponseStoreProjectFilterGitProvidersCase0List>;

export type CreateStorageStoresBlobResponseStoreProjectFilterGitProvidersCase1 = "*";
export const CreateStorageStoresBlobResponseStoreProjectFilterGitProvidersCase1 = S.String;

export type CreateStorageStoresBlobResponseStoreProjectFilterGitProviders =
  | CreateStorageStoresBlobResponseStoreProjectFilterGitProvidersCase0List
  | CreateStorageStoresBlobResponseStoreProjectFilterGitProvidersCase1;
export const CreateStorageStoresBlobResponseStoreProjectFilterGitProviders =
  S.Unknown as any as S.Schema<CreateStorageStoresBlobResponseStoreProjectFilterGitProviders>;

export type CreateStorageStoresBlobResponseStoreProjectFilterGitReposList = Array<string>;
export const CreateStorageStoresBlobResponseStoreProjectFilterGitReposList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreateStorageStoresBlobResponseStoreProjectFilterGitReposList>;

export interface CreateStorageStoresBlobResponseStoreProjectFilterGit {
  owners?: CreateStorageStoresBlobResponseStoreProjectFilterGitOwnersList;
  providers: CreateStorageStoresBlobResponseStoreProjectFilterGitProviders;
  repos?: CreateStorageStoresBlobResponseStoreProjectFilterGitReposList;
}
export const CreateStorageStoresBlobResponseStoreProjectFilterGit = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    owners: S.optional(CreateStorageStoresBlobResponseStoreProjectFilterGitOwnersList),
    providers: CreateStorageStoresBlobResponseStoreProjectFilterGitProviders,
    repos: S.optional(CreateStorageStoresBlobResponseStoreProjectFilterGitReposList),
  }),
).annotate({
  identifier: "CreateStorageStoresBlobResponseStoreProjectFilterGit",
}) as any as S.Schema<CreateStorageStoresBlobResponseStoreProjectFilterGit>;

export interface CreateStorageStoresBlobResponseStoreProjectFilter {
  git?: CreateStorageStoresBlobResponseStoreProjectFilterGit;
}
export const CreateStorageStoresBlobResponseStoreProjectFilter = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    git: S.optional(CreateStorageStoresBlobResponseStoreProjectFilterGit),
  }),
).annotate({
  identifier: "CreateStorageStoresBlobResponseStoreProjectFilter",
}) as any as S.Schema<CreateStorageStoresBlobResponseStoreProjectFilter>;

export type CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeploymentsActionsItemEnvironmentsList =
  Array<string>;
export const CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeploymentsActionsItemEnvironmentsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeploymentsActionsItemEnvironmentsList>;

export interface CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeploymentsActionsItem {
  environments: CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeploymentsActionsItemEnvironmentsList;
  slug: string;
}
export const CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeploymentsActionsItem =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      environments:
        CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeploymentsActionsItemEnvironmentsList,
      slug: S.String,
    }),
  ).annotate({
    identifier: "CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeploymentsActionsItem",
  }) as any as S.Schema<CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeploymentsActionsItem>;

export type CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeploymentsActionsList =
  Array<CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeploymentsActionsItem>;
export const CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeploymentsActionsList =
  /*@__PURE__*/ S.Array(
    CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeploymentsActionsItem,
  ) as any as S.Schema<CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeploymentsActionsList>;

export interface CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeployments {
  actions: CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeploymentsActionsList;
  required: boolean;
}
export const CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeployments =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      actions: CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeploymentsActionsList,
      required: S.Boolean,
    }),
  ).annotate({
    identifier: "CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeployments",
  }) as any as S.Schema<CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeployments>;

export type CreateStorageStoresBlobResponseStoreProjectsMetadataItemEnvironmentsList =
  Array<string>;
export const CreateStorageStoresBlobResponseStoreProjectsMetadataItemEnvironmentsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<CreateStorageStoresBlobResponseStoreProjectsMetadataItemEnvironmentsList>;

export type CreateStorageStoresBlobResponseStoreProjectsMetadataItemEnvironmentVariablesList =
  Array<string>;
export const CreateStorageStoresBlobResponseStoreProjectsMetadataItemEnvironmentVariablesList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<CreateStorageStoresBlobResponseStoreProjectsMetadataItemEnvironmentVariablesList>;

export type CreateStorageStoresBlobResponseStoreProjectsMetadataItemFramework =
  | "actix-web"
  | "angular"
  | "ash"
  | "astro"
  | "axum"
  | "blitzjs"
  | "brunch"
  | "bun"
  | "container"
  | "create-react-app"
  | "django"
  | "docusaurus"
  | "docusaurus-2"
  | "dojo"
  | "eleventy"
  | "elysia"
  | "ember"
  | "eve"
  | "express"
  | "factory-eve"
  | "fastapi"
  | "fasthtml"
  | "fastify"
  | "flask"
  | "gatsby"
  | "go"
  | "gridsome"
  | "h3"
  | "hexo"
  | "hono"
  | "hugo"
  | "hydrogen"
  | "ionic-angular"
  | "ionic-react"
  | "jekyll"
  | "koa"
  | "mastra"
  | "middleman"
  | "nestjs"
  | "nextjs"
  | "nitro"
  | "node"
  | "nuxtjs"
  | "parcel"
  | "polymer"
  | "preact"
  | "python"
  | "react-router"
  | "redwoodjs"
  | "remix"
  | "ruby"
  | "rust"
  | "saber"
  | "sanity"
  | "sanity-v2"
  | "sapper"
  | "scully"
  | "services"
  | "solidstart"
  | "solidstart-1"
  | "stencil"
  | "storybook"
  | "svelte"
  | "sveltekit"
  | "sveltekit-1"
  | "tanstack-start"
  | "tanstack-start-lovable"
  | "umijs"
  | "vite"
  | "vitepress"
  | "vue"
  | "vuepress"
  | "xmcp"
  | "zola";
export const CreateStorageStoresBlobResponseStoreProjectsMetadataItemFramework = S.String;

export interface CreateStorageStoresBlobResponseStoreProjectsMetadataItem {
  deployments?: CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeployments;
  environments: CreateStorageStoresBlobResponseStoreProjectsMetadataItemEnvironmentsList;
  environmentVariables: CreateStorageStoresBlobResponseStoreProjectsMetadataItemEnvironmentVariablesList;
  envVarPrefix: string | null;
  framework?: CreateStorageStoresBlobResponseStoreProjectsMetadataItemFramework | null;
  id: string;
  latestDeployment?: string;
  makeEnvVarsSensitive?: boolean;
  name: string;
  projectId: string;
}
export const CreateStorageStoresBlobResponseStoreProjectsMetadataItem = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      deployments: S.optional(CreateStorageStoresBlobResponseStoreProjectsMetadataItemDeployments),
      environments: CreateStorageStoresBlobResponseStoreProjectsMetadataItemEnvironmentsList,
      environmentVariables:
        CreateStorageStoresBlobResponseStoreProjectsMetadataItemEnvironmentVariablesList,
      envVarPrefix: S.NullOr(S.String),
      framework: S.optional(
        S.NullOr(CreateStorageStoresBlobResponseStoreProjectsMetadataItemFramework),
      ),
      id: S.String,
      latestDeployment: S.optional(S.String),
      makeEnvVarsSensitive: S.optional(S.Boolean),
      name: S.String,
      projectId: S.String,
    }),
).annotate({
  identifier: "CreateStorageStoresBlobResponseStoreProjectsMetadataItem",
}) as any as S.Schema<CreateStorageStoresBlobResponseStoreProjectsMetadataItem>;

export type CreateStorageStoresBlobResponseStoreProjectsMetadataList =
  Array<CreateStorageStoresBlobResponseStoreProjectsMetadataItem>;
export const CreateStorageStoresBlobResponseStoreProjectsMetadataList = /*@__PURE__*/ S.Array(
  CreateStorageStoresBlobResponseStoreProjectsMetadataItem,
) as any as S.Schema<CreateStorageStoresBlobResponseStoreProjectsMetadataList>;

export type CreateStorageStoresBlobResponseStoreStatus =
  | "available"
  | "error"
  | "initializing"
  | "limits-exceeded-suspended"
  | "limits-exceeded-suspended-store-count"
  | "onboarding"
  | "suspended"
  | "uninstalled";
export const CreateStorageStoresBlobResponseStoreStatus = S.String;

export type CreateStorageStoresBlobResponseStoreAccess = "private" | "public";
export const CreateStorageStoresBlobResponseStoreAccess = S.String;

/** A project-default store is a private blob store that is lazily created per-project, uses OIDC auth instead of read-write tokens, and cannot be modified through standard store mutation APIs. Undefined for legacy stores. */
export type CreateStorageStoresBlobResponseStoreKind = "project-default" | "user-created";
export const CreateStorageStoresBlobResponseStoreKind = S.String;

export type CreateStorageStoresBlobResponseStoreRegion =
  | "arn1"
  | "bom1"
  | "cdg1"
  | "cle1"
  | "cpt1"
  | "dub1"
  | "dxb1"
  | "fra1"
  | "gru1"
  | "hkg1"
  | "hnd1"
  | "iad1"
  | "icn1"
  | "kix1"
  | "lhr1"
  | "pdx1"
  | "sfo1"
  | "sin1"
  | "syd1"
  | "yul1";
export const CreateStorageStoresBlobResponseStoreRegion = S.String;

export interface CreateStorageStoresBlobResponseStore {
  projectFilter?: CreateStorageStoresBlobResponseStoreProjectFilter;
  projectsMetadata: CreateStorageStoresBlobResponseStoreProjectsMetadataList;
  status: CreateStorageStoresBlobResponseStoreStatus | null;
  totalConnectedProjects?: number;
  usageQuotaExceeded: boolean;
  access?: CreateStorageStoresBlobResponseStoreAccess;
  /** A project-default store is a private blob store that is lazily created per-project, uses OIDC auth instead of read-write tokens, and cannot be modified through standard store mutation APIs. Undefined for legacy stores. */
  kind?: CreateStorageStoresBlobResponseStoreKind;
  /** The project this store is scoped to. Set for project-default stores and user-created stores with enforced project association. */
  projectId?: string;
  count: number;
  isTokenExpired: boolean;
  region: CreateStorageStoresBlobResponseStoreRegion;
  size: number;
}
export const CreateStorageStoresBlobResponseStore = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectFilter: S.optional(CreateStorageStoresBlobResponseStoreProjectFilter),
    projectsMetadata: CreateStorageStoresBlobResponseStoreProjectsMetadataList,
    status: S.NullOr(CreateStorageStoresBlobResponseStoreStatus),
    totalConnectedProjects: S.optional(S.Number),
    usageQuotaExceeded: S.Boolean,
    access: S.optional(CreateStorageStoresBlobResponseStoreAccess),
    kind: S.optional(CreateStorageStoresBlobResponseStoreKind),
    projectId: S.optional(S.String),
    count: S.Number,
    isTokenExpired: S.Boolean,
    region: CreateStorageStoresBlobResponseStoreRegion,
    size: S.Number,
  }),
).annotate({
  identifier: "CreateStorageStoresBlobResponseStore",
}) as any as S.Schema<CreateStorageStoresBlobResponseStore>;

export interface CreateStorageStoresBlobResponse {
  store: CreateStorageStoresBlobResponseStore | null;
}
export const CreateStorageStoresBlobResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    store: S.NullOr(CreateStorageStoresBlobResponseStore),
  }),
).annotate({
  identifier: "CreateStorageStoresBlobResponse",
}) as any as S.Schema<CreateStorageStoresBlobResponse>;

export interface DeleteStorageStoresBlobRequest {
  id: string;
}
export const DeleteStorageStoresBlobRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "DELETE", uri: "/storage/stores/blob/{id}", code: 200 })),
).annotate({
  identifier: "DeleteStorageStoresBlobRequest",
}) as any as S.Schema<DeleteStorageStoresBlobRequest>;

export interface DeleteStorageStoresBlobResponse {
  id: string;
}
export const DeleteStorageStoresBlobResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
  }),
).annotate({
  identifier: "DeleteStorageStoresBlobResponse",
}) as any as S.Schema<DeleteStorageStoresBlobResponse>;

export interface GetStorageStoreRequest {
  id: string;
  skip_metadata?: boolean;
  include_guides?: boolean;
}
export const GetStorageStoreRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
    skip_metadata: S.optional(S.Boolean.pipe(T.Query("skip-metadata"))),
    include_guides: S.optional(S.Boolean.pipe(T.Query("include-guides"))),
  }).pipe(T.Http({ method: "GET", uri: "/storage/stores/{id}", code: 200 })),
).annotate({ identifier: "GetStorageStoreRequest" }) as any as S.Schema<GetStorageStoreRequest>;

export type GetStorageStoreResponseStoreProjectFilterGitOwnersList = Array<string>;
export const GetStorageStoreResponseStoreProjectFilterGitOwnersList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<GetStorageStoreResponseStoreProjectFilterGitOwnersList>;

export type GetStorageStoreResponseStoreProjectFilterGitProvidersCase0Item =
  | "bitbucket"
  | "github"
  | "gitlab";
export const GetStorageStoreResponseStoreProjectFilterGitProvidersCase0Item = S.String;

export type GetStorageStoreResponseStoreProjectFilterGitProvidersCase0List =
  Array<GetStorageStoreResponseStoreProjectFilterGitProvidersCase0Item>;
export const GetStorageStoreResponseStoreProjectFilterGitProvidersCase0List = /*@__PURE__*/ S.Array(
  GetStorageStoreResponseStoreProjectFilterGitProvidersCase0Item,
) as any as S.Schema<GetStorageStoreResponseStoreProjectFilterGitProvidersCase0List>;

export type GetStorageStoreResponseStoreProjectFilterGitProvidersCase1 = "*";
export const GetStorageStoreResponseStoreProjectFilterGitProvidersCase1 = S.String;

export type GetStorageStoreResponseStoreProjectFilterGitProviders =
  | GetStorageStoreResponseStoreProjectFilterGitProvidersCase0List
  | GetStorageStoreResponseStoreProjectFilterGitProvidersCase1;
export const GetStorageStoreResponseStoreProjectFilterGitProviders =
  S.Unknown as any as S.Schema<GetStorageStoreResponseStoreProjectFilterGitProviders>;

export type GetStorageStoreResponseStoreProjectFilterGitReposList = Array<string>;
export const GetStorageStoreResponseStoreProjectFilterGitReposList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<GetStorageStoreResponseStoreProjectFilterGitReposList>;

export interface GetStorageStoreResponseStoreProjectFilterGit {
  owners?: GetStorageStoreResponseStoreProjectFilterGitOwnersList;
  providers: GetStorageStoreResponseStoreProjectFilterGitProviders;
  repos?: GetStorageStoreResponseStoreProjectFilterGitReposList;
}
export const GetStorageStoreResponseStoreProjectFilterGit = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    owners: S.optional(GetStorageStoreResponseStoreProjectFilterGitOwnersList),
    providers: GetStorageStoreResponseStoreProjectFilterGitProviders,
    repos: S.optional(GetStorageStoreResponseStoreProjectFilterGitReposList),
  }),
).annotate({
  identifier: "GetStorageStoreResponseStoreProjectFilterGit",
}) as any as S.Schema<GetStorageStoreResponseStoreProjectFilterGit>;

export interface GetStorageStoreResponseStoreProjectFilter {
  git?: GetStorageStoreResponseStoreProjectFilterGit;
}
export const GetStorageStoreResponseStoreProjectFilter = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    git: S.optional(GetStorageStoreResponseStoreProjectFilterGit),
  }),
).annotate({
  identifier: "GetStorageStoreResponseStoreProjectFilter",
}) as any as S.Schema<GetStorageStoreResponseStoreProjectFilter>;

export type GetStorageStoreResponseStoreProjectsMetadataItemDeploymentsActionsItemEnvironmentsList =
  Array<string>;
export const GetStorageStoreResponseStoreProjectsMetadataItemDeploymentsActionsItemEnvironmentsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<GetStorageStoreResponseStoreProjectsMetadataItemDeploymentsActionsItemEnvironmentsList>;

export interface GetStorageStoreResponseStoreProjectsMetadataItemDeploymentsActionsItem {
  environments: GetStorageStoreResponseStoreProjectsMetadataItemDeploymentsActionsItemEnvironmentsList;
  slug: string;
}
export const GetStorageStoreResponseStoreProjectsMetadataItemDeploymentsActionsItem =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      environments:
        GetStorageStoreResponseStoreProjectsMetadataItemDeploymentsActionsItemEnvironmentsList,
      slug: S.String,
    }),
  ).annotate({
    identifier: "GetStorageStoreResponseStoreProjectsMetadataItemDeploymentsActionsItem",
  }) as any as S.Schema<GetStorageStoreResponseStoreProjectsMetadataItemDeploymentsActionsItem>;

export type GetStorageStoreResponseStoreProjectsMetadataItemDeploymentsActionsList =
  Array<GetStorageStoreResponseStoreProjectsMetadataItemDeploymentsActionsItem>;
export const GetStorageStoreResponseStoreProjectsMetadataItemDeploymentsActionsList =
  /*@__PURE__*/ S.Array(
    GetStorageStoreResponseStoreProjectsMetadataItemDeploymentsActionsItem,
  ) as any as S.Schema<GetStorageStoreResponseStoreProjectsMetadataItemDeploymentsActionsList>;

export interface GetStorageStoreResponseStoreProjectsMetadataItemDeployments {
  actions: GetStorageStoreResponseStoreProjectsMetadataItemDeploymentsActionsList;
  required: boolean;
}
export const GetStorageStoreResponseStoreProjectsMetadataItemDeployments = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      actions: GetStorageStoreResponseStoreProjectsMetadataItemDeploymentsActionsList,
      required: S.Boolean,
    }),
).annotate({
  identifier: "GetStorageStoreResponseStoreProjectsMetadataItemDeployments",
}) as any as S.Schema<GetStorageStoreResponseStoreProjectsMetadataItemDeployments>;

export type GetStorageStoreResponseStoreProjectsMetadataItemEnvironmentsList = Array<string>;
export const GetStorageStoreResponseStoreProjectsMetadataItemEnvironmentsList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<GetStorageStoreResponseStoreProjectsMetadataItemEnvironmentsList>;

export type GetStorageStoreResponseStoreProjectsMetadataItemEnvironmentVariablesList =
  Array<string>;
export const GetStorageStoreResponseStoreProjectsMetadataItemEnvironmentVariablesList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<GetStorageStoreResponseStoreProjectsMetadataItemEnvironmentVariablesList>;

export type GetStorageStoreResponseStoreProjectsMetadataItemFramework =
  | "actix-web"
  | "angular"
  | "ash"
  | "astro"
  | "axum"
  | "blitzjs"
  | "brunch"
  | "bun"
  | "container"
  | "create-react-app"
  | "django"
  | "docusaurus"
  | "docusaurus-2"
  | "dojo"
  | "eleventy"
  | "elysia"
  | "ember"
  | "eve"
  | "express"
  | "factory-eve"
  | "fastapi"
  | "fasthtml"
  | "fastify"
  | "flask"
  | "gatsby"
  | "go"
  | "gridsome"
  | "h3"
  | "hexo"
  | "hono"
  | "hugo"
  | "hydrogen"
  | "ionic-angular"
  | "ionic-react"
  | "jekyll"
  | "koa"
  | "mastra"
  | "middleman"
  | "nestjs"
  | "nextjs"
  | "nitro"
  | "node"
  | "nuxtjs"
  | "parcel"
  | "polymer"
  | "preact"
  | "python"
  | "react-router"
  | "redwoodjs"
  | "remix"
  | "ruby"
  | "rust"
  | "saber"
  | "sanity"
  | "sanity-v2"
  | "sapper"
  | "scully"
  | "services"
  | "solidstart"
  | "solidstart-1"
  | "stencil"
  | "storybook"
  | "svelte"
  | "sveltekit"
  | "sveltekit-1"
  | "tanstack-start"
  | "tanstack-start-lovable"
  | "umijs"
  | "vite"
  | "vitepress"
  | "vue"
  | "vuepress"
  | "xmcp"
  | "zola";
export const GetStorageStoreResponseStoreProjectsMetadataItemFramework = S.String;

export interface GetStorageStoreResponseStoreProjectsMetadataItem {
  deployments?: GetStorageStoreResponseStoreProjectsMetadataItemDeployments;
  environments: GetStorageStoreResponseStoreProjectsMetadataItemEnvironmentsList;
  environmentVariables: GetStorageStoreResponseStoreProjectsMetadataItemEnvironmentVariablesList;
  envVarPrefix: string | null;
  framework?: GetStorageStoreResponseStoreProjectsMetadataItemFramework | null;
  id: string;
  latestDeployment?: string;
  makeEnvVarsSensitive?: boolean;
  name: string;
  projectId: string;
}
export const GetStorageStoreResponseStoreProjectsMetadataItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    deployments: S.optional(GetStorageStoreResponseStoreProjectsMetadataItemDeployments),
    environments: GetStorageStoreResponseStoreProjectsMetadataItemEnvironmentsList,
    environmentVariables: GetStorageStoreResponseStoreProjectsMetadataItemEnvironmentVariablesList,
    envVarPrefix: S.NullOr(S.String),
    framework: S.optional(S.NullOr(GetStorageStoreResponseStoreProjectsMetadataItemFramework)),
    id: S.String,
    latestDeployment: S.optional(S.String),
    makeEnvVarsSensitive: S.optional(S.Boolean),
    name: S.String,
    projectId: S.String,
  }),
).annotate({
  identifier: "GetStorageStoreResponseStoreProjectsMetadataItem",
}) as any as S.Schema<GetStorageStoreResponseStoreProjectsMetadataItem>;

export type GetStorageStoreResponseStoreProjectsMetadataList =
  Array<GetStorageStoreResponseStoreProjectsMetadataItem>;
export const GetStorageStoreResponseStoreProjectsMetadataList = /*@__PURE__*/ S.Array(
  GetStorageStoreResponseStoreProjectsMetadataItem,
) as any as S.Schema<GetStorageStoreResponseStoreProjectsMetadataList>;

export type GetStorageStoreResponseStoreStatus =
  | "available"
  | "error"
  | "initializing"
  | "limits-exceeded-suspended"
  | "limits-exceeded-suspended-store-count"
  | "onboarding"
  | "suspended"
  | "uninstalled";
export const GetStorageStoreResponseStoreStatus = S.String;

export interface GetStorageStoreResponseStore {
  projectFilter?: GetStorageStoreResponseStoreProjectFilter;
  projectsMetadata: GetStorageStoreResponseStoreProjectsMetadataList;
  status: GetStorageStoreResponseStoreStatus | null;
  totalConnectedProjects?: number;
  usageQuotaExceeded: boolean;
}
export const GetStorageStoreResponseStore = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectFilter: S.optional(GetStorageStoreResponseStoreProjectFilter),
    projectsMetadata: GetStorageStoreResponseStoreProjectsMetadataList,
    status: S.NullOr(GetStorageStoreResponseStoreStatus),
    totalConnectedProjects: S.optional(S.Number),
    usageQuotaExceeded: S.Boolean,
  }),
).annotate({
  identifier: "GetStorageStoreResponseStore",
}) as any as S.Schema<GetStorageStoreResponseStore>;

export interface GetStorageStoreResponse {
  store: GetStorageStoreResponseStore;
}
export const GetStorageStoreResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    store: GetStorageStoreResponseStore,
  }),
).annotate({ identifier: "GetStorageStoreResponse" }) as any as S.Schema<GetStorageStoreResponse>;

export type CreateStorageStoresBlobError =
  | BadRequest
  | PaymentRequired
  | Forbidden
  | NotFound
  | Conflict
  | VercelOpError;
/** Create a Blob store */
export const createStorageStoresBlob: API.OperationMethod<
  CreateStorageStoresBlobRequest,
  CreateStorageStoresBlobResponse,
  CreateStorageStoresBlobError,
  VercelOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateStorageStoresBlobRequest,
  output: CreateStorageStoresBlobResponse,
  errors: [BadRequest, PaymentRequired, Forbidden, NotFound, Conflict],
  protocol: VercelProtocol,
  retry: Retry.Retry,
}));

export type DeleteStorageStoresBlobError =
  | BadRequest
  | Forbidden
  | NotFound
  | Conflict
  | VercelOpError;
/** Delete a Blob store */
export const deleteStorageStoresBlob: API.OperationMethod<
  DeleteStorageStoresBlobRequest,
  DeleteStorageStoresBlobResponse,
  DeleteStorageStoresBlobError,
  VercelOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteStorageStoresBlobRequest,
  output: DeleteStorageStoresBlobResponse,
  errors: [BadRequest, Forbidden, NotFound, Conflict],
  protocol: VercelProtocol,
  retry: Retry.Retry,
}));

export type GetStorageStoreError = BadRequest | Forbidden | NotFound | VercelOpError;
/** Get a store */
export const getStorageStore: API.OperationMethod<
  GetStorageStoreRequest,
  GetStorageStoreResponse,
  GetStorageStoreError,
  VercelOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetStorageStoreRequest,
  output: GetStorageStoreResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: VercelProtocol,
  retry: Retry.Retry,
}));
